// Source: AllFlagDatas.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: AllFlagDatas.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllFlagDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          *FlagDatas             `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllFlagDatas) Reset() {
	*x = AllFlagDatas{}
	mi := &file_AllFlagDatas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllFlagDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllFlagDatas) ProtoMessage() {}

func (x *AllFlagDatas) ProtoReflect() protoreflect.Message {
	mi := &file_AllFlagDatas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllFlagDatas.ProtoReflect.Descriptor instead.
func (*AllFlagDatas) Descriptor() ([]byte, []int) {
	return file_AllFlagDatas_proto_rawDescGZIP(), []int{0}
}

func (x *AllFlagDatas) GetFlag() *FlagDatas {
	if x != nil {
		return x.Flag
	}
	return nil
}

type FlagDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []*FlagConfigure       `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagDatas) Reset() {
	*x = FlagDatas{}
	mi := &file_AllFlagDatas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagDatas) ProtoMessage() {}

func (x *FlagDatas) ProtoReflect() protoreflect.Message {
	mi := &file_AllFlagDatas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagDatas.ProtoReflect.Descriptor instead.
func (*FlagDatas) Descriptor() ([]byte, []int) {
	return file_AllFlagDatas_proto_rawDescGZIP(), []int{1}
}

func (x *FlagDatas) GetDatas() []*FlagConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type FlagConfigure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TextID        int32                  `protobuf:"varint,2,opt,name=TextID,proto3" json:"TextID,omitempty"`
	IconID        int32                  `protobuf:"varint,3,opt,name=IconID,proto3" json:"IconID,omitempty"`
	SceneID       int32                  `protobuf:"varint,4,opt,name=SceneID,proto3" json:"SceneID,omitempty"`
	FlagGroupInfo []*FlagGroupInfo       `protobuf:"bytes,5,rep,name=FlagGroupInfo,proto3" json:"FlagGroupInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagConfigure) Reset() {
	*x = FlagConfigure{}
	mi := &file_AllFlagDatas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagConfigure) ProtoMessage() {}

func (x *FlagConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_AllFlagDatas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagConfigure.ProtoReflect.Descriptor instead.
func (*FlagConfigure) Descriptor() ([]byte, []int) {
	return file_AllFlagDatas_proto_rawDescGZIP(), []int{2}
}

func (x *FlagConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *FlagConfigure) GetTextID() int32 {
	if x != nil {
		return x.TextID
	}
	return 0
}

func (x *FlagConfigure) GetIconID() int32 {
	if x != nil {
		return x.IconID
	}
	return 0
}

func (x *FlagConfigure) GetSceneID() int32 {
	if x != nil {
		return x.SceneID
	}
	return 0
}

func (x *FlagConfigure) GetFlagGroupInfo() []*FlagGroupInfo {
	if x != nil {
		return x.FlagGroupInfo
	}
	return nil
}

type FlagGroupInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	IsItemUnlock   bool                   `protobuf:"varint,2,opt,name=IsItemUnlock,proto3" json:"IsItemUnlock,omitempty"`
	NewMissionType int32                  `protobuf:"varint,3,opt,name=NewMissionType,proto3" json:"NewMissionType,omitempty"`
	RelationID     int32                  `protobuf:"varint,4,opt,name=RelationID,proto3" json:"RelationID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlagGroupInfo) Reset() {
	*x = FlagGroupInfo{}
	mi := &file_AllFlagDatas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagGroupInfo) ProtoMessage() {}

func (x *FlagGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_AllFlagDatas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagGroupInfo.ProtoReflect.Descriptor instead.
func (*FlagGroupInfo) Descriptor() ([]byte, []int) {
	return file_AllFlagDatas_proto_rawDescGZIP(), []int{3}
}

func (x *FlagGroupInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FlagGroupInfo) GetIsItemUnlock() bool {
	if x != nil {
		return x.IsItemUnlock
	}
	return false
}

func (x *FlagGroupInfo) GetNewMissionType() int32 {
	if x != nil {
		return x.NewMissionType
	}
	return 0
}

func (x *FlagGroupInfo) GetRelationID() int32 {
	if x != nil {
		return x.RelationID
	}
	return 0
}

var File_AllFlagDatas_proto protoreflect.FileDescriptor

const file_AllFlagDatas_proto_rawDesc = "" +
	"\n" +
	"\x12AllFlagDatas.proto\x12\x05excel\"4\n" +
	"\fAllFlagDatas\x12$\n" +
	"\x04Flag\x18\x01 \x01(\v2\x10.excel.FlagDatasR\x04Flag\"7\n" +
	"\tFlagDatas\x12*\n" +
	"\x05Datas\x18\x01 \x03(\v2\x14.excel.FlagConfigureR\x05Datas\"\xa5\x01\n" +
	"\rFlagConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x16\n" +
	"\x06TextID\x18\x02 \x01(\x05R\x06TextID\x12\x16\n" +
	"\x06IconID\x18\x03 \x01(\x05R\x06IconID\x12\x18\n" +
	"\aSceneID\x18\x04 \x01(\x05R\aSceneID\x12:\n" +
	"\rFlagGroupInfo\x18\x05 \x03(\v2\x14.excel.FlagGroupInfoR\rFlagGroupInfo\"\x91\x01\n" +
	"\rFlagGroupInfo\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\x05R\x05Index\x12\"\n" +
	"\fIsItemUnlock\x18\x02 \x01(\bR\fIsItemUnlock\x12&\n" +
	"\x0eNewMissionType\x18\x03 \x01(\x05R\x0eNewMissionType\x12\x1e\n" +
	"\n" +
	"RelationID\x18\x04 \x01(\x05R\n" +
	"RelationIDB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_AllFlagDatas_proto_rawDescOnce sync.Once
	file_AllFlagDatas_proto_rawDescData []byte
)

func file_AllFlagDatas_proto_rawDescGZIP() []byte {
	file_AllFlagDatas_proto_rawDescOnce.Do(func() {
		file_AllFlagDatas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AllFlagDatas_proto_rawDesc), len(file_AllFlagDatas_proto_rawDesc)))
	})
	return file_AllFlagDatas_proto_rawDescData
}

var file_AllFlagDatas_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_AllFlagDatas_proto_goTypes = []any{
	(*AllFlagDatas)(nil),  // 0: excel.AllFlagDatas
	(*FlagDatas)(nil),     // 1: excel.FlagDatas
	(*FlagConfigure)(nil), // 2: excel.FlagConfigure
	(*FlagGroupInfo)(nil), // 3: excel.FlagGroupInfo
}
var file_AllFlagDatas_proto_depIdxs = []int32{
	1, // 0: excel.AllFlagDatas.Flag:type_name -> excel.FlagDatas
	2, // 1: excel.FlagDatas.Datas:type_name -> excel.FlagConfigure
	3, // 2: excel.FlagConfigure.FlagGroupInfo:type_name -> excel.FlagGroupInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_AllFlagDatas_proto_init() }
func file_AllFlagDatas_proto_init() {
	if File_AllFlagDatas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AllFlagDatas_proto_rawDesc), len(file_AllFlagDatas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AllFlagDatas_proto_goTypes,
		DependencyIndexes: file_AllFlagDatas_proto_depIdxs,
		MessageInfos:      file_AllFlagDatas_proto_msgTypes,
	}.Build()
	File_AllFlagDatas_proto = out.File
	file_AllFlagDatas_proto_goTypes = nil
	file_AllFlagDatas_proto_depIdxs = nil
}
