// Source: AllGemDuelAchieveDatas.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: AllGemDuelAchieveDatas.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllGemDuelAchieveDatas struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GemDuelAchieve *GemDuelAchieveDatas   `protobuf:"bytes,1,opt,name=GemDuelAchieve,proto3" json:"GemDuelAchieve,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllGemDuelAchieveDatas) Reset() {
	*x = AllGemDuelAchieveDatas{}
	mi := &file_AllGemDuelAchieveDatas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllGemDuelAchieveDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllGemDuelAchieveDatas) ProtoMessage() {}

func (x *AllGemDuelAchieveDatas) ProtoReflect() protoreflect.Message {
	mi := &file_AllGemDuelAchieveDatas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllGemDuelAchieveDatas.ProtoReflect.Descriptor instead.
func (*AllGemDuelAchieveDatas) Descriptor() ([]byte, []int) {
	return file_AllGemDuelAchieveDatas_proto_rawDescGZIP(), []int{0}
}

func (x *AllGemDuelAchieveDatas) GetGemDuelAchieve() *GemDuelAchieveDatas {
	if x != nil {
		return x.GemDuelAchieve
	}
	return nil
}

type GemDuelAchieveDatas struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Datas         []*GemDuelAchieveConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GemDuelAchieveDatas) Reset() {
	*x = GemDuelAchieveDatas{}
	mi := &file_AllGemDuelAchieveDatas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GemDuelAchieveDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GemDuelAchieveDatas) ProtoMessage() {}

func (x *GemDuelAchieveDatas) ProtoReflect() protoreflect.Message {
	mi := &file_AllGemDuelAchieveDatas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GemDuelAchieveDatas.ProtoReflect.Descriptor instead.
func (*GemDuelAchieveDatas) Descriptor() ([]byte, []int) {
	return file_AllGemDuelAchieveDatas_proto_rawDescGZIP(), []int{1}
}

func (x *GemDuelAchieveDatas) GetDatas() []*GemDuelAchieveConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type GemDuelAchieveConfigure struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ID                          int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Param                       []int32                `protobuf:"varint,2,rep,packed,name=Param,proto3" json:"Param,omitempty"`
	CountParam                  int32                  `protobuf:"varint,3,opt,name=CountParam,proto3" json:"CountParam,omitempty"`
	NeweGemDuelAchieveCondition int32                  `protobuf:"varint,4,opt,name=NeweGemDuelAchieveCondition,proto3" json:"NeweGemDuelAchieveCondition,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GemDuelAchieveConfigure) Reset() {
	*x = GemDuelAchieveConfigure{}
	mi := &file_AllGemDuelAchieveDatas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GemDuelAchieveConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GemDuelAchieveConfigure) ProtoMessage() {}

func (x *GemDuelAchieveConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_AllGemDuelAchieveDatas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GemDuelAchieveConfigure.ProtoReflect.Descriptor instead.
func (*GemDuelAchieveConfigure) Descriptor() ([]byte, []int) {
	return file_AllGemDuelAchieveDatas_proto_rawDescGZIP(), []int{2}
}

func (x *GemDuelAchieveConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GemDuelAchieveConfigure) GetParam() []int32 {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *GemDuelAchieveConfigure) GetCountParam() int32 {
	if x != nil {
		return x.CountParam
	}
	return 0
}

func (x *GemDuelAchieveConfigure) GetNeweGemDuelAchieveCondition() int32 {
	if x != nil {
		return x.NeweGemDuelAchieveCondition
	}
	return 0
}

var File_AllGemDuelAchieveDatas_proto protoreflect.FileDescriptor

const file_AllGemDuelAchieveDatas_proto_rawDesc = "" +
	"\n" +
	"\x1cAllGemDuelAchieveDatas.proto\x12\x05excel\"\\\n" +
	"\x16AllGemDuelAchieveDatas\x12B\n" +
	"\x0eGemDuelAchieve\x18\x01 \x01(\v2\x1a.excel.GemDuelAchieveDatasR\x0eGemDuelAchieve\"K\n" +
	"\x13GemDuelAchieveDatas\x124\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1e.excel.GemDuelAchieveConfigureR\x05Datas\"\xa1\x01\n" +
	"\x17GemDuelAchieveConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x14\n" +
	"\x05Param\x18\x02 \x03(\x05R\x05Param\x12\x1e\n" +
	"\n" +
	"CountParam\x18\x03 \x01(\x05R\n" +
	"CountParam\x12@\n" +
	"\x1bNeweGemDuelAchieveCondition\x18\x04 \x01(\x05R\x1bNeweGemDuelAchieveConditionB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_AllGemDuelAchieveDatas_proto_rawDescOnce sync.Once
	file_AllGemDuelAchieveDatas_proto_rawDescData []byte
)

func file_AllGemDuelAchieveDatas_proto_rawDescGZIP() []byte {
	file_AllGemDuelAchieveDatas_proto_rawDescOnce.Do(func() {
		file_AllGemDuelAchieveDatas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AllGemDuelAchieveDatas_proto_rawDesc), len(file_AllGemDuelAchieveDatas_proto_rawDesc)))
	})
	return file_AllGemDuelAchieveDatas_proto_rawDescData
}

var file_AllGemDuelAchieveDatas_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AllGemDuelAchieveDatas_proto_goTypes = []any{
	(*AllGemDuelAchieveDatas)(nil),  // 0: excel.AllGemDuelAchieveDatas
	(*GemDuelAchieveDatas)(nil),     // 1: excel.GemDuelAchieveDatas
	(*GemDuelAchieveConfigure)(nil), // 2: excel.GemDuelAchieveConfigure
}
var file_AllGemDuelAchieveDatas_proto_depIdxs = []int32{
	1, // 0: excel.AllGemDuelAchieveDatas.GemDuelAchieve:type_name -> excel.GemDuelAchieveDatas
	2, // 1: excel.GemDuelAchieveDatas.Datas:type_name -> excel.GemDuelAchieveConfigure
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AllGemDuelAchieveDatas_proto_init() }
func file_AllGemDuelAchieveDatas_proto_init() {
	if File_AllGemDuelAchieveDatas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AllGemDuelAchieveDatas_proto_rawDesc), len(file_AllGemDuelAchieveDatas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AllGemDuelAchieveDatas_proto_goTypes,
		DependencyIndexes: file_AllGemDuelAchieveDatas_proto_depIdxs,
		MessageInfos:      file_AllGemDuelAchieveDatas_proto_msgTypes,
	}.Build()
	File_AllGemDuelAchieveDatas_proto = out.File
	file_AllGemDuelAchieveDatas_proto_goTypes = nil
	file_AllGemDuelAchieveDatas_proto_depIdxs = nil
}
