// Source: ItemLevel.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ItemLevel.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllItemLevelDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemLevel     *ItemLevelDatas        `protobuf:"bytes,1,opt,name=ItemLevel,proto3" json:"ItemLevel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllItemLevelDatas) Reset() {
	*x = AllItemLevelDatas{}
	mi := &file_ItemLevel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllItemLevelDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllItemLevelDatas) ProtoMessage() {}

func (x *AllItemLevelDatas) ProtoReflect() protoreflect.Message {
	mi := &file_ItemLevel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllItemLevelDatas.ProtoReflect.Descriptor instead.
func (*AllItemLevelDatas) Descriptor() ([]byte, []int) {
	return file_ItemLevel_proto_rawDescGZIP(), []int{0}
}

func (x *AllItemLevelDatas) GetItemLevel() *ItemLevelDatas {
	if x != nil {
		return x.ItemLevel
	}
	return nil
}

type ItemLevelDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []*ItemLevelConfigure  `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemLevelDatas) Reset() {
	*x = ItemLevelDatas{}
	mi := &file_ItemLevel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLevelDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLevelDatas) ProtoMessage() {}

func (x *ItemLevelDatas) ProtoReflect() protoreflect.Message {
	mi := &file_ItemLevel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLevelDatas.ProtoReflect.Descriptor instead.
func (*ItemLevelDatas) Descriptor() ([]byte, []int) {
	return file_ItemLevel_proto_rawDescGZIP(), []int{1}
}

func (x *ItemLevelDatas) GetDatas() []*ItemLevelConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type ItemLevelConfigure struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ID                int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ItemLevelItem     []*ItemLevelItem       `protobuf:"bytes,2,rep,name=ItemLevelItem,proto3" json:"ItemLevelItem,omitempty"`
	NewItemSourceEnum int32                  `protobuf:"varint,3,opt,name=NewItemSourceEnum,proto3" json:"NewItemSourceEnum,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemLevelConfigure) Reset() {
	*x = ItemLevelConfigure{}
	mi := &file_ItemLevel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLevelConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLevelConfigure) ProtoMessage() {}

func (x *ItemLevelConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_ItemLevel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLevelConfigure.ProtoReflect.Descriptor instead.
func (*ItemLevelConfigure) Descriptor() ([]byte, []int) {
	return file_ItemLevel_proto_rawDescGZIP(), []int{2}
}

func (x *ItemLevelConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ItemLevelConfigure) GetItemLevelItem() []*ItemLevelItem {
	if x != nil {
		return x.ItemLevelItem
	}
	return nil
}

func (x *ItemLevelConfigure) GetNewItemSourceEnum() int32 {
	if x != nil {
		return x.NewItemSourceEnum
	}
	return 0
}

type ItemLevelItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"`
	VoiceID       int32                  `protobuf:"varint,2,opt,name=VoiceID,proto3" json:"VoiceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemLevelItem) Reset() {
	*x = ItemLevelItem{}
	mi := &file_ItemLevel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLevelItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLevelItem) ProtoMessage() {}

func (x *ItemLevelItem) ProtoReflect() protoreflect.Message {
	mi := &file_ItemLevel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLevelItem.ProtoReflect.Descriptor instead.
func (*ItemLevelItem) Descriptor() ([]byte, []int) {
	return file_ItemLevel_proto_rawDescGZIP(), []int{3}
}

func (x *ItemLevelItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ItemLevelItem) GetVoiceID() int32 {
	if x != nil {
		return x.VoiceID
	}
	return 0
}

var File_ItemLevel_proto protoreflect.FileDescriptor

const file_ItemLevel_proto_rawDesc = "" +
	"\n" +
	"\x0fItemLevel.proto\x12\x05excel\"H\n" +
	"\x11AllItemLevelDatas\x123\n" +
	"\tItemLevel\x18\x01 \x01(\v2\x15.excel.ItemLevelDatasR\tItemLevel\"A\n" +
	"\x0eItemLevelDatas\x12/\n" +
	"\x05Datas\x18\x01 \x03(\v2\x19.excel.ItemLevelConfigureR\x05Datas\"\x8e\x01\n" +
	"\x12ItemLevelConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12:\n" +
	"\rItemLevelItem\x18\x02 \x03(\v2\x14.excel.ItemLevelItemR\rItemLevelItem\x12,\n" +
	"\x11NewItemSourceEnum\x18\x03 \x01(\x05R\x11NewItemSourceEnum\"?\n" +
	"\rItemLevelItem\x12\x14\n" +
	"\x05Level\x18\x01 \x01(\x05R\x05Level\x12\x18\n" +
	"\aVoiceID\x18\x02 \x01(\x05R\aVoiceIDB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_ItemLevel_proto_rawDescOnce sync.Once
	file_ItemLevel_proto_rawDescData []byte
)

func file_ItemLevel_proto_rawDescGZIP() []byte {
	file_ItemLevel_proto_rawDescOnce.Do(func() {
		file_ItemLevel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ItemLevel_proto_rawDesc), len(file_ItemLevel_proto_rawDesc)))
	})
	return file_ItemLevel_proto_rawDescData
}

var file_ItemLevel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ItemLevel_proto_goTypes = []any{
	(*AllItemLevelDatas)(nil),  // 0: excel.AllItemLevelDatas
	(*ItemLevelDatas)(nil),     // 1: excel.ItemLevelDatas
	(*ItemLevelConfigure)(nil), // 2: excel.ItemLevelConfigure
	(*ItemLevelItem)(nil),      // 3: excel.ItemLevelItem
}
var file_ItemLevel_proto_depIdxs = []int32{
	1, // 0: excel.AllItemLevelDatas.ItemLevel:type_name -> excel.ItemLevelDatas
	2, // 1: excel.ItemLevelDatas.Datas:type_name -> excel.ItemLevelConfigure
	3, // 2: excel.ItemLevelConfigure.ItemLevelItem:type_name -> excel.ItemLevelItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ItemLevel_proto_init() }
func file_ItemLevel_proto_init() {
	if File_ItemLevel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ItemLevel_proto_rawDesc), len(file_ItemLevel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ItemLevel_proto_goTypes,
		DependencyIndexes: file_ItemLevel_proto_depIdxs,
		MessageInfos:      file_ItemLevel_proto_msgTypes,
	}.Build()
	File_ItemLevel_proto = out.File
	file_ItemLevel_proto_goTypes = nil
	file_ItemLevel_proto_depIdxs = nil
}
