// Source: NpcQuest.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: NpcQuest.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllNpcQuestDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcQuestInfo  *NpcQuestInfoDatas     `protobuf:"bytes,1,opt,name=NpcQuestInfo,proto3" json:"NpcQuestInfo,omitempty"`
	NpcQuestPool  *NpcQuestPoolDatas     `protobuf:"bytes,2,opt,name=NpcQuestPool,proto3" json:"NpcQuestPool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllNpcQuestDatas) Reset() {
	*x = AllNpcQuestDatas{}
	mi := &file_NpcQuest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllNpcQuestDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNpcQuestDatas) ProtoMessage() {}

func (x *AllNpcQuestDatas) ProtoReflect() protoreflect.Message {
	mi := &file_NpcQuest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNpcQuestDatas.ProtoReflect.Descriptor instead.
func (*AllNpcQuestDatas) Descriptor() ([]byte, []int) {
	return file_NpcQuest_proto_rawDescGZIP(), []int{0}
}

func (x *AllNpcQuestDatas) GetNpcQuestInfo() *NpcQuestInfoDatas {
	if x != nil {
		return x.NpcQuestInfo
	}
	return nil
}

func (x *AllNpcQuestDatas) GetNpcQuestPool() *NpcQuestPoolDatas {
	if x != nil {
		return x.NpcQuestPool
	}
	return nil
}

type NpcQuestInfoDatas struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Datas         []*NpcQuestInfoConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcQuestInfoDatas) Reset() {
	*x = NpcQuestInfoDatas{}
	mi := &file_NpcQuest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcQuestInfoDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcQuestInfoDatas) ProtoMessage() {}

func (x *NpcQuestInfoDatas) ProtoReflect() protoreflect.Message {
	mi := &file_NpcQuest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcQuestInfoDatas.ProtoReflect.Descriptor instead.
func (*NpcQuestInfoDatas) Descriptor() ([]byte, []int) {
	return file_NpcQuest_proto_rawDescGZIP(), []int{1}
}

func (x *NpcQuestInfoDatas) GetDatas() []*NpcQuestInfoConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type NpcQuestInfoConfigure struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ID                 int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RefreshTime        int32                  `protobuf:"varint,2,opt,name=RefreshTime,proto3" json:"RefreshTime,omitempty"`
	RefreshCurrency    int32                  `protobuf:"varint,3,opt,name=RefreshCurrency,proto3" json:"RefreshCurrency,omitempty"`
	RefreshCost        int32                  `protobuf:"varint,4,opt,name=RefreshCost,proto3" json:"RefreshCost,omitempty"`
	QuestPoolID        int32                  `protobuf:"varint,5,opt,name=QuestPoolID,proto3" json:"QuestPoolID,omitempty"`
	OpenedDialog       int32                  `protobuf:"varint,6,opt,name=OpenedDialog,proto3" json:"OpenedDialog,omitempty"`
	NormalDonateDialog int32                  `protobuf:"varint,7,opt,name=NormalDonateDialog,proto3" json:"NormalDonateDialog,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NpcQuestInfoConfigure) Reset() {
	*x = NpcQuestInfoConfigure{}
	mi := &file_NpcQuest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcQuestInfoConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcQuestInfoConfigure) ProtoMessage() {}

func (x *NpcQuestInfoConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_NpcQuest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcQuestInfoConfigure.ProtoReflect.Descriptor instead.
func (*NpcQuestInfoConfigure) Descriptor() ([]byte, []int) {
	return file_NpcQuest_proto_rawDescGZIP(), []int{2}
}

func (x *NpcQuestInfoConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NpcQuestInfoConfigure) GetRefreshTime() int32 {
	if x != nil {
		return x.RefreshTime
	}
	return 0
}

func (x *NpcQuestInfoConfigure) GetRefreshCurrency() int32 {
	if x != nil {
		return x.RefreshCurrency
	}
	return 0
}

func (x *NpcQuestInfoConfigure) GetRefreshCost() int32 {
	if x != nil {
		return x.RefreshCost
	}
	return 0
}

func (x *NpcQuestInfoConfigure) GetQuestPoolID() int32 {
	if x != nil {
		return x.QuestPoolID
	}
	return 0
}

func (x *NpcQuestInfoConfigure) GetOpenedDialog() int32 {
	if x != nil {
		return x.OpenedDialog
	}
	return 0
}

func (x *NpcQuestInfoConfigure) GetNormalDonateDialog() int32 {
	if x != nil {
		return x.NormalDonateDialog
	}
	return 0
}

type NpcQuestPoolDatas struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Datas         []*NpcQuestPoolConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcQuestPoolDatas) Reset() {
	*x = NpcQuestPoolDatas{}
	mi := &file_NpcQuest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcQuestPoolDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcQuestPoolDatas) ProtoMessage() {}

func (x *NpcQuestPoolDatas) ProtoReflect() protoreflect.Message {
	mi := &file_NpcQuest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcQuestPoolDatas.ProtoReflect.Descriptor instead.
func (*NpcQuestPoolDatas) Descriptor() ([]byte, []int) {
	return file_NpcQuest_proto_rawDescGZIP(), []int{3}
}

func (x *NpcQuestPoolDatas) GetDatas() []*NpcQuestPoolConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type NpcQuestPoolConfigure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NpcQuestPools []*NpcQuestPoolItem    `protobuf:"bytes,2,rep,name=NpcQuestPools,proto3" json:"NpcQuestPools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcQuestPoolConfigure) Reset() {
	*x = NpcQuestPoolConfigure{}
	mi := &file_NpcQuest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcQuestPoolConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcQuestPoolConfigure) ProtoMessage() {}

func (x *NpcQuestPoolConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_NpcQuest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcQuestPoolConfigure.ProtoReflect.Descriptor instead.
func (*NpcQuestPoolConfigure) Descriptor() ([]byte, []int) {
	return file_NpcQuest_proto_rawDescGZIP(), []int{4}
}

func (x *NpcQuestPoolConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NpcQuestPoolConfigure) GetNpcQuestPools() []*NpcQuestPoolItem {
	if x != nil {
		return x.NpcQuestPools
	}
	return nil
}

type NpcQuestPoolItem struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	QuestID                int32                     `protobuf:"varint,1,opt,name=QuestID,proto3" json:"QuestID,omitempty"`
	NeedItemID             int32                     `protobuf:"varint,2,opt,name=NeedItemID,proto3" json:"NeedItemID,omitempty"`
	NeedItemMinCount       int32                     `protobuf:"varint,3,opt,name=NeedItemMinCount,proto3" json:"NeedItemMinCount,omitempty"`
	NeedItemMaxCount       int32                     `protobuf:"varint,4,opt,name=NeedItemMaxCount,proto3" json:"NeedItemMaxCount,omitempty"`
	AmityAdd               int32                     `protobuf:"varint,5,opt,name=AmityAdd,proto3" json:"AmityAdd,omitempty"`
	Weight                 int32                     `protobuf:"varint,6,opt,name=Weight,proto3" json:"Weight,omitempty"`
	NeedMinLevel           int32                     `protobuf:"varint,7,opt,name=NeedMinLevel,proto3" json:"NeedMinLevel,omitempty"`
	NeedMaxLevel           int32                     `protobuf:"varint,8,opt,name=NeedMaxLevel,proto3" json:"NeedMaxLevel,omitempty"`
	NpcQuestPoolRewardItem []*NpcQuestPoolRewardItem `protobuf:"bytes,9,rep,name=NpcQuestPoolRewardItem,proto3" json:"NpcQuestPoolRewardItem,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NpcQuestPoolItem) Reset() {
	*x = NpcQuestPoolItem{}
	mi := &file_NpcQuest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcQuestPoolItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcQuestPoolItem) ProtoMessage() {}

func (x *NpcQuestPoolItem) ProtoReflect() protoreflect.Message {
	mi := &file_NpcQuest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcQuestPoolItem.ProtoReflect.Descriptor instead.
func (*NpcQuestPoolItem) Descriptor() ([]byte, []int) {
	return file_NpcQuest_proto_rawDescGZIP(), []int{5}
}

func (x *NpcQuestPoolItem) GetQuestID() int32 {
	if x != nil {
		return x.QuestID
	}
	return 0
}

func (x *NpcQuestPoolItem) GetNeedItemID() int32 {
	if x != nil {
		return x.NeedItemID
	}
	return 0
}

func (x *NpcQuestPoolItem) GetNeedItemMinCount() int32 {
	if x != nil {
		return x.NeedItemMinCount
	}
	return 0
}

func (x *NpcQuestPoolItem) GetNeedItemMaxCount() int32 {
	if x != nil {
		return x.NeedItemMaxCount
	}
	return 0
}

func (x *NpcQuestPoolItem) GetAmityAdd() int32 {
	if x != nil {
		return x.AmityAdd
	}
	return 0
}

func (x *NpcQuestPoolItem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *NpcQuestPoolItem) GetNeedMinLevel() int32 {
	if x != nil {
		return x.NeedMinLevel
	}
	return 0
}

func (x *NpcQuestPoolItem) GetNeedMaxLevel() int32 {
	if x != nil {
		return x.NeedMaxLevel
	}
	return 0
}

func (x *NpcQuestPoolItem) GetNpcQuestPoolRewardItem() []*NpcQuestPoolRewardItem {
	if x != nil {
		return x.NpcQuestPoolRewardItem
	}
	return nil
}

type NpcQuestPoolRewardItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RewardItemID    int32                  `protobuf:"varint,1,opt,name=RewardItemID,proto3" json:"RewardItemID,omitempty"`
	RewardItemCount int32                  `protobuf:"varint,2,opt,name=RewardItemCount,proto3" json:"RewardItemCount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NpcQuestPoolRewardItem) Reset() {
	*x = NpcQuestPoolRewardItem{}
	mi := &file_NpcQuest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcQuestPoolRewardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcQuestPoolRewardItem) ProtoMessage() {}

func (x *NpcQuestPoolRewardItem) ProtoReflect() protoreflect.Message {
	mi := &file_NpcQuest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcQuestPoolRewardItem.ProtoReflect.Descriptor instead.
func (*NpcQuestPoolRewardItem) Descriptor() ([]byte, []int) {
	return file_NpcQuest_proto_rawDescGZIP(), []int{6}
}

func (x *NpcQuestPoolRewardItem) GetRewardItemID() int32 {
	if x != nil {
		return x.RewardItemID
	}
	return 0
}

func (x *NpcQuestPoolRewardItem) GetRewardItemCount() int32 {
	if x != nil {
		return x.RewardItemCount
	}
	return 0
}

var File_NpcQuest_proto protoreflect.FileDescriptor

const file_NpcQuest_proto_rawDesc = "" +
	"\n" +
	"\x0eNpcQuest.proto\x12\x05excel\"\x8e\x01\n" +
	"\x10AllNpcQuestDatas\x12<\n" +
	"\fNpcQuestInfo\x18\x01 \x01(\v2\x18.excel.NpcQuestInfoDatasR\fNpcQuestInfo\x12<\n" +
	"\fNpcQuestPool\x18\x02 \x01(\v2\x18.excel.NpcQuestPoolDatasR\fNpcQuestPool\"G\n" +
	"\x11NpcQuestInfoDatas\x122\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1c.excel.NpcQuestInfoConfigureR\x05Datas\"\x8b\x02\n" +
	"\x15NpcQuestInfoConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12 \n" +
	"\vRefreshTime\x18\x02 \x01(\x05R\vRefreshTime\x12(\n" +
	"\x0fRefreshCurrency\x18\x03 \x01(\x05R\x0fRefreshCurrency\x12 \n" +
	"\vRefreshCost\x18\x04 \x01(\x05R\vRefreshCost\x12 \n" +
	"\vQuestPoolID\x18\x05 \x01(\x05R\vQuestPoolID\x12\"\n" +
	"\fOpenedDialog\x18\x06 \x01(\x05R\fOpenedDialog\x12.\n" +
	"\x12NormalDonateDialog\x18\a \x01(\x05R\x12NormalDonateDialog\"G\n" +
	"\x11NpcQuestPoolDatas\x122\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1c.excel.NpcQuestPoolConfigureR\x05Datas\"f\n" +
	"\x15NpcQuestPoolConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12=\n" +
	"\rNpcQuestPools\x18\x02 \x03(\v2\x17.excel.NpcQuestPoolItemR\rNpcQuestPools\"\xf7\x02\n" +
	"\x10NpcQuestPoolItem\x12\x18\n" +
	"\aQuestID\x18\x01 \x01(\x05R\aQuestID\x12\x1e\n" +
	"\n" +
	"NeedItemID\x18\x02 \x01(\x05R\n" +
	"NeedItemID\x12*\n" +
	"\x10NeedItemMinCount\x18\x03 \x01(\x05R\x10NeedItemMinCount\x12*\n" +
	"\x10NeedItemMaxCount\x18\x04 \x01(\x05R\x10NeedItemMaxCount\x12\x1a\n" +
	"\bAmityAdd\x18\x05 \x01(\x05R\bAmityAdd\x12\x16\n" +
	"\x06Weight\x18\x06 \x01(\x05R\x06Weight\x12\"\n" +
	"\fNeedMinLevel\x18\a \x01(\x05R\fNeedMinLevel\x12\"\n" +
	"\fNeedMaxLevel\x18\b \x01(\x05R\fNeedMaxLevel\x12U\n" +
	"\x16NpcQuestPoolRewardItem\x18\t \x03(\v2\x1d.excel.NpcQuestPoolRewardItemR\x16NpcQuestPoolRewardItem\"f\n" +
	"\x16NpcQuestPoolRewardItem\x12\"\n" +
	"\fRewardItemID\x18\x01 \x01(\x05R\fRewardItemID\x12(\n" +
	"\x0fRewardItemCount\x18\x02 \x01(\x05R\x0fRewardItemCountB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_NpcQuest_proto_rawDescOnce sync.Once
	file_NpcQuest_proto_rawDescData []byte
)

func file_NpcQuest_proto_rawDescGZIP() []byte {
	file_NpcQuest_proto_rawDescOnce.Do(func() {
		file_NpcQuest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_NpcQuest_proto_rawDesc), len(file_NpcQuest_proto_rawDesc)))
	})
	return file_NpcQuest_proto_rawDescData
}

var file_NpcQuest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_NpcQuest_proto_goTypes = []any{
	(*AllNpcQuestDatas)(nil),       // 0: excel.AllNpcQuestDatas
	(*NpcQuestInfoDatas)(nil),      // 1: excel.NpcQuestInfoDatas
	(*NpcQuestInfoConfigure)(nil),  // 2: excel.NpcQuestInfoConfigure
	(*NpcQuestPoolDatas)(nil),      // 3: excel.NpcQuestPoolDatas
	(*NpcQuestPoolConfigure)(nil),  // 4: excel.NpcQuestPoolConfigure
	(*NpcQuestPoolItem)(nil),       // 5: excel.NpcQuestPoolItem
	(*NpcQuestPoolRewardItem)(nil), // 6: excel.NpcQuestPoolRewardItem
}
var file_NpcQuest_proto_depIdxs = []int32{
	1, // 0: excel.AllNpcQuestDatas.NpcQuestInfo:type_name -> excel.NpcQuestInfoDatas
	3, // 1: excel.AllNpcQuestDatas.NpcQuestPool:type_name -> excel.NpcQuestPoolDatas
	2, // 2: excel.NpcQuestInfoDatas.Datas:type_name -> excel.NpcQuestInfoConfigure
	4, // 3: excel.NpcQuestPoolDatas.Datas:type_name -> excel.NpcQuestPoolConfigure
	5, // 4: excel.NpcQuestPoolConfigure.NpcQuestPools:type_name -> excel.NpcQuestPoolItem
	6, // 5: excel.NpcQuestPoolItem.NpcQuestPoolRewardItem:type_name -> excel.NpcQuestPoolRewardItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_NpcQuest_proto_init() }
func file_NpcQuest_proto_init() {
	if File_NpcQuest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_NpcQuest_proto_rawDesc), len(file_NpcQuest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_NpcQuest_proto_goTypes,
		DependencyIndexes: file_NpcQuest_proto_depIdxs,
		MessageInfos:      file_NpcQuest_proto_msgTypes,
	}.Build()
	File_NpcQuest_proto = out.File
	file_NpcQuest_proto_goTypes = nil
	file_NpcQuest_proto_depIdxs = nil
}
