// Source: PlayerUnlock.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: PlayerUnlock.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllPlayerUnlockDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUnlock  *PlayerUnlockDatas     `protobuf:"bytes,1,opt,name=PlayerUnlock,proto3" json:"PlayerUnlock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllPlayerUnlockDatas) Reset() {
	*x = AllPlayerUnlockDatas{}
	mi := &file_PlayerUnlock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllPlayerUnlockDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPlayerUnlockDatas) ProtoMessage() {}

func (x *AllPlayerUnlockDatas) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerUnlock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPlayerUnlockDatas.ProtoReflect.Descriptor instead.
func (*AllPlayerUnlockDatas) Descriptor() ([]byte, []int) {
	return file_PlayerUnlock_proto_rawDescGZIP(), []int{0}
}

func (x *AllPlayerUnlockDatas) GetPlayerUnlock() *PlayerUnlockDatas {
	if x != nil {
		return x.PlayerUnlock
	}
	return nil
}

type PlayerUnlockDatas struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Datas         []*PlayerUnlockConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUnlockDatas) Reset() {
	*x = PlayerUnlockDatas{}
	mi := &file_PlayerUnlock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUnlockDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUnlockDatas) ProtoMessage() {}

func (x *PlayerUnlockDatas) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerUnlock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUnlockDatas.ProtoReflect.Descriptor instead.
func (*PlayerUnlockDatas) Descriptor() ([]byte, []int) {
	return file_PlayerUnlock_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerUnlockDatas) GetDatas() []*PlayerUnlockConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type PlayerUnlockConfigure struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ID                    int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Para                  int32                  `protobuf:"varint,2,opt,name=Para,proto3" json:"Para,omitempty"`
	ItemID                int32                  `protobuf:"varint,3,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	IsShowTips            bool                   `protobuf:"varint,4,opt,name=IsShowTips,proto3" json:"IsShowTips,omitempty"`
	NewUnlockFunctionType int32                  `protobuf:"varint,5,opt,name=NewUnlockFunctionType,proto3" json:"NewUnlockFunctionType,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerUnlockConfigure) Reset() {
	*x = PlayerUnlockConfigure{}
	mi := &file_PlayerUnlock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUnlockConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUnlockConfigure) ProtoMessage() {}

func (x *PlayerUnlockConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerUnlock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUnlockConfigure.ProtoReflect.Descriptor instead.
func (*PlayerUnlockConfigure) Descriptor() ([]byte, []int) {
	return file_PlayerUnlock_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerUnlockConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PlayerUnlockConfigure) GetPara() int32 {
	if x != nil {
		return x.Para
	}
	return 0
}

func (x *PlayerUnlockConfigure) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *PlayerUnlockConfigure) GetIsShowTips() bool {
	if x != nil {
		return x.IsShowTips
	}
	return false
}

func (x *PlayerUnlockConfigure) GetNewUnlockFunctionType() int32 {
	if x != nil {
		return x.NewUnlockFunctionType
	}
	return 0
}

var File_PlayerUnlock_proto protoreflect.FileDescriptor

const file_PlayerUnlock_proto_rawDesc = "" +
	"\n" +
	"\x12PlayerUnlock.proto\x12\x05excel\"T\n" +
	"\x14AllPlayerUnlockDatas\x12<\n" +
	"\fPlayerUnlock\x18\x01 \x01(\v2\x18.excel.PlayerUnlockDatasR\fPlayerUnlock\"G\n" +
	"\x11PlayerUnlockDatas\x122\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1c.excel.PlayerUnlockConfigureR\x05Datas\"\xa9\x01\n" +
	"\x15PlayerUnlockConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Para\x18\x02 \x01(\x05R\x04Para\x12\x16\n" +
	"\x06ItemID\x18\x03 \x01(\x05R\x06ItemID\x12\x1e\n" +
	"\n" +
	"IsShowTips\x18\x04 \x01(\bR\n" +
	"IsShowTips\x124\n" +
	"\x15NewUnlockFunctionType\x18\x05 \x01(\x05R\x15NewUnlockFunctionTypeB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_PlayerUnlock_proto_rawDescOnce sync.Once
	file_PlayerUnlock_proto_rawDescData []byte
)

func file_PlayerUnlock_proto_rawDescGZIP() []byte {
	file_PlayerUnlock_proto_rawDescOnce.Do(func() {
		file_PlayerUnlock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PlayerUnlock_proto_rawDesc), len(file_PlayerUnlock_proto_rawDesc)))
	})
	return file_PlayerUnlock_proto_rawDescData
}

var file_PlayerUnlock_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PlayerUnlock_proto_goTypes = []any{
	(*AllPlayerUnlockDatas)(nil),  // 0: excel.AllPlayerUnlockDatas
	(*PlayerUnlockDatas)(nil),     // 1: excel.PlayerUnlockDatas
	(*PlayerUnlockConfigure)(nil), // 2: excel.PlayerUnlockConfigure
}
var file_PlayerUnlock_proto_depIdxs = []int32{
	1, // 0: excel.AllPlayerUnlockDatas.PlayerUnlock:type_name -> excel.PlayerUnlockDatas
	2, // 1: excel.PlayerUnlockDatas.Datas:type_name -> excel.PlayerUnlockConfigure
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PlayerUnlock_proto_init() }
func file_PlayerUnlock_proto_init() {
	if File_PlayerUnlock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PlayerUnlock_proto_rawDesc), len(file_PlayerUnlock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerUnlock_proto_goTypes,
		DependencyIndexes: file_PlayerUnlock_proto_depIdxs,
		MessageInfos:      file_PlayerUnlock_proto_msgTypes,
	}.Build()
	File_PlayerUnlock_proto = out.File
	file_PlayerUnlock_proto_goTypes = nil
	file_PlayerUnlock_proto_depIdxs = nil
}
