// Source: PlayerAbility.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: PlayerAbility.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllPlayerAbilityDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerAbility *PlayerAbilityDatas    `protobuf:"bytes,1,opt,name=PlayerAbility,proto3" json:"PlayerAbility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllPlayerAbilityDatas) Reset() {
	*x = AllPlayerAbilityDatas{}
	mi := &file_PlayerAbility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllPlayerAbilityDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPlayerAbilityDatas) ProtoMessage() {}

func (x *AllPlayerAbilityDatas) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerAbility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPlayerAbilityDatas.ProtoReflect.Descriptor instead.
func (*AllPlayerAbilityDatas) Descriptor() ([]byte, []int) {
	return file_PlayerAbility_proto_rawDescGZIP(), []int{0}
}

func (x *AllPlayerAbilityDatas) GetPlayerAbility() *PlayerAbilityDatas {
	if x != nil {
		return x.PlayerAbility
	}
	return nil
}

type PlayerAbilityDatas struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Datas         []*PlayerAbilityConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAbilityDatas) Reset() {
	*x = PlayerAbilityDatas{}
	mi := &file_PlayerAbility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAbilityDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAbilityDatas) ProtoMessage() {}

func (x *PlayerAbilityDatas) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerAbility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAbilityDatas.ProtoReflect.Descriptor instead.
func (*PlayerAbilityDatas) Descriptor() ([]byte, []int) {
	return file_PlayerAbility_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerAbilityDatas) GetDatas() []*PlayerAbilityConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type PlayerAbilityConfigure struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ID                   int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Para                 float32                `protobuf:"fixed32,2,opt,name=Para,proto3" json:"Para,omitempty"`
	SceneIDs             []int32                `protobuf:"varint,3,rep,packed,name=SceneIDs,proto3" json:"SceneIDs,omitempty"`
	NewUnlockAbilityType int32                  `protobuf:"varint,4,opt,name=NewUnlockAbilityType,proto3" json:"NewUnlockAbilityType,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlayerAbilityConfigure) Reset() {
	*x = PlayerAbilityConfigure{}
	mi := &file_PlayerAbility_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAbilityConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAbilityConfigure) ProtoMessage() {}

func (x *PlayerAbilityConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerAbility_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAbilityConfigure.ProtoReflect.Descriptor instead.
func (*PlayerAbilityConfigure) Descriptor() ([]byte, []int) {
	return file_PlayerAbility_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerAbilityConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PlayerAbilityConfigure) GetPara() float32 {
	if x != nil {
		return x.Para
	}
	return 0
}

func (x *PlayerAbilityConfigure) GetSceneIDs() []int32 {
	if x != nil {
		return x.SceneIDs
	}
	return nil
}

func (x *PlayerAbilityConfigure) GetNewUnlockAbilityType() int32 {
	if x != nil {
		return x.NewUnlockAbilityType
	}
	return 0
}

var File_PlayerAbility_proto protoreflect.FileDescriptor

const file_PlayerAbility_proto_rawDesc = "" +
	"\n" +
	"\x13PlayerAbility.proto\x12\x05excel\"X\n" +
	"\x15AllPlayerAbilityDatas\x12?\n" +
	"\rPlayerAbility\x18\x01 \x01(\v2\x19.excel.PlayerAbilityDatasR\rPlayerAbility\"I\n" +
	"\x12PlayerAbilityDatas\x123\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1d.excel.PlayerAbilityConfigureR\x05Datas\"\x8c\x01\n" +
	"\x16PlayerAbilityConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Para\x18\x02 \x01(\x02R\x04Para\x12\x1a\n" +
	"\bSceneIDs\x18\x03 \x03(\x05R\bSceneIDs\x122\n" +
	"\x14NewUnlockAbilityType\x18\x04 \x01(\x05R\x14NewUnlockAbilityTypeB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_PlayerAbility_proto_rawDescOnce sync.Once
	file_PlayerAbility_proto_rawDescData []byte
)

func file_PlayerAbility_proto_rawDescGZIP() []byte {
	file_PlayerAbility_proto_rawDescOnce.Do(func() {
		file_PlayerAbility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PlayerAbility_proto_rawDesc), len(file_PlayerAbility_proto_rawDesc)))
	})
	return file_PlayerAbility_proto_rawDescData
}

var file_PlayerAbility_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PlayerAbility_proto_goTypes = []any{
	(*AllPlayerAbilityDatas)(nil),  // 0: excel.AllPlayerAbilityDatas
	(*PlayerAbilityDatas)(nil),     // 1: excel.PlayerAbilityDatas
	(*PlayerAbilityConfigure)(nil), // 2: excel.PlayerAbilityConfigure
}
var file_PlayerAbility_proto_depIdxs = []int32{
	1, // 0: excel.AllPlayerAbilityDatas.PlayerAbility:type_name -> excel.PlayerAbilityDatas
	2, // 1: excel.PlayerAbilityDatas.Datas:type_name -> excel.PlayerAbilityConfigure
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PlayerAbility_proto_init() }
func file_PlayerAbility_proto_init() {
	if File_PlayerAbility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PlayerAbility_proto_rawDesc), len(file_PlayerAbility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerAbility_proto_goTypes,
		DependencyIndexes: file_PlayerAbility_proto_depIdxs,
		MessageInfos:      file_PlayerAbility_proto_msgTypes,
	}.Build()
	File_PlayerAbility_proto = out.File
	file_PlayerAbility_proto_goTypes = nil
	file_PlayerAbility_proto_depIdxs = nil
}
