// Source: QuickObtaining.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: QuickObtaining.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllQuickObtainingDatas struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuickObtaining *QuickObtainingDatas   `protobuf:"bytes,1,opt,name=QuickObtaining,proto3" json:"QuickObtaining,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllQuickObtainingDatas) Reset() {
	*x = AllQuickObtainingDatas{}
	mi := &file_QuickObtaining_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllQuickObtainingDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllQuickObtainingDatas) ProtoMessage() {}

func (x *AllQuickObtainingDatas) ProtoReflect() protoreflect.Message {
	mi := &file_QuickObtaining_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllQuickObtainingDatas.ProtoReflect.Descriptor instead.
func (*AllQuickObtainingDatas) Descriptor() ([]byte, []int) {
	return file_QuickObtaining_proto_rawDescGZIP(), []int{0}
}

func (x *AllQuickObtainingDatas) GetQuickObtaining() *QuickObtainingDatas {
	if x != nil {
		return x.QuickObtaining
	}
	return nil
}

type QuickObtainingDatas struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Datas         []*QuickObtainingConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickObtainingDatas) Reset() {
	*x = QuickObtainingDatas{}
	mi := &file_QuickObtaining_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickObtainingDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickObtainingDatas) ProtoMessage() {}

func (x *QuickObtainingDatas) ProtoReflect() protoreflect.Message {
	mi := &file_QuickObtaining_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickObtainingDatas.ProtoReflect.Descriptor instead.
func (*QuickObtainingDatas) Descriptor() ([]byte, []int) {
	return file_QuickObtaining_proto_rawDescGZIP(), []int{1}
}

func (x *QuickObtainingDatas) GetDatas() []*QuickObtainingConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type QuickObtainingConfigure struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ID                 int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	QuickObtainingItem []*QuickObtainingItem  `protobuf:"bytes,2,rep,name=QuickObtainingItem,proto3" json:"QuickObtainingItem,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuickObtainingConfigure) Reset() {
	*x = QuickObtainingConfigure{}
	mi := &file_QuickObtaining_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickObtainingConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickObtainingConfigure) ProtoMessage() {}

func (x *QuickObtainingConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_QuickObtaining_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickObtainingConfigure.ProtoReflect.Descriptor instead.
func (*QuickObtainingConfigure) Descriptor() ([]byte, []int) {
	return file_QuickObtaining_proto_rawDescGZIP(), []int{2}
}

func (x *QuickObtainingConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *QuickObtainingConfigure) GetQuickObtainingItem() []*QuickObtainingItem {
	if x != nil {
		return x.QuickObtainingItem
	}
	return nil
}

type QuickObtainingItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayerLevel         int32                  `protobuf:"varint,1,opt,name=PlayerLevel,proto3" json:"PlayerLevel,omitempty"`
	Num                 int32                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	NeedVitality        int32                  `protobuf:"varint,3,opt,name=NeedVitality,proto3" json:"NeedVitality,omitempty"`
	NeedSpecialcurrency int32                  `protobuf:"varint,4,opt,name=NeedSpecialcurrency,proto3" json:"NeedSpecialcurrency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QuickObtainingItem) Reset() {
	*x = QuickObtainingItem{}
	mi := &file_QuickObtaining_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickObtainingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickObtainingItem) ProtoMessage() {}

func (x *QuickObtainingItem) ProtoReflect() protoreflect.Message {
	mi := &file_QuickObtaining_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickObtainingItem.ProtoReflect.Descriptor instead.
func (*QuickObtainingItem) Descriptor() ([]byte, []int) {
	return file_QuickObtaining_proto_rawDescGZIP(), []int{3}
}

func (x *QuickObtainingItem) GetPlayerLevel() int32 {
	if x != nil {
		return x.PlayerLevel
	}
	return 0
}

func (x *QuickObtainingItem) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *QuickObtainingItem) GetNeedVitality() int32 {
	if x != nil {
		return x.NeedVitality
	}
	return 0
}

func (x *QuickObtainingItem) GetNeedSpecialcurrency() int32 {
	if x != nil {
		return x.NeedSpecialcurrency
	}
	return 0
}

var File_QuickObtaining_proto protoreflect.FileDescriptor

const file_QuickObtaining_proto_rawDesc = "" +
	"\n" +
	"\x14QuickObtaining.proto\x12\x05excel\"\\\n" +
	"\x16AllQuickObtainingDatas\x12B\n" +
	"\x0eQuickObtaining\x18\x01 \x01(\v2\x1a.excel.QuickObtainingDatasR\x0eQuickObtaining\"K\n" +
	"\x13QuickObtainingDatas\x124\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1e.excel.QuickObtainingConfigureR\x05Datas\"t\n" +
	"\x17QuickObtainingConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12I\n" +
	"\x12QuickObtainingItem\x18\x02 \x03(\v2\x19.excel.QuickObtainingItemR\x12QuickObtainingItem\"\x9e\x01\n" +
	"\x12QuickObtainingItem\x12 \n" +
	"\vPlayerLevel\x18\x01 \x01(\x05R\vPlayerLevel\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x05R\x03Num\x12\"\n" +
	"\fNeedVitality\x18\x03 \x01(\x05R\fNeedVitality\x120\n" +
	"\x13NeedSpecialcurrency\x18\x04 \x01(\x05R\x13NeedSpecialcurrencyB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_QuickObtaining_proto_rawDescOnce sync.Once
	file_QuickObtaining_proto_rawDescData []byte
)

func file_QuickObtaining_proto_rawDescGZIP() []byte {
	file_QuickObtaining_proto_rawDescOnce.Do(func() {
		file_QuickObtaining_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_QuickObtaining_proto_rawDesc), len(file_QuickObtaining_proto_rawDesc)))
	})
	return file_QuickObtaining_proto_rawDescData
}

var file_QuickObtaining_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_QuickObtaining_proto_goTypes = []any{
	(*AllQuickObtainingDatas)(nil),  // 0: excel.AllQuickObtainingDatas
	(*QuickObtainingDatas)(nil),     // 1: excel.QuickObtainingDatas
	(*QuickObtainingConfigure)(nil), // 2: excel.QuickObtainingConfigure
	(*QuickObtainingItem)(nil),      // 3: excel.QuickObtainingItem
}
var file_QuickObtaining_proto_depIdxs = []int32{
	1, // 0: excel.AllQuickObtainingDatas.QuickObtaining:type_name -> excel.QuickObtainingDatas
	2, // 1: excel.QuickObtainingDatas.Datas:type_name -> excel.QuickObtainingConfigure
	3, // 2: excel.QuickObtainingConfigure.QuickObtainingItem:type_name -> excel.QuickObtainingItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_QuickObtaining_proto_init() }
func file_QuickObtaining_proto_init() {
	if File_QuickObtaining_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_QuickObtaining_proto_rawDesc), len(file_QuickObtaining_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_QuickObtaining_proto_goTypes,
		DependencyIndexes: file_QuickObtaining_proto_depIdxs,
		MessageInfos:      file_QuickObtaining_proto_msgTypes,
	}.Build()
	File_QuickObtaining_proto = out.File
	file_QuickObtaining_proto_goTypes = nil
	file_QuickObtaining_proto_depIdxs = nil
}
