// Source: Spin.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Spin.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllSpinDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpinLevel     *SpinLevelDatas        `protobuf:"bytes,1,opt,name=SpinLevel,proto3" json:"SpinLevel,omitempty"`
	SpinItem      *SpinItemDatas         `protobuf:"bytes,2,opt,name=SpinItem,proto3" json:"SpinItem,omitempty"`
	SpinSpell     *SpinSpellDatas        `protobuf:"bytes,3,opt,name=SpinSpell,proto3" json:"SpinSpell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllSpinDatas) Reset() {
	*x = AllSpinDatas{}
	mi := &file_Spin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllSpinDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllSpinDatas) ProtoMessage() {}

func (x *AllSpinDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllSpinDatas.ProtoReflect.Descriptor instead.
func (*AllSpinDatas) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{0}
}

func (x *AllSpinDatas) GetSpinLevel() *SpinLevelDatas {
	if x != nil {
		return x.SpinLevel
	}
	return nil
}

func (x *AllSpinDatas) GetSpinItem() *SpinItemDatas {
	if x != nil {
		return x.SpinItem
	}
	return nil
}

func (x *AllSpinDatas) GetSpinSpell() *SpinSpellDatas {
	if x != nil {
		return x.SpinSpell
	}
	return nil
}

type SpinLevelDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []*SpinLevelConfigure  `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinLevelDatas) Reset() {
	*x = SpinLevelDatas{}
	mi := &file_Spin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinLevelDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinLevelDatas) ProtoMessage() {}

func (x *SpinLevelDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinLevelDatas.ProtoReflect.Descriptor instead.
func (*SpinLevelDatas) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{1}
}

func (x *SpinLevelDatas) GetDatas() []*SpinLevelConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type SpinLevelConfigure struct {
	state                     protoimpl.MessageState           `protogen:"open.v1"`
	ID                        int32                            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UpgradeLevelByProficiency int32                            `protobuf:"varint,2,opt,name=UpgradeLevelByProficiency,proto3" json:"UpgradeLevelByProficiency,omitempty"`
	NeedItemID                int32                            `protobuf:"varint,3,opt,name=NeedItemID,proto3" json:"NeedItemID,omitempty"`
	NeedItemCount             int32                            `protobuf:"varint,4,opt,name=NeedItemCount,proto3" json:"NeedItemCount,omitempty"`
	SpinLevelAchieve          []*SpinLevelAchieveConfigureItem `protobuf:"bytes,5,rep,name=SpinLevelAchieve,proto3" json:"SpinLevelAchieve,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SpinLevelConfigure) Reset() {
	*x = SpinLevelConfigure{}
	mi := &file_Spin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinLevelConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinLevelConfigure) ProtoMessage() {}

func (x *SpinLevelConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinLevelConfigure.ProtoReflect.Descriptor instead.
func (*SpinLevelConfigure) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{2}
}

func (x *SpinLevelConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SpinLevelConfigure) GetUpgradeLevelByProficiency() int32 {
	if x != nil {
		return x.UpgradeLevelByProficiency
	}
	return 0
}

func (x *SpinLevelConfigure) GetNeedItemID() int32 {
	if x != nil {
		return x.NeedItemID
	}
	return 0
}

func (x *SpinLevelConfigure) GetNeedItemCount() int32 {
	if x != nil {
		return x.NeedItemCount
	}
	return 0
}

func (x *SpinLevelConfigure) GetSpinLevelAchieve() []*SpinLevelAchieveConfigureItem {
	if x != nil {
		return x.SpinLevelAchieve
	}
	return nil
}

type SpinLevelAchieveConfigureItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AchieveConditionID int32                  `protobuf:"varint,1,opt,name=AchieveConditionID,proto3" json:"AchieveConditionID,omitempty"`
	Proficiency        int32                  `protobuf:"varint,2,opt,name=Proficiency,proto3" json:"Proficiency,omitempty"`
	CompleteLimit      int32                  `protobuf:"varint,3,opt,name=CompleteLimit,proto3" json:"CompleteLimit,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SpinLevelAchieveConfigureItem) Reset() {
	*x = SpinLevelAchieveConfigureItem{}
	mi := &file_Spin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinLevelAchieveConfigureItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinLevelAchieveConfigureItem) ProtoMessage() {}

func (x *SpinLevelAchieveConfigureItem) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinLevelAchieveConfigureItem.ProtoReflect.Descriptor instead.
func (*SpinLevelAchieveConfigureItem) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{3}
}

func (x *SpinLevelAchieveConfigureItem) GetAchieveConditionID() int32 {
	if x != nil {
		return x.AchieveConditionID
	}
	return 0
}

func (x *SpinLevelAchieveConfigureItem) GetProficiency() int32 {
	if x != nil {
		return x.Proficiency
	}
	return 0
}

func (x *SpinLevelAchieveConfigureItem) GetCompleteLimit() int32 {
	if x != nil {
		return x.CompleteLimit
	}
	return 0
}

type SpinItemDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []*SpinItemConfigure   `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinItemDatas) Reset() {
	*x = SpinItemDatas{}
	mi := &file_Spin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinItemDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinItemDatas) ProtoMessage() {}

func (x *SpinItemDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinItemDatas.ProtoReflect.Descriptor instead.
func (*SpinItemDatas) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{4}
}

func (x *SpinItemDatas) GetDatas() []*SpinItemConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type SpinItemConfigure struct {
	state                 protoimpl.MessageState      `protogen:"open.v1"`
	ID                    int32                       `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IsShow                bool                        `protobuf:"varint,2,opt,name=IsShow,proto3" json:"IsShow,omitempty"`
	IsHandbookShow        bool                        `protobuf:"varint,3,opt,name=IsHandbookShow,proto3" json:"IsHandbookShow,omitempty"`
	NeedShowbookItemID    int32                       `protobuf:"varint,4,opt,name=NeedShowbookItemID,proto3" json:"NeedShowbookItemID,omitempty"`
	NeedFormulaItemID     int32                       `protobuf:"varint,5,opt,name=NeedFormulaItemID,proto3" json:"NeedFormulaItemID,omitempty"`
	SpinLevel             int32                       `protobuf:"varint,6,opt,name=SpinLevel,proto3" json:"SpinLevel,omitempty"`
	NeedTime              int32                       `protobuf:"varint,7,opt,name=NeedTime,proto3" json:"NeedTime,omitempty"`
	OpeningTime           string                      `protobuf:"bytes,8,opt,name=OpeningTime,proto3" json:"OpeningTime,omitempty"`
	ClosingTime           string                      `protobuf:"bytes,9,opt,name=ClosingTime,proto3" json:"ClosingTime,omitempty"`
	NeedItemID            int32                       `protobuf:"varint,10,opt,name=NeedItemID,proto3" json:"NeedItemID,omitempty"`
	NeedItemCount         int32                       `protobuf:"varint,11,opt,name=NeedItemCount,proto3" json:"NeedItemCount,omitempty"`
	SpinItems             []*SpinItemConfigureItem    `protobuf:"bytes,12,rep,name=SpinItems,proto3" json:"SpinItems,omitempty"`
	SuccessfulProbability float32                     `protobuf:"fixed32,13,opt,name=SuccessfulProbability,proto3" json:"SuccessfulProbability,omitempty"`
	GetItemID             int32                       `protobuf:"varint,14,opt,name=GetItemID,proto3" json:"GetItemID,omitempty"`
	SpinAchieveRewards    []*SpinAchieveConfigureItem `protobuf:"bytes,15,rep,name=SpinAchieveRewards,proto3" json:"SpinAchieveRewards,omitempty"`
	NewSpinToolType       int32                       `protobuf:"varint,16,opt,name=NewSpinToolType,proto3" json:"NewSpinToolType,omitempty"`
	NewSpinType           int32                       `protobuf:"varint,17,opt,name=NewSpinType,proto3" json:"NewSpinType,omitempty"`
	NewSpinPageType       int32                       `protobuf:"varint,18,opt,name=NewSpinPageType,proto3" json:"NewSpinPageType,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SpinItemConfigure) Reset() {
	*x = SpinItemConfigure{}
	mi := &file_Spin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinItemConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinItemConfigure) ProtoMessage() {}

func (x *SpinItemConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinItemConfigure.ProtoReflect.Descriptor instead.
func (*SpinItemConfigure) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{5}
}

func (x *SpinItemConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SpinItemConfigure) GetIsShow() bool {
	if x != nil {
		return x.IsShow
	}
	return false
}

func (x *SpinItemConfigure) GetIsHandbookShow() bool {
	if x != nil {
		return x.IsHandbookShow
	}
	return false
}

func (x *SpinItemConfigure) GetNeedShowbookItemID() int32 {
	if x != nil {
		return x.NeedShowbookItemID
	}
	return 0
}

func (x *SpinItemConfigure) GetNeedFormulaItemID() int32 {
	if x != nil {
		return x.NeedFormulaItemID
	}
	return 0
}

func (x *SpinItemConfigure) GetSpinLevel() int32 {
	if x != nil {
		return x.SpinLevel
	}
	return 0
}

func (x *SpinItemConfigure) GetNeedTime() int32 {
	if x != nil {
		return x.NeedTime
	}
	return 0
}

func (x *SpinItemConfigure) GetOpeningTime() string {
	if x != nil {
		return x.OpeningTime
	}
	return ""
}

func (x *SpinItemConfigure) GetClosingTime() string {
	if x != nil {
		return x.ClosingTime
	}
	return ""
}

func (x *SpinItemConfigure) GetNeedItemID() int32 {
	if x != nil {
		return x.NeedItemID
	}
	return 0
}

func (x *SpinItemConfigure) GetNeedItemCount() int32 {
	if x != nil {
		return x.NeedItemCount
	}
	return 0
}

func (x *SpinItemConfigure) GetSpinItems() []*SpinItemConfigureItem {
	if x != nil {
		return x.SpinItems
	}
	return nil
}

func (x *SpinItemConfigure) GetSuccessfulProbability() float32 {
	if x != nil {
		return x.SuccessfulProbability
	}
	return 0
}

func (x *SpinItemConfigure) GetGetItemID() int32 {
	if x != nil {
		return x.GetItemID
	}
	return 0
}

func (x *SpinItemConfigure) GetSpinAchieveRewards() []*SpinAchieveConfigureItem {
	if x != nil {
		return x.SpinAchieveRewards
	}
	return nil
}

func (x *SpinItemConfigure) GetNewSpinToolType() int32 {
	if x != nil {
		return x.NewSpinToolType
	}
	return 0
}

func (x *SpinItemConfigure) GetNewSpinType() int32 {
	if x != nil {
		return x.NewSpinType
	}
	return 0
}

func (x *SpinItemConfigure) GetNewSpinPageType() int32 {
	if x != nil {
		return x.NewSpinPageType
	}
	return 0
}

type SpinItemConfigureItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int32                  `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	ItemCount     int32                  `protobuf:"varint,2,opt,name=ItemCount,proto3" json:"ItemCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinItemConfigureItem) Reset() {
	*x = SpinItemConfigureItem{}
	mi := &file_Spin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinItemConfigureItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinItemConfigureItem) ProtoMessage() {}

func (x *SpinItemConfigureItem) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinItemConfigureItem.ProtoReflect.Descriptor instead.
func (*SpinItemConfigureItem) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{6}
}

func (x *SpinItemConfigureItem) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *SpinItemConfigureItem) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type SpinAchieveConfigureItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AchieveConditionID int32                  `protobuf:"varint,1,opt,name=AchieveConditionID,proto3" json:"AchieveConditionID,omitempty"`
	RewardID           int32                  `protobuf:"varint,2,opt,name=RewardID,proto3" json:"RewardID,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SpinAchieveConfigureItem) Reset() {
	*x = SpinAchieveConfigureItem{}
	mi := &file_Spin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinAchieveConfigureItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinAchieveConfigureItem) ProtoMessage() {}

func (x *SpinAchieveConfigureItem) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinAchieveConfigureItem.ProtoReflect.Descriptor instead.
func (*SpinAchieveConfigureItem) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{7}
}

func (x *SpinAchieveConfigureItem) GetAchieveConditionID() int32 {
	if x != nil {
		return x.AchieveConditionID
	}
	return 0
}

func (x *SpinAchieveConfigureItem) GetRewardID() int32 {
	if x != nil {
		return x.RewardID
	}
	return 0
}

type SpinSpellDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []*SpinSpellConfigure  `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinSpellDatas) Reset() {
	*x = SpinSpellDatas{}
	mi := &file_Spin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinSpellDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinSpellDatas) ProtoMessage() {}

func (x *SpinSpellDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinSpellDatas.ProtoReflect.Descriptor instead.
func (*SpinSpellDatas) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{8}
}

func (x *SpinSpellDatas) GetDatas() []*SpinSpellConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type SpinSpellConfigure struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	ID             int32                          `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SpinSpellItems []*SpinSpellItemsConfigureItem `protobuf:"bytes,2,rep,name=SpinSpellItems,proto3" json:"SpinSpellItems,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpinSpellConfigure) Reset() {
	*x = SpinSpellConfigure{}
	mi := &file_Spin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinSpellConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinSpellConfigure) ProtoMessage() {}

func (x *SpinSpellConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinSpellConfigure.ProtoReflect.Descriptor instead.
func (*SpinSpellConfigure) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{9}
}

func (x *SpinSpellConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *SpinSpellConfigure) GetSpinSpellItems() []*SpinSpellItemsConfigureItem {
	if x != nil {
		return x.SpinSpellItems
	}
	return nil
}

type SpinSpellItemsConfigureItem struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Level                  int32                  `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"`
	IconID                 int32                  `protobuf:"varint,2,opt,name=IconID,proto3" json:"IconID,omitempty"`
	TextID                 int32                  `protobuf:"varint,3,opt,name=TextID,proto3" json:"TextID,omitempty"`
	NewLifeSpellEffectType int32                  `protobuf:"varint,4,opt,name=NewLifeSpellEffectType,proto3" json:"NewLifeSpellEffectType,omitempty"`
	SpellParam1            float32                `protobuf:"fixed32,5,opt,name=SpellParam1,proto3" json:"SpellParam1,omitempty"`
	SpellParam2            float32                `protobuf:"fixed32,6,opt,name=SpellParam2,proto3" json:"SpellParam2,omitempty"`
	NeedSpinLevel          int32                  `protobuf:"varint,7,opt,name=NeedSpinLevel,proto3" json:"NeedSpinLevel,omitempty"`
	NeedTime               int32                  `protobuf:"varint,8,opt,name=NeedTime,proto3" json:"NeedTime,omitempty"`
	NeedCurrencyID         int32                  `protobuf:"varint,9,opt,name=NeedCurrencyID,proto3" json:"NeedCurrencyID,omitempty"`
	NeedCurrencyCount      int32                  `protobuf:"varint,10,opt,name=NeedCurrencyCount,proto3" json:"NeedCurrencyCount,omitempty"`
	SpinNeedItem           []*SpinNeedItems       `protobuf:"bytes,11,rep,name=SpinNeedItem,proto3" json:"SpinNeedItem,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SpinSpellItemsConfigureItem) Reset() {
	*x = SpinSpellItemsConfigureItem{}
	mi := &file_Spin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinSpellItemsConfigureItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinSpellItemsConfigureItem) ProtoMessage() {}

func (x *SpinSpellItemsConfigureItem) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinSpellItemsConfigureItem.ProtoReflect.Descriptor instead.
func (*SpinSpellItemsConfigureItem) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{10}
}

func (x *SpinSpellItemsConfigureItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetIconID() int32 {
	if x != nil {
		return x.IconID
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetTextID() int32 {
	if x != nil {
		return x.TextID
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetNewLifeSpellEffectType() int32 {
	if x != nil {
		return x.NewLifeSpellEffectType
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetSpellParam1() float32 {
	if x != nil {
		return x.SpellParam1
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetSpellParam2() float32 {
	if x != nil {
		return x.SpellParam2
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetNeedSpinLevel() int32 {
	if x != nil {
		return x.NeedSpinLevel
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetNeedTime() int32 {
	if x != nil {
		return x.NeedTime
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetNeedCurrencyID() int32 {
	if x != nil {
		return x.NeedCurrencyID
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetNeedCurrencyCount() int32 {
	if x != nil {
		return x.NeedCurrencyCount
	}
	return 0
}

func (x *SpinSpellItemsConfigureItem) GetSpinNeedItem() []*SpinNeedItems {
	if x != nil {
		return x.SpinNeedItem
	}
	return nil
}

type SpinNeedItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedItemID    int32                  `protobuf:"varint,1,opt,name=NeedItemID,proto3" json:"NeedItemID,omitempty"`
	NeedItemCount int32                  `protobuf:"varint,2,opt,name=NeedItemCount,proto3" json:"NeedItemCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinNeedItems) Reset() {
	*x = SpinNeedItems{}
	mi := &file_Spin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinNeedItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinNeedItems) ProtoMessage() {}

func (x *SpinNeedItems) ProtoReflect() protoreflect.Message {
	mi := &file_Spin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinNeedItems.ProtoReflect.Descriptor instead.
func (*SpinNeedItems) Descriptor() ([]byte, []int) {
	return file_Spin_proto_rawDescGZIP(), []int{11}
}

func (x *SpinNeedItems) GetNeedItemID() int32 {
	if x != nil {
		return x.NeedItemID
	}
	return 0
}

func (x *SpinNeedItems) GetNeedItemCount() int32 {
	if x != nil {
		return x.NeedItemCount
	}
	return 0
}

var File_Spin_proto protoreflect.FileDescriptor

const file_Spin_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Spin.proto\x12\x05excel\"\xaa\x01\n" +
	"\fAllSpinDatas\x123\n" +
	"\tSpinLevel\x18\x01 \x01(\v2\x15.excel.SpinLevelDatasR\tSpinLevel\x120\n" +
	"\bSpinItem\x18\x02 \x01(\v2\x14.excel.SpinItemDatasR\bSpinItem\x123\n" +
	"\tSpinSpell\x18\x03 \x01(\v2\x15.excel.SpinSpellDatasR\tSpinSpell\"A\n" +
	"\x0eSpinLevelDatas\x12/\n" +
	"\x05Datas\x18\x01 \x03(\v2\x19.excel.SpinLevelConfigureR\x05Datas\"\xfa\x01\n" +
	"\x12SpinLevelConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12<\n" +
	"\x19UpgradeLevelByProficiency\x18\x02 \x01(\x05R\x19UpgradeLevelByProficiency\x12\x1e\n" +
	"\n" +
	"NeedItemID\x18\x03 \x01(\x05R\n" +
	"NeedItemID\x12$\n" +
	"\rNeedItemCount\x18\x04 \x01(\x05R\rNeedItemCount\x12P\n" +
	"\x10SpinLevelAchieve\x18\x05 \x03(\v2$.excel.SpinLevelAchieveConfigureItemR\x10SpinLevelAchieve\"\x97\x01\n" +
	"\x1dSpinLevelAchieveConfigureItem\x12.\n" +
	"\x12AchieveConditionID\x18\x01 \x01(\x05R\x12AchieveConditionID\x12 \n" +
	"\vProficiency\x18\x02 \x01(\x05R\vProficiency\x12$\n" +
	"\rCompleteLimit\x18\x03 \x01(\x05R\rCompleteLimit\"?\n" +
	"\rSpinItemDatas\x12.\n" +
	"\x05Datas\x18\x01 \x03(\v2\x18.excel.SpinItemConfigureR\x05Datas\"\xdc\x05\n" +
	"\x11SpinItemConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x16\n" +
	"\x06IsShow\x18\x02 \x01(\bR\x06IsShow\x12&\n" +
	"\x0eIsHandbookShow\x18\x03 \x01(\bR\x0eIsHandbookShow\x12.\n" +
	"\x12NeedShowbookItemID\x18\x04 \x01(\x05R\x12NeedShowbookItemID\x12,\n" +
	"\x11NeedFormulaItemID\x18\x05 \x01(\x05R\x11NeedFormulaItemID\x12\x1c\n" +
	"\tSpinLevel\x18\x06 \x01(\x05R\tSpinLevel\x12\x1a\n" +
	"\bNeedTime\x18\a \x01(\x05R\bNeedTime\x12 \n" +
	"\vOpeningTime\x18\b \x01(\tR\vOpeningTime\x12 \n" +
	"\vClosingTime\x18\t \x01(\tR\vClosingTime\x12\x1e\n" +
	"\n" +
	"NeedItemID\x18\n" +
	" \x01(\x05R\n" +
	"NeedItemID\x12$\n" +
	"\rNeedItemCount\x18\v \x01(\x05R\rNeedItemCount\x12:\n" +
	"\tSpinItems\x18\f \x03(\v2\x1c.excel.SpinItemConfigureItemR\tSpinItems\x124\n" +
	"\x15SuccessfulProbability\x18\r \x01(\x02R\x15SuccessfulProbability\x12\x1c\n" +
	"\tGetItemID\x18\x0e \x01(\x05R\tGetItemID\x12O\n" +
	"\x12SpinAchieveRewards\x18\x0f \x03(\v2\x1f.excel.SpinAchieveConfigureItemR\x12SpinAchieveRewards\x12(\n" +
	"\x0fNewSpinToolType\x18\x10 \x01(\x05R\x0fNewSpinToolType\x12 \n" +
	"\vNewSpinType\x18\x11 \x01(\x05R\vNewSpinType\x12(\n" +
	"\x0fNewSpinPageType\x18\x12 \x01(\x05R\x0fNewSpinPageType\"M\n" +
	"\x15SpinItemConfigureItem\x12\x16\n" +
	"\x06ItemID\x18\x01 \x01(\x05R\x06ItemID\x12\x1c\n" +
	"\tItemCount\x18\x02 \x01(\x05R\tItemCount\"f\n" +
	"\x18SpinAchieveConfigureItem\x12.\n" +
	"\x12AchieveConditionID\x18\x01 \x01(\x05R\x12AchieveConditionID\x12\x1a\n" +
	"\bRewardID\x18\x02 \x01(\x05R\bRewardID\"A\n" +
	"\x0eSpinSpellDatas\x12/\n" +
	"\x05Datas\x18\x01 \x03(\v2\x19.excel.SpinSpellConfigureR\x05Datas\"p\n" +
	"\x12SpinSpellConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12J\n" +
	"\x0eSpinSpellItems\x18\x02 \x03(\v2\".excel.SpinSpellItemsConfigureItemR\x0eSpinSpellItems\"\xb1\x03\n" +
	"\x1bSpinSpellItemsConfigureItem\x12\x14\n" +
	"\x05Level\x18\x01 \x01(\x05R\x05Level\x12\x16\n" +
	"\x06IconID\x18\x02 \x01(\x05R\x06IconID\x12\x16\n" +
	"\x06TextID\x18\x03 \x01(\x05R\x06TextID\x126\n" +
	"\x16NewLifeSpellEffectType\x18\x04 \x01(\x05R\x16NewLifeSpellEffectType\x12 \n" +
	"\vSpellParam1\x18\x05 \x01(\x02R\vSpellParam1\x12 \n" +
	"\vSpellParam2\x18\x06 \x01(\x02R\vSpellParam2\x12$\n" +
	"\rNeedSpinLevel\x18\a \x01(\x05R\rNeedSpinLevel\x12\x1a\n" +
	"\bNeedTime\x18\b \x01(\x05R\bNeedTime\x12&\n" +
	"\x0eNeedCurrencyID\x18\t \x01(\x05R\x0eNeedCurrencyID\x12,\n" +
	"\x11NeedCurrencyCount\x18\n" +
	" \x01(\x05R\x11NeedCurrencyCount\x128\n" +
	"\fSpinNeedItem\x18\v \x03(\v2\x14.excel.SpinNeedItemsR\fSpinNeedItem\"U\n" +
	"\rSpinNeedItems\x12\x1e\n" +
	"\n" +
	"NeedItemID\x18\x01 \x01(\x05R\n" +
	"NeedItemID\x12$\n" +
	"\rNeedItemCount\x18\x02 \x01(\x05R\rNeedItemCountB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_Spin_proto_rawDescOnce sync.Once
	file_Spin_proto_rawDescData []byte
)

func file_Spin_proto_rawDescGZIP() []byte {
	file_Spin_proto_rawDescOnce.Do(func() {
		file_Spin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Spin_proto_rawDesc), len(file_Spin_proto_rawDesc)))
	})
	return file_Spin_proto_rawDescData
}

var file_Spin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_Spin_proto_goTypes = []any{
	(*AllSpinDatas)(nil),                  // 0: excel.AllSpinDatas
	(*SpinLevelDatas)(nil),                // 1: excel.SpinLevelDatas
	(*SpinLevelConfigure)(nil),            // 2: excel.SpinLevelConfigure
	(*SpinLevelAchieveConfigureItem)(nil), // 3: excel.SpinLevelAchieveConfigureItem
	(*SpinItemDatas)(nil),                 // 4: excel.SpinItemDatas
	(*SpinItemConfigure)(nil),             // 5: excel.SpinItemConfigure
	(*SpinItemConfigureItem)(nil),         // 6: excel.SpinItemConfigureItem
	(*SpinAchieveConfigureItem)(nil),      // 7: excel.SpinAchieveConfigureItem
	(*SpinSpellDatas)(nil),                // 8: excel.SpinSpellDatas
	(*SpinSpellConfigure)(nil),            // 9: excel.SpinSpellConfigure
	(*SpinSpellItemsConfigureItem)(nil),   // 10: excel.SpinSpellItemsConfigureItem
	(*SpinNeedItems)(nil),                 // 11: excel.SpinNeedItems
}
var file_Spin_proto_depIdxs = []int32{
	1,  // 0: excel.AllSpinDatas.SpinLevel:type_name -> excel.SpinLevelDatas
	4,  // 1: excel.AllSpinDatas.SpinItem:type_name -> excel.SpinItemDatas
	8,  // 2: excel.AllSpinDatas.SpinSpell:type_name -> excel.SpinSpellDatas
	2,  // 3: excel.SpinLevelDatas.Datas:type_name -> excel.SpinLevelConfigure
	3,  // 4: excel.SpinLevelConfigure.SpinLevelAchieve:type_name -> excel.SpinLevelAchieveConfigureItem
	5,  // 5: excel.SpinItemDatas.Datas:type_name -> excel.SpinItemConfigure
	6,  // 6: excel.SpinItemConfigure.SpinItems:type_name -> excel.SpinItemConfigureItem
	7,  // 7: excel.SpinItemConfigure.SpinAchieveRewards:type_name -> excel.SpinAchieveConfigureItem
	9,  // 8: excel.SpinSpellDatas.Datas:type_name -> excel.SpinSpellConfigure
	10, // 9: excel.SpinSpellConfigure.SpinSpellItems:type_name -> excel.SpinSpellItemsConfigureItem
	11, // 10: excel.SpinSpellItemsConfigureItem.SpinNeedItem:type_name -> excel.SpinNeedItems
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_Spin_proto_init() }
func file_Spin_proto_init() {
	if File_Spin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Spin_proto_rawDesc), len(file_Spin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Spin_proto_goTypes,
		DependencyIndexes: file_Spin_proto_depIdxs,
		MessageInfos:      file_Spin_proto_msgTypes,
	}.Build()
	File_Spin_proto = out.File
	file_Spin_proto_goTypes = nil
	file_Spin_proto_depIdxs = nil
}
