// Source: Story.proto
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Story.proto

package excel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllStoryDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryChapter  *StoryChapterDatas     `protobuf:"bytes,1,opt,name=StoryChapter,proto3" json:"StoryChapter,omitempty"`
	Story         *StoryDatas            `protobuf:"bytes,2,opt,name=Story,proto3" json:"Story,omitempty"`
	StoryReview   *StoryReviewDatas      `protobuf:"bytes,3,opt,name=StoryReview,proto3" json:"StoryReview,omitempty"`
	ExtraChapter  *ExtraChapterDatas     `protobuf:"bytes,4,opt,name=ExtraChapter,proto3" json:"ExtraChapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllStoryDatas) Reset() {
	*x = AllStoryDatas{}
	mi := &file_Story_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllStoryDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStoryDatas) ProtoMessage() {}

func (x *AllStoryDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStoryDatas.ProtoReflect.Descriptor instead.
func (*AllStoryDatas) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{0}
}

func (x *AllStoryDatas) GetStoryChapter() *StoryChapterDatas {
	if x != nil {
		return x.StoryChapter
	}
	return nil
}

func (x *AllStoryDatas) GetStory() *StoryDatas {
	if x != nil {
		return x.Story
	}
	return nil
}

func (x *AllStoryDatas) GetStoryReview() *StoryReviewDatas {
	if x != nil {
		return x.StoryReview
	}
	return nil
}

func (x *AllStoryDatas) GetExtraChapter() *ExtraChapterDatas {
	if x != nil {
		return x.ExtraChapter
	}
	return nil
}

type StoryChapterDatas struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Datas         []*StoryChapterConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryChapterDatas) Reset() {
	*x = StoryChapterDatas{}
	mi := &file_Story_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryChapterDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryChapterDatas) ProtoMessage() {}

func (x *StoryChapterDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryChapterDatas.ProtoReflect.Descriptor instead.
func (*StoryChapterDatas) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{1}
}

func (x *StoryChapterDatas) GetDatas() []*StoryChapterConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type StoryChapterConfigure struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ID                  int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                int32                  `protobuf:"varint,2,opt,name=Name,proto3" json:"Name,omitempty"`
	IconID              int32                  `protobuf:"varint,3,opt,name=IconID,proto3" json:"IconID,omitempty"`
	PreChapterUnlock    int32                  `protobuf:"varint,4,opt,name=PreChapterUnlock,proto3" json:"PreChapterUnlock,omitempty"`
	MapCompletionUnlock []int32                `protobuf:"varint,5,rep,packed,name=MapCompletionUnlock,proto3" json:"MapCompletionUnlock,omitempty"`
	LvUnlock            int32                  `protobuf:"varint,6,opt,name=LvUnlock,proto3" json:"LvUnlock,omitempty"`
	TimeUnlock          string                 `protobuf:"bytes,7,opt,name=TimeUnlock,proto3" json:"TimeUnlock,omitempty"`
	StoryList           []int32                `protobuf:"varint,8,rep,packed,name=StoryList,proto3" json:"StoryList,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StoryChapterConfigure) Reset() {
	*x = StoryChapterConfigure{}
	mi := &file_Story_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryChapterConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryChapterConfigure) ProtoMessage() {}

func (x *StoryChapterConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryChapterConfigure.ProtoReflect.Descriptor instead.
func (*StoryChapterConfigure) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{2}
}

func (x *StoryChapterConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *StoryChapterConfigure) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *StoryChapterConfigure) GetIconID() int32 {
	if x != nil {
		return x.IconID
	}
	return 0
}

func (x *StoryChapterConfigure) GetPreChapterUnlock() int32 {
	if x != nil {
		return x.PreChapterUnlock
	}
	return 0
}

func (x *StoryChapterConfigure) GetMapCompletionUnlock() []int32 {
	if x != nil {
		return x.MapCompletionUnlock
	}
	return nil
}

func (x *StoryChapterConfigure) GetLvUnlock() int32 {
	if x != nil {
		return x.LvUnlock
	}
	return 0
}

func (x *StoryChapterConfigure) GetTimeUnlock() string {
	if x != nil {
		return x.TimeUnlock
	}
	return ""
}

func (x *StoryChapterConfigure) GetStoryList() []int32 {
	if x != nil {
		return x.StoryList
	}
	return nil
}

type StoryDatas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datas         []*StoryConfigure      `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryDatas) Reset() {
	*x = StoryDatas{}
	mi := &file_Story_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryDatas) ProtoMessage() {}

func (x *StoryDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryDatas.ProtoReflect.Descriptor instead.
func (*StoryDatas) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{3}
}

func (x *StoryDatas) GetDatas() []*StoryConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type StoryConfigure struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ID                  int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PreStoryUnlock      int32                  `protobuf:"varint,2,opt,name=PreStoryUnlock,proto3" json:"PreStoryUnlock,omitempty"`
	LvUnlock            int32                  `protobuf:"varint,3,opt,name=LvUnlock,proto3" json:"LvUnlock,omitempty"`
	MapCompletionUnlock []int32                `protobuf:"varint,4,rep,packed,name=MapCompletionUnlock,proto3" json:"MapCompletionUnlock,omitempty"`
	TimeUnlock          string                 `protobuf:"bytes,5,opt,name=TimeUnlock,proto3" json:"TimeUnlock,omitempty"`
	QuestID             int32                  `protobuf:"varint,6,opt,name=QuestID,proto3" json:"QuestID,omitempty"`
	Reward              int32                  `protobuf:"varint,7,opt,name=Reward,proto3" json:"Reward,omitempty"`
	ReviewID            int32                  `protobuf:"varint,8,opt,name=ReviewID,proto3" json:"ReviewID,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StoryConfigure) Reset() {
	*x = StoryConfigure{}
	mi := &file_Story_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryConfigure) ProtoMessage() {}

func (x *StoryConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryConfigure.ProtoReflect.Descriptor instead.
func (*StoryConfigure) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{4}
}

func (x *StoryConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *StoryConfigure) GetPreStoryUnlock() int32 {
	if x != nil {
		return x.PreStoryUnlock
	}
	return 0
}

func (x *StoryConfigure) GetLvUnlock() int32 {
	if x != nil {
		return x.LvUnlock
	}
	return 0
}

func (x *StoryConfigure) GetMapCompletionUnlock() []int32 {
	if x != nil {
		return x.MapCompletionUnlock
	}
	return nil
}

func (x *StoryConfigure) GetTimeUnlock() string {
	if x != nil {
		return x.TimeUnlock
	}
	return ""
}

func (x *StoryConfigure) GetQuestID() int32 {
	if x != nil {
		return x.QuestID
	}
	return 0
}

func (x *StoryConfigure) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *StoryConfigure) GetReviewID() int32 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

type StoryReviewDatas struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Datas         []*StoryReviewConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryReviewDatas) Reset() {
	*x = StoryReviewDatas{}
	mi := &file_Story_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryReviewDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryReviewDatas) ProtoMessage() {}

func (x *StoryReviewDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryReviewDatas.ProtoReflect.Descriptor instead.
func (*StoryReviewDatas) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{5}
}

func (x *StoryReviewDatas) GetDatas() []*StoryReviewConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type StoryReviewConfigure struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	StoryReviewSet []*StoryReviewSet      `protobuf:"bytes,2,rep,name=StoryReviewSet,proto3" json:"StoryReviewSet,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoryReviewConfigure) Reset() {
	*x = StoryReviewConfigure{}
	mi := &file_Story_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryReviewConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryReviewConfigure) ProtoMessage() {}

func (x *StoryReviewConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryReviewConfigure.ProtoReflect.Descriptor instead.
func (*StoryReviewConfigure) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{6}
}

func (x *StoryReviewConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *StoryReviewConfigure) GetStoryReviewSet() []*StoryReviewSet {
	if x != nil {
		return x.StoryReviewSet
	}
	return nil
}

type StoryReviewSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          int32                  `protobuf:"varint,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DialogID      int32                  `protobuf:"varint,2,opt,name=DialogID,proto3" json:"DialogID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryReviewSet) Reset() {
	*x = StoryReviewSet{}
	mi := &file_Story_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryReviewSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryReviewSet) ProtoMessage() {}

func (x *StoryReviewSet) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryReviewSet.ProtoReflect.Descriptor instead.
func (*StoryReviewSet) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{7}
}

func (x *StoryReviewSet) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *StoryReviewSet) GetDialogID() int32 {
	if x != nil {
		return x.DialogID
	}
	return 0
}

type ExtraChapterDatas struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Datas         []*ExtraChapterConfigure `protobuf:"bytes,1,rep,name=Datas,proto3" json:"Datas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraChapterDatas) Reset() {
	*x = ExtraChapterDatas{}
	mi := &file_Story_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraChapterDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraChapterDatas) ProtoMessage() {}

func (x *ExtraChapterDatas) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraChapterDatas.ProtoReflect.Descriptor instead.
func (*ExtraChapterDatas) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{8}
}

func (x *ExtraChapterDatas) GetDatas() []*ExtraChapterConfigure {
	if x != nil {
		return x.Datas
	}
	return nil
}

type ExtraChapterConfigure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ExtraQuest    []*ExtraQuest          `protobuf:"bytes,2,rep,name=ExtraQuest,proto3" json:"ExtraQuest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraChapterConfigure) Reset() {
	*x = ExtraChapterConfigure{}
	mi := &file_Story_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraChapterConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraChapterConfigure) ProtoMessage() {}

func (x *ExtraChapterConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraChapterConfigure.ProtoReflect.Descriptor instead.
func (*ExtraChapterConfigure) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{9}
}

func (x *ExtraChapterConfigure) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ExtraChapterConfigure) GetExtraQuest() []*ExtraQuest {
	if x != nil {
		return x.ExtraQuest
	}
	return nil
}

type ExtraQuest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextID        int32                  `protobuf:"varint,1,opt,name=TextID,proto3" json:"TextID,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	IconID        int32                  `protobuf:"varint,3,opt,name=IconID,proto3" json:"IconID,omitempty"`
	QuestUnlock   int32                  `protobuf:"varint,4,opt,name=QuestUnlock,proto3" json:"QuestUnlock,omitempty"`
	LvUnlock      int32                  `protobuf:"varint,5,opt,name=LvUnlock,proto3" json:"LvUnlock,omitempty"`
	QuestID       int32                  `protobuf:"varint,6,opt,name=QuestID,proto3" json:"QuestID,omitempty"`
	ReviewID      int32                  `protobuf:"varint,7,opt,name=ReviewID,proto3" json:"ReviewID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtraQuest) Reset() {
	*x = ExtraQuest{}
	mi := &file_Story_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtraQuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtraQuest) ProtoMessage() {}

func (x *ExtraQuest) ProtoReflect() protoreflect.Message {
	mi := &file_Story_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtraQuest.ProtoReflect.Descriptor instead.
func (*ExtraQuest) Descriptor() ([]byte, []int) {
	return file_Story_proto_rawDescGZIP(), []int{10}
}

func (x *ExtraQuest) GetTextID() int32 {
	if x != nil {
		return x.TextID
	}
	return 0
}

func (x *ExtraQuest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ExtraQuest) GetIconID() int32 {
	if x != nil {
		return x.IconID
	}
	return 0
}

func (x *ExtraQuest) GetQuestUnlock() int32 {
	if x != nil {
		return x.QuestUnlock
	}
	return 0
}

func (x *ExtraQuest) GetLvUnlock() int32 {
	if x != nil {
		return x.LvUnlock
	}
	return 0
}

func (x *ExtraQuest) GetQuestID() int32 {
	if x != nil {
		return x.QuestID
	}
	return 0
}

func (x *ExtraQuest) GetReviewID() int32 {
	if x != nil {
		return x.ReviewID
	}
	return 0
}

var File_Story_proto protoreflect.FileDescriptor

const file_Story_proto_rawDesc = "" +
	"\n" +
	"\vStory.proto\x12\x05excel\"\xef\x01\n" +
	"\rAllStoryDatas\x12<\n" +
	"\fStoryChapter\x18\x01 \x01(\v2\x18.excel.StoryChapterDatasR\fStoryChapter\x12'\n" +
	"\x05Story\x18\x02 \x01(\v2\x11.excel.StoryDatasR\x05Story\x129\n" +
	"\vStoryReview\x18\x03 \x01(\v2\x17.excel.StoryReviewDatasR\vStoryReview\x12<\n" +
	"\fExtraChapter\x18\x04 \x01(\v2\x18.excel.ExtraChapterDatasR\fExtraChapter\"G\n" +
	"\x11StoryChapterDatas\x122\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1c.excel.StoryChapterConfigureR\x05Datas\"\x8b\x02\n" +
	"\x15StoryChapterConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\x05R\x04Name\x12\x16\n" +
	"\x06IconID\x18\x03 \x01(\x05R\x06IconID\x12*\n" +
	"\x10PreChapterUnlock\x18\x04 \x01(\x05R\x10PreChapterUnlock\x120\n" +
	"\x13MapCompletionUnlock\x18\x05 \x03(\x05R\x13MapCompletionUnlock\x12\x1a\n" +
	"\bLvUnlock\x18\x06 \x01(\x05R\bLvUnlock\x12\x1e\n" +
	"\n" +
	"TimeUnlock\x18\a \x01(\tR\n" +
	"TimeUnlock\x12\x1c\n" +
	"\tStoryList\x18\b \x03(\x05R\tStoryList\"9\n" +
	"\n" +
	"StoryDatas\x12+\n" +
	"\x05Datas\x18\x01 \x03(\v2\x15.excel.StoryConfigureR\x05Datas\"\x84\x02\n" +
	"\x0eStoryConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12&\n" +
	"\x0ePreStoryUnlock\x18\x02 \x01(\x05R\x0ePreStoryUnlock\x12\x1a\n" +
	"\bLvUnlock\x18\x03 \x01(\x05R\bLvUnlock\x120\n" +
	"\x13MapCompletionUnlock\x18\x04 \x03(\x05R\x13MapCompletionUnlock\x12\x1e\n" +
	"\n" +
	"TimeUnlock\x18\x05 \x01(\tR\n" +
	"TimeUnlock\x12\x18\n" +
	"\aQuestID\x18\x06 \x01(\x05R\aQuestID\x12\x16\n" +
	"\x06Reward\x18\a \x01(\x05R\x06Reward\x12\x1a\n" +
	"\bReviewID\x18\b \x01(\x05R\bReviewID\"E\n" +
	"\x10StoryReviewDatas\x121\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1b.excel.StoryReviewConfigureR\x05Datas\"e\n" +
	"\x14StoryReviewConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12=\n" +
	"\x0eStoryReviewSet\x18\x02 \x03(\v2\x15.excel.StoryReviewSetR\x0eStoryReviewSet\"@\n" +
	"\x0eStoryReviewSet\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\x05R\x04Name\x12\x1a\n" +
	"\bDialogID\x18\x02 \x01(\x05R\bDialogID\"G\n" +
	"\x11ExtraChapterDatas\x122\n" +
	"\x05Datas\x18\x01 \x03(\v2\x1c.excel.ExtraChapterConfigureR\x05Datas\"Z\n" +
	"\x15ExtraChapterConfigure\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x121\n" +
	"\n" +
	"ExtraQuest\x18\x02 \x03(\v2\x11.excel.ExtraQuestR\n" +
	"ExtraQuest\"\xc6\x01\n" +
	"\n" +
	"ExtraQuest\x12\x16\n" +
	"\x06TextID\x18\x01 \x01(\x05R\x06TextID\x12\x14\n" +
	"\x05Index\x18\x02 \x01(\x05R\x05Index\x12\x16\n" +
	"\x06IconID\x18\x03 \x01(\x05R\x06IconID\x12 \n" +
	"\vQuestUnlock\x18\x04 \x01(\x05R\vQuestUnlock\x12\x1a\n" +
	"\bLvUnlock\x18\x05 \x01(\x05R\bLvUnlock\x12\x18\n" +
	"\aQuestID\x18\x06 \x01(\x05R\aQuestID\x12\x1a\n" +
	"\bReviewID\x18\a \x01(\x05R\bReviewIDB\n" +
	"Z\b./;excelb\x06proto3"

var (
	file_Story_proto_rawDescOnce sync.Once
	file_Story_proto_rawDescData []byte
)

func file_Story_proto_rawDescGZIP() []byte {
	file_Story_proto_rawDescOnce.Do(func() {
		file_Story_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Story_proto_rawDesc), len(file_Story_proto_rawDesc)))
	})
	return file_Story_proto_rawDescData
}

var file_Story_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Story_proto_goTypes = []any{
	(*AllStoryDatas)(nil),         // 0: excel.AllStoryDatas
	(*StoryChapterDatas)(nil),     // 1: excel.StoryChapterDatas
	(*StoryChapterConfigure)(nil), // 2: excel.StoryChapterConfigure
	(*StoryDatas)(nil),            // 3: excel.StoryDatas
	(*StoryConfigure)(nil),        // 4: excel.StoryConfigure
	(*StoryReviewDatas)(nil),      // 5: excel.StoryReviewDatas
	(*StoryReviewConfigure)(nil),  // 6: excel.StoryReviewConfigure
	(*StoryReviewSet)(nil),        // 7: excel.StoryReviewSet
	(*ExtraChapterDatas)(nil),     // 8: excel.ExtraChapterDatas
	(*ExtraChapterConfigure)(nil), // 9: excel.ExtraChapterConfigure
	(*ExtraQuest)(nil),            // 10: excel.ExtraQuest
}
var file_Story_proto_depIdxs = []int32{
	1,  // 0: excel.AllStoryDatas.StoryChapter:type_name -> excel.StoryChapterDatas
	3,  // 1: excel.AllStoryDatas.Story:type_name -> excel.StoryDatas
	5,  // 2: excel.AllStoryDatas.StoryReview:type_name -> excel.StoryReviewDatas
	8,  // 3: excel.AllStoryDatas.ExtraChapter:type_name -> excel.ExtraChapterDatas
	2,  // 4: excel.StoryChapterDatas.Datas:type_name -> excel.StoryChapterConfigure
	4,  // 5: excel.StoryDatas.Datas:type_name -> excel.StoryConfigure
	6,  // 6: excel.StoryReviewDatas.Datas:type_name -> excel.StoryReviewConfigure
	7,  // 7: excel.StoryReviewConfigure.StoryReviewSet:type_name -> excel.StoryReviewSet
	9,  // 8: excel.ExtraChapterDatas.Datas:type_name -> excel.ExtraChapterConfigure
	10, // 9: excel.ExtraChapterConfigure.ExtraQuest:type_name -> excel.ExtraQuest
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_Story_proto_init() }
func file_Story_proto_init() {
	if File_Story_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Story_proto_rawDesc), len(file_Story_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Story_proto_goTypes,
		DependencyIndexes: file_Story_proto_depIdxs,
		MessageInfos:      file_Story_proto_msgTypes,
	}.Build()
	File_Story_proto = out.File
	file_Story_proto_goTypes = nil
	file_Story_proto_depIdxs = nil
}
