// Extracted message AbilityBadgePageInfo
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: AbilityBadgePageInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbilityBadgePageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	IsReward      bool                   `protobuf:"varint,2,opt,name=is_reward,json=isReward,proto3" json:"is_reward,omitempty"`
	ActiveBoxIds  []uint32               `protobuf:"varint,3,rep,packed,name=active_box_ids,json=activeBoxIds,proto3" json:"active_box_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityBadgePageInfo) Reset() {
	*x = AbilityBadgePageInfo{}
	mi := &file_AbilityBadgePageInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityBadgePageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityBadgePageInfo) ProtoMessage() {}

func (x *AbilityBadgePageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_AbilityBadgePageInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityBadgePageInfo.ProtoReflect.Descriptor instead.
func (*AbilityBadgePageInfo) Descriptor() ([]byte, []int) {
	return file_AbilityBadgePageInfo_proto_rawDescGZIP(), []int{0}
}

func (x *AbilityBadgePageInfo) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AbilityBadgePageInfo) GetIsReward() bool {
	if x != nil {
		return x.IsReward
	}
	return false
}

func (x *AbilityBadgePageInfo) GetActiveBoxIds() []uint32 {
	if x != nil {
		return x.ActiveBoxIds
	}
	return nil
}

var File_AbilityBadgePageInfo_proto protoreflect.FileDescriptor

const file_AbilityBadgePageInfo_proto_rawDesc = "" +
	"\n" +
	"\x1aAbilityBadgePageInfo.proto\x12\x05proto\"m\n" +
	"\x14AbilityBadgePageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tis_reward\x18\x02 \x01(\bR\bisReward\x12$\n" +
	"\x0eactive_box_ids\x18\x03 \x03(\rR\factiveBoxIdsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_AbilityBadgePageInfo_proto_rawDescOnce sync.Once
	file_AbilityBadgePageInfo_proto_rawDescData []byte
)

func file_AbilityBadgePageInfo_proto_rawDescGZIP() []byte {
	file_AbilityBadgePageInfo_proto_rawDescOnce.Do(func() {
		file_AbilityBadgePageInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AbilityBadgePageInfo_proto_rawDesc), len(file_AbilityBadgePageInfo_proto_rawDesc)))
	})
	return file_AbilityBadgePageInfo_proto_rawDescData
}

var file_AbilityBadgePageInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AbilityBadgePageInfo_proto_goTypes = []any{
	(*AbilityBadgePageInfo)(nil), // 0: proto.AbilityBadgePageInfo
}
var file_AbilityBadgePageInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AbilityBadgePageInfo_proto_init() }
func file_AbilityBadgePageInfo_proto_init() {
	if File_AbilityBadgePageInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AbilityBadgePageInfo_proto_rawDesc), len(file_AbilityBadgePageInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AbilityBadgePageInfo_proto_goTypes,
		DependencyIndexes: file_AbilityBadgePageInfo_proto_depIdxs,
		MessageInfos:      file_AbilityBadgePageInfo_proto_msgTypes,
	}.Build()
	File_AbilityBadgePageInfo_proto = out.File
	file_AbilityBadgePageInfo_proto_goTypes = nil
	file_AbilityBadgePageInfo_proto_depIdxs = nil
}
