// Extracted message AbyssDungeonInfo
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: AbyssDungeonInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbyssDungeonInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DungeonId     uint32                 `protobuf:"varint,1,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`
	AbyssTeams    []*Team                `protobuf:"bytes,2,rep,name=abyss_teams,json=abyssTeams,proto3" json:"abyss_teams,omitempty"`
	FinishTime    uint32                 `protobuf:"varint,3,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	IsChallenge   bool                   `protobuf:"varint,4,opt,name=is_challenge,json=isChallenge,proto3" json:"is_challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbyssDungeonInfo) Reset() {
	*x = AbyssDungeonInfo{}
	mi := &file_AbyssDungeonInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbyssDungeonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbyssDungeonInfo) ProtoMessage() {}

func (x *AbyssDungeonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_AbyssDungeonInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbyssDungeonInfo.ProtoReflect.Descriptor instead.
func (*AbyssDungeonInfo) Descriptor() ([]byte, []int) {
	return file_AbyssDungeonInfo_proto_rawDescGZIP(), []int{0}
}

func (x *AbyssDungeonInfo) GetDungeonId() uint32 {
	if x != nil {
		return x.DungeonId
	}
	return 0
}

func (x *AbyssDungeonInfo) GetAbyssTeams() []*Team {
	if x != nil {
		return x.AbyssTeams
	}
	return nil
}

func (x *AbyssDungeonInfo) GetFinishTime() uint32 {
	if x != nil {
		return x.FinishTime
	}
	return 0
}

func (x *AbyssDungeonInfo) GetIsChallenge() bool {
	if x != nil {
		return x.IsChallenge
	}
	return false
}

var File_AbyssDungeonInfo_proto protoreflect.FileDescriptor

const file_AbyssDungeonInfo_proto_rawDesc = "" +
	"\n" +
	"\x16AbyssDungeonInfo.proto\x12\x05proto\x1a\n" +
	"Team.proto\"\xa3\x01\n" +
	"\x10AbyssDungeonInfo\x12\x1d\n" +
	"\n" +
	"dungeon_id\x18\x01 \x01(\rR\tdungeonId\x12,\n" +
	"\vabyss_teams\x18\x02 \x03(\v2\v.proto.TeamR\n" +
	"abyssTeams\x12\x1f\n" +
	"\vfinish_time\x18\x03 \x01(\rR\n" +
	"finishTime\x12!\n" +
	"\fis_challenge\x18\x04 \x01(\bR\visChallengeB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_AbyssDungeonInfo_proto_rawDescOnce sync.Once
	file_AbyssDungeonInfo_proto_rawDescData []byte
)

func file_AbyssDungeonInfo_proto_rawDescGZIP() []byte {
	file_AbyssDungeonInfo_proto_rawDescOnce.Do(func() {
		file_AbyssDungeonInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AbyssDungeonInfo_proto_rawDesc), len(file_AbyssDungeonInfo_proto_rawDesc)))
	})
	return file_AbyssDungeonInfo_proto_rawDescData
}

var file_AbyssDungeonInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AbyssDungeonInfo_proto_goTypes = []any{
	(*AbyssDungeonInfo)(nil), // 0: proto.AbyssDungeonInfo
	(*Team)(nil),             // 1: proto.Team
}
var file_AbyssDungeonInfo_proto_depIdxs = []int32{
	1, // 0: proto.AbyssDungeonInfo.abyss_teams:type_name -> proto.Team
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AbyssDungeonInfo_proto_init() }
func file_AbyssDungeonInfo_proto_init() {
	if File_AbyssDungeonInfo_proto != nil {
		return
	}
	file_Team_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AbyssDungeonInfo_proto_rawDesc), len(file_AbyssDungeonInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AbyssDungeonInfo_proto_goTypes,
		DependencyIndexes: file_AbyssDungeonInfo_proto_depIdxs,
		MessageInfos:      file_AbyssDungeonInfo_proto_msgTypes,
	}.Build()
	File_AbyssDungeonInfo_proto = out.File
	file_AbyssDungeonInfo_proto_goTypes = nil
	file_AbyssDungeonInfo_proto_depIdxs = nil
}
