// Extracted enum AccountType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: AccountType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_AccountType_None          AccountType = 0
	AccountType_AccountType_Tourist       AccountType = 1
	AccountType_AccountType_Gava          AccountType = 3
	AccountType_AccountType_Xiaomi        AccountType = 19
	AccountType_AccountType_Vivo          AccountType = 65
	AccountType_AccountType_Oppo          AccountType = 139
	AccountType_AccountType_Huawei        AccountType = 39
	AccountType_AccountType_Mumu          AccountType = 311
	AccountType_AccountType_Leidian       AccountType = 309
	AccountType_AccountType__9Game        AccountType = 207
	AccountType_AccountType_Honor         AccountType = 315
	AccountType_AccountType__4399         AccountType = 45
	AccountType_AccountType_Lenovo        AccountType = 29
	AccountType_AccountType_Yyb           AccountType = 95
	AccountType_AccountType__223          AccountType = 321
	AccountType_AccountType_Blibli        AccountType = 114
	AccountType_AccountType_Mac           AccountType = 7777
	AccountType_AccountType_Ios           AccountType = 8888
	AccountType_AccountType_Windows       AccountType = 9999
	AccountType_AccountType_Android       AccountType = 28814
	AccountType_AccountType_WeGame        AccountType = 30000
	AccountType_AccountType_BliBliPc      AccountType = 30114
	AccountType_AccountType_GlobalIos     AccountType = 18888
	AccountType_AccountType_GlobalWindows AccountType = 19999
	AccountType_AccountType_GlobalGoogle  AccountType = 17777
	AccountType_AccountType_GlobalSamsung AccountType = 17778
	AccountType_AccountType_GlobalSteam   AccountType = 16666
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0:     "AccountType_None",
		1:     "AccountType_Tourist",
		3:     "AccountType_Gava",
		19:    "AccountType_Xiaomi",
		65:    "AccountType_Vivo",
		139:   "AccountType_Oppo",
		39:    "AccountType_Huawei",
		311:   "AccountType_Mumu",
		309:   "AccountType_Leidian",
		207:   "AccountType__9Game",
		315:   "AccountType_Honor",
		45:    "AccountType__4399",
		29:    "AccountType_Lenovo",
		95:    "AccountType_Yyb",
		321:   "AccountType__223",
		114:   "AccountType_Blibli",
		7777:  "AccountType_Mac",
		8888:  "AccountType_Ios",
		9999:  "AccountType_Windows",
		28814: "AccountType_Android",
		30000: "AccountType_WeGame",
		30114: "AccountType_BliBliPc",
		18888: "AccountType_GlobalIos",
		19999: "AccountType_GlobalWindows",
		17777: "AccountType_GlobalGoogle",
		17778: "AccountType_GlobalSamsung",
		16666: "AccountType_GlobalSteam",
	}
	AccountType_value = map[string]int32{
		"AccountType_None":          0,
		"AccountType_Tourist":       1,
		"AccountType_Gava":          3,
		"AccountType_Xiaomi":        19,
		"AccountType_Vivo":          65,
		"AccountType_Oppo":          139,
		"AccountType_Huawei":        39,
		"AccountType_Mumu":          311,
		"AccountType_Leidian":       309,
		"AccountType__9Game":        207,
		"AccountType_Honor":         315,
		"AccountType__4399":         45,
		"AccountType_Lenovo":        29,
		"AccountType_Yyb":           95,
		"AccountType__223":          321,
		"AccountType_Blibli":        114,
		"AccountType_Mac":           7777,
		"AccountType_Ios":           8888,
		"AccountType_Windows":       9999,
		"AccountType_Android":       28814,
		"AccountType_WeGame":        30000,
		"AccountType_BliBliPc":      30114,
		"AccountType_GlobalIos":     18888,
		"AccountType_GlobalWindows": 19999,
		"AccountType_GlobalGoogle":  17777,
		"AccountType_GlobalSamsung": 17778,
		"AccountType_GlobalSteam":   16666,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_AccountType_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_AccountType_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_AccountType_proto_rawDescGZIP(), []int{0}
}

var File_AccountType_proto protoreflect.FileDescriptor

const file_AccountType_proto_rawDesc = "" +
	"\n" +
	"\x11AccountType.proto\x12\x05proto*\xb9\x05\n" +
	"\vAccountType\x12\x14\n" +
	"\x10AccountType_None\x10\x00\x12\x17\n" +
	"\x13AccountType_Tourist\x10\x01\x12\x14\n" +
	"\x10AccountType_Gava\x10\x03\x12\x16\n" +
	"\x12AccountType_Xiaomi\x10\x13\x12\x14\n" +
	"\x10AccountType_Vivo\x10A\x12\x15\n" +
	"\x10AccountType_Oppo\x10\x8b\x01\x12\x16\n" +
	"\x12AccountType_Huawei\x10'\x12\x15\n" +
	"\x10AccountType_Mumu\x10\xb7\x02\x12\x18\n" +
	"\x13AccountType_Leidian\x10\xb5\x02\x12\x17\n" +
	"\x12AccountType__9Game\x10\xcf\x01\x12\x16\n" +
	"\x11AccountType_Honor\x10\xbb\x02\x12\x15\n" +
	"\x11AccountType__4399\x10-\x12\x16\n" +
	"\x12AccountType_Lenovo\x10\x1d\x12\x13\n" +
	"\x0fAccountType_Yyb\x10_\x12\x15\n" +
	"\x10AccountType__223\x10\xc1\x02\x12\x16\n" +
	"\x12AccountType_Blibli\x10r\x12\x14\n" +
	"\x0fAccountType_Mac\x10\xe1<\x12\x14\n" +
	"\x0fAccountType_Ios\x10\xb8E\x12\x18\n" +
	"\x13AccountType_Windows\x10\x8fN\x12\x19\n" +
	"\x13AccountType_Android\x10\x8e\xe1\x01\x12\x18\n" +
	"\x12AccountType_WeGame\x10\xb0\xea\x01\x12\x1a\n" +
	"\x14AccountType_BliBliPc\x10\xa2\xeb\x01\x12\x1b\n" +
	"\x15AccountType_GlobalIos\x10ȓ\x01\x12\x1f\n" +
	"\x19AccountType_GlobalWindows\x10\x9f\x9c\x01\x12\x1e\n" +
	"\x18AccountType_GlobalGoogle\x10\xf1\x8a\x01\x12\x1f\n" +
	"\x19AccountType_GlobalSamsung\x10\xf2\x8a\x01\x12\x1d\n" +
	"\x17AccountType_GlobalSteam\x10\x9a\x82\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_AccountType_proto_rawDescOnce sync.Once
	file_AccountType_proto_rawDescData []byte
)

func file_AccountType_proto_rawDescGZIP() []byte {
	file_AccountType_proto_rawDescOnce.Do(func() {
		file_AccountType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AccountType_proto_rawDesc), len(file_AccountType_proto_rawDesc)))
	})
	return file_AccountType_proto_rawDescData
}

var file_AccountType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AccountType_proto_goTypes = []any{
	(AccountType)(0), // 0: proto.AccountType
}
var file_AccountType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AccountType_proto_init() }
func file_AccountType_proto_init() {
	if File_AccountType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AccountType_proto_rawDesc), len(file_AccountType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccountType_proto_goTypes,
		DependencyIndexes: file_AccountType_proto_depIdxs,
		EnumInfos:         file_AccountType_proto_enumTypes,
	}.Build()
	File_AccountType_proto = out.File
	file_AccountType_proto_goTypes = nil
	file_AccountType_proto_depIdxs = nil
}
