// Extracted message ActivityRegularAchieve
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ActivityRegularAchieve.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityRegularAchieve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AchieveId     uint32                 `protobuf:"varint,1,opt,name=achieve_id,json=achieveId,proto3" json:"achieve_id,omitempty"`
	IsReward      bool                   `protobuf:"varint,2,opt,name=is_reward,json=isReward,proto3" json:"is_reward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityRegularAchieve) Reset() {
	*x = ActivityRegularAchieve{}
	mi := &file_ActivityRegularAchieve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityRegularAchieve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRegularAchieve) ProtoMessage() {}

func (x *ActivityRegularAchieve) ProtoReflect() protoreflect.Message {
	mi := &file_ActivityRegularAchieve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRegularAchieve.ProtoReflect.Descriptor instead.
func (*ActivityRegularAchieve) Descriptor() ([]byte, []int) {
	return file_ActivityRegularAchieve_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityRegularAchieve) GetAchieveId() uint32 {
	if x != nil {
		return x.AchieveId
	}
	return 0
}

func (x *ActivityRegularAchieve) GetIsReward() bool {
	if x != nil {
		return x.IsReward
	}
	return false
}

var File_ActivityRegularAchieve_proto protoreflect.FileDescriptor

const file_ActivityRegularAchieve_proto_rawDesc = "" +
	"\n" +
	"\x1cActivityRegularAchieve.proto\x12\x05proto\"T\n" +
	"\x16ActivityRegularAchieve\x12\x1d\n" +
	"\n" +
	"achieve_id\x18\x01 \x01(\rR\tachieveId\x12\x1b\n" +
	"\tis_reward\x18\x02 \x01(\bR\bisRewardB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ActivityRegularAchieve_proto_rawDescOnce sync.Once
	file_ActivityRegularAchieve_proto_rawDescData []byte
)

func file_ActivityRegularAchieve_proto_rawDescGZIP() []byte {
	file_ActivityRegularAchieve_proto_rawDescOnce.Do(func() {
		file_ActivityRegularAchieve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ActivityRegularAchieve_proto_rawDesc), len(file_ActivityRegularAchieve_proto_rawDesc)))
	})
	return file_ActivityRegularAchieve_proto_rawDescData
}

var file_ActivityRegularAchieve_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ActivityRegularAchieve_proto_goTypes = []any{
	(*ActivityRegularAchieve)(nil), // 0: proto.ActivityRegularAchieve
}
var file_ActivityRegularAchieve_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ActivityRegularAchieve_proto_init() }
func file_ActivityRegularAchieve_proto_init() {
	if File_ActivityRegularAchieve_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ActivityRegularAchieve_proto_rawDesc), len(file_ActivityRegularAchieve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ActivityRegularAchieve_proto_goTypes,
		DependencyIndexes: file_ActivityRegularAchieve_proto_depIdxs,
		MessageInfos:      file_ActivityRegularAchieve_proto_msgTypes,
	}.Build()
	File_ActivityRegularAchieve_proto = out.File
	file_ActivityRegularAchieve_proto_goTypes = nil
	file_ActivityRegularAchieve_proto_depIdxs = nil
}
