// Extracted message ActivityInviteRewardClaimRsp
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ActivityInviteRewardClaimRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityInviteRewardClaimRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	ActivityId    uint32                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ConditionId   uint32                 `protobuf:"varint,3,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	Rewards       []*ItemDetail          `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityInviteRewardClaimRsp) Reset() {
	*x = ActivityInviteRewardClaimRsp{}
	mi := &file_ActivityInviteRewardClaimRsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInviteRewardClaimRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInviteRewardClaimRsp) ProtoMessage() {}

func (x *ActivityInviteRewardClaimRsp) ProtoReflect() protoreflect.Message {
	mi := &file_ActivityInviteRewardClaimRsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInviteRewardClaimRsp.ProtoReflect.Descriptor instead.
func (*ActivityInviteRewardClaimRsp) Descriptor() ([]byte, []int) {
	return file_ActivityInviteRewardClaimRsp_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityInviteRewardClaimRsp) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *ActivityInviteRewardClaimRsp) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityInviteRewardClaimRsp) GetConditionId() uint32 {
	if x != nil {
		return x.ConditionId
	}
	return 0
}

func (x *ActivityInviteRewardClaimRsp) GetRewards() []*ItemDetail {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_ActivityInviteRewardClaimRsp_proto protoreflect.FileDescriptor

const file_ActivityInviteRewardClaimRsp_proto_rawDesc = "" +
	"\n" +
	"\"ActivityInviteRewardClaimRsp.proto\x12\x05proto\x1a\x10ItemDetail.proto\x1a\x10StatusCode.proto\"\xba\x01\n" +
	"\x1cActivityInviteRewardClaimRsp\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\rR\n" +
	"activityId\x12!\n" +
	"\fcondition_id\x18\x03 \x01(\rR\vconditionId\x12+\n" +
	"\arewards\x18\x04 \x03(\v2\x11.proto.ItemDetailR\arewardsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ActivityInviteRewardClaimRsp_proto_rawDescOnce sync.Once
	file_ActivityInviteRewardClaimRsp_proto_rawDescData []byte
)

func file_ActivityInviteRewardClaimRsp_proto_rawDescGZIP() []byte {
	file_ActivityInviteRewardClaimRsp_proto_rawDescOnce.Do(func() {
		file_ActivityInviteRewardClaimRsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ActivityInviteRewardClaimRsp_proto_rawDesc), len(file_ActivityInviteRewardClaimRsp_proto_rawDesc)))
	})
	return file_ActivityInviteRewardClaimRsp_proto_rawDescData
}

var file_ActivityInviteRewardClaimRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ActivityInviteRewardClaimRsp_proto_goTypes = []any{
	(*ActivityInviteRewardClaimRsp)(nil), // 0: proto.ActivityInviteRewardClaimRsp
	(StatusCode)(0),                      // 1: proto.StatusCode
	(*ItemDetail)(nil),                   // 2: proto.ItemDetail
}
var file_ActivityInviteRewardClaimRsp_proto_depIdxs = []int32{
	1, // 0: proto.ActivityInviteRewardClaimRsp.status:type_name -> proto.StatusCode
	2, // 1: proto.ActivityInviteRewardClaimRsp.rewards:type_name -> proto.ItemDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ActivityInviteRewardClaimRsp_proto_init() }
func file_ActivityInviteRewardClaimRsp_proto_init() {
	if File_ActivityInviteRewardClaimRsp_proto != nil {
		return
	}
	file_ItemDetail_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ActivityInviteRewardClaimRsp_proto_rawDesc), len(file_ActivityInviteRewardClaimRsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ActivityInviteRewardClaimRsp_proto_goTypes,
		DependencyIndexes: file_ActivityInviteRewardClaimRsp_proto_depIdxs,
		MessageInfos:      file_ActivityInviteRewardClaimRsp_proto_msgTypes,
	}.Build()
	File_ActivityInviteRewardClaimRsp_proto = out.File
	file_ActivityInviteRewardClaimRsp_proto_goTypes = nil
	file_ActivityInviteRewardClaimRsp_proto_depIdxs = nil
}
