// Extracted message BlessTreeUnlockRsp
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: BlessTreeUnlockRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlessTreeUnlockRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	DefId         uint32                 `protobuf:"varint,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"`
	TreeId        uint32                 `protobuf:"varint,3,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Rewards       []*ItemDetail          `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlessTreeUnlockRsp) Reset() {
	*x = BlessTreeUnlockRsp{}
	mi := &file_BlessTreeUnlockRsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlessTreeUnlockRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlessTreeUnlockRsp) ProtoMessage() {}

func (x *BlessTreeUnlockRsp) ProtoReflect() protoreflect.Message {
	mi := &file_BlessTreeUnlockRsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlessTreeUnlockRsp.ProtoReflect.Descriptor instead.
func (*BlessTreeUnlockRsp) Descriptor() ([]byte, []int) {
	return file_BlessTreeUnlockRsp_proto_rawDescGZIP(), []int{0}
}

func (x *BlessTreeUnlockRsp) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *BlessTreeUnlockRsp) GetDefId() uint32 {
	if x != nil {
		return x.DefId
	}
	return 0
}

func (x *BlessTreeUnlockRsp) GetTreeId() uint32 {
	if x != nil {
		return x.TreeId
	}
	return 0
}

func (x *BlessTreeUnlockRsp) GetRewards() []*ItemDetail {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_BlessTreeUnlockRsp_proto protoreflect.FileDescriptor

const file_BlessTreeUnlockRsp_proto_rawDesc = "" +
	"\n" +
	"\x18BlessTreeUnlockRsp.proto\x12\x05proto\x1a\x10ItemDetail.proto\x1a\x10StatusCode.proto\"\x9c\x01\n" +
	"\x12BlessTreeUnlockRsp\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12\x15\n" +
	"\x06def_id\x18\x02 \x01(\rR\x05defId\x12\x17\n" +
	"\atree_id\x18\x03 \x01(\rR\x06treeId\x12+\n" +
	"\arewards\x18\x04 \x03(\v2\x11.proto.ItemDetailR\arewardsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_BlessTreeUnlockRsp_proto_rawDescOnce sync.Once
	file_BlessTreeUnlockRsp_proto_rawDescData []byte
)

func file_BlessTreeUnlockRsp_proto_rawDescGZIP() []byte {
	file_BlessTreeUnlockRsp_proto_rawDescOnce.Do(func() {
		file_BlessTreeUnlockRsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BlessTreeUnlockRsp_proto_rawDesc), len(file_BlessTreeUnlockRsp_proto_rawDesc)))
	})
	return file_BlessTreeUnlockRsp_proto_rawDescData
}

var file_BlessTreeUnlockRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_BlessTreeUnlockRsp_proto_goTypes = []any{
	(*BlessTreeUnlockRsp)(nil), // 0: proto.BlessTreeUnlockRsp
	(StatusCode)(0),            // 1: proto.StatusCode
	(*ItemDetail)(nil),         // 2: proto.ItemDetail
}
var file_BlessTreeUnlockRsp_proto_depIdxs = []int32{
	1, // 0: proto.BlessTreeUnlockRsp.status:type_name -> proto.StatusCode
	2, // 1: proto.BlessTreeUnlockRsp.rewards:type_name -> proto.ItemDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_BlessTreeUnlockRsp_proto_init() }
func file_BlessTreeUnlockRsp_proto_init() {
	if File_BlessTreeUnlockRsp_proto != nil {
		return
	}
	file_ItemDetail_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BlessTreeUnlockRsp_proto_rawDesc), len(file_BlessTreeUnlockRsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BlessTreeUnlockRsp_proto_goTypes,
		DependencyIndexes: file_BlessTreeUnlockRsp_proto_depIdxs,
		MessageInfos:      file_BlessTreeUnlockRsp_proto_msgTypes,
	}.Build()
	File_BlessTreeUnlockRsp_proto = out.File
	file_BlessTreeUnlockRsp_proto_goTypes = nil
	file_BlessTreeUnlockRsp_proto_depIdxs = nil
}
