// Extracted message BossRushFriendDetailReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: BossRushFriendDetailReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BossRushFriendDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossRushFriendDetailReq) Reset() {
	*x = BossRushFriendDetailReq{}
	mi := &file_BossRushFriendDetailReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossRushFriendDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRushFriendDetailReq) ProtoMessage() {}

func (x *BossRushFriendDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_BossRushFriendDetailReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRushFriendDetailReq.ProtoReflect.Descriptor instead.
func (*BossRushFriendDetailReq) Descriptor() ([]byte, []int) {
	return file_BossRushFriendDetailReq_proto_rawDescGZIP(), []int{0}
}

func (x *BossRushFriendDetailReq) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_BossRushFriendDetailReq_proto protoreflect.FileDescriptor

const file_BossRushFriendDetailReq_proto_rawDesc = "" +
	"\n" +
	"\x1dBossRushFriendDetailReq.proto\x12\x05proto\"6\n" +
	"\x17BossRushFriendDetailReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerIdB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_BossRushFriendDetailReq_proto_rawDescOnce sync.Once
	file_BossRushFriendDetailReq_proto_rawDescData []byte
)

func file_BossRushFriendDetailReq_proto_rawDescGZIP() []byte {
	file_BossRushFriendDetailReq_proto_rawDescOnce.Do(func() {
		file_BossRushFriendDetailReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BossRushFriendDetailReq_proto_rawDesc), len(file_BossRushFriendDetailReq_proto_rawDesc)))
	})
	return file_BossRushFriendDetailReq_proto_rawDescData
}

var file_BossRushFriendDetailReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_BossRushFriendDetailReq_proto_goTypes = []any{
	(*BossRushFriendDetailReq)(nil), // 0: proto.BossRushFriendDetailReq
}
var file_BossRushFriendDetailReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_BossRushFriendDetailReq_proto_init() }
func file_BossRushFriendDetailReq_proto_init() {
	if File_BossRushFriendDetailReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BossRushFriendDetailReq_proto_rawDesc), len(file_BossRushFriendDetailReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BossRushFriendDetailReq_proto_goTypes,
		DependencyIndexes: file_BossRushFriendDetailReq_proto_depIdxs,
		MessageInfos:      file_BossRushFriendDetailReq_proto_msgTypes,
	}.Build()
	File_BossRushFriendDetailReq_proto = out.File
	file_BossRushFriendDetailReq_proto_goTypes = nil
	file_BossRushFriendDetailReq_proto_depIdxs = nil
}
