// Extracted message BossRushQuestRewardRsp
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: BossRushQuestRewardRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BossRushQuestRewardRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	SeasonId      uint32                 `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	AchieveId     uint32                 `protobuf:"varint,3,opt,name=achieve_id,json=achieveId,proto3" json:"achieve_id,omitempty"`
	Rewards       []*ItemDetail          `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossRushQuestRewardRsp) Reset() {
	*x = BossRushQuestRewardRsp{}
	mi := &file_BossRushQuestRewardRsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossRushQuestRewardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossRushQuestRewardRsp) ProtoMessage() {}

func (x *BossRushQuestRewardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_BossRushQuestRewardRsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossRushQuestRewardRsp.ProtoReflect.Descriptor instead.
func (*BossRushQuestRewardRsp) Descriptor() ([]byte, []int) {
	return file_BossRushQuestRewardRsp_proto_rawDescGZIP(), []int{0}
}

func (x *BossRushQuestRewardRsp) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *BossRushQuestRewardRsp) GetSeasonId() uint32 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

func (x *BossRushQuestRewardRsp) GetAchieveId() uint32 {
	if x != nil {
		return x.AchieveId
	}
	return 0
}

func (x *BossRushQuestRewardRsp) GetRewards() []*ItemDetail {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_BossRushQuestRewardRsp_proto protoreflect.FileDescriptor

const file_BossRushQuestRewardRsp_proto_rawDesc = "" +
	"\n" +
	"\x1cBossRushQuestRewardRsp.proto\x12\x05proto\x1a\x10ItemDetail.proto\x1a\x10StatusCode.proto\"\xac\x01\n" +
	"\x16BossRushQuestRewardRsp\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12\x1b\n" +
	"\tseason_id\x18\x02 \x01(\rR\bseasonId\x12\x1d\n" +
	"\n" +
	"achieve_id\x18\x03 \x01(\rR\tachieveId\x12+\n" +
	"\arewards\x18\x04 \x03(\v2\x11.proto.ItemDetailR\arewardsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_BossRushQuestRewardRsp_proto_rawDescOnce sync.Once
	file_BossRushQuestRewardRsp_proto_rawDescData []byte
)

func file_BossRushQuestRewardRsp_proto_rawDescGZIP() []byte {
	file_BossRushQuestRewardRsp_proto_rawDescOnce.Do(func() {
		file_BossRushQuestRewardRsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_BossRushQuestRewardRsp_proto_rawDesc), len(file_BossRushQuestRewardRsp_proto_rawDesc)))
	})
	return file_BossRushQuestRewardRsp_proto_rawDescData
}

var file_BossRushQuestRewardRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_BossRushQuestRewardRsp_proto_goTypes = []any{
	(*BossRushQuestRewardRsp)(nil), // 0: proto.BossRushQuestRewardRsp
	(StatusCode)(0),                // 1: proto.StatusCode
	(*ItemDetail)(nil),             // 2: proto.ItemDetail
}
var file_BossRushQuestRewardRsp_proto_depIdxs = []int32{
	1, // 0: proto.BossRushQuestRewardRsp.status:type_name -> proto.StatusCode
	2, // 1: proto.BossRushQuestRewardRsp.rewards:type_name -> proto.ItemDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_BossRushQuestRewardRsp_proto_init() }
func file_BossRushQuestRewardRsp_proto_init() {
	if File_BossRushQuestRewardRsp_proto != nil {
		return
	}
	file_ItemDetail_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_BossRushQuestRewardRsp_proto_rawDesc), len(file_BossRushQuestRewardRsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BossRushQuestRewardRsp_proto_goTypes,
		DependencyIndexes: file_BossRushQuestRewardRsp_proto_depIdxs,
		MessageInfos:      file_BossRushQuestRewardRsp_proto_msgTypes,
	}.Build()
	File_BossRushQuestRewardRsp_proto = out.File
	file_BossRushQuestRewardRsp_proto_goTypes = nil
	file_BossRushQuestRewardRsp_proto_depIdxs = nil
}
