// Extracted message CameraCommon
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: CameraCommon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	G             float32                `protobuf:"fixed32,2,opt,name=G,proto3" json:"G,omitempty"`
	R             float32                `protobuf:"fixed32,3,opt,name=R,proto3" json:"R,omitempty"`
	B             float32                `protobuf:"fixed32,4,opt,name=B,proto3" json:"B,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraCommon) Reset() {
	*x = CameraCommon{}
	mi := &file_CameraCommon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraCommon) ProtoMessage() {}

func (x *CameraCommon) ProtoReflect() protoreflect.Message {
	mi := &file_CameraCommon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraCommon.ProtoReflect.Descriptor instead.
func (*CameraCommon) Descriptor() ([]byte, []int) {
	return file_CameraCommon_proto_rawDescGZIP(), []int{0}
}

func (x *CameraCommon) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *CameraCommon) GetG() float32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *CameraCommon) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *CameraCommon) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_CameraCommon_proto protoreflect.FileDescriptor

const file_CameraCommon_proto_rawDesc = "" +
	"\n" +
	"\x12CameraCommon.proto\x12\x05proto\"Q\n" +
	"\fCameraCommon\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\x12\f\n" +
	"\x01G\x18\x02 \x01(\x02R\x01G\x12\f\n" +
	"\x01R\x18\x03 \x01(\x02R\x01R\x12\f\n" +
	"\x01B\x18\x04 \x01(\x02R\x01BB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_CameraCommon_proto_rawDescOnce sync.Once
	file_CameraCommon_proto_rawDescData []byte
)

func file_CameraCommon_proto_rawDescGZIP() []byte {
	file_CameraCommon_proto_rawDescOnce.Do(func() {
		file_CameraCommon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CameraCommon_proto_rawDesc), len(file_CameraCommon_proto_rawDesc)))
	})
	return file_CameraCommon_proto_rawDescData
}

var file_CameraCommon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CameraCommon_proto_goTypes = []any{
	(*CameraCommon)(nil), // 0: proto.CameraCommon
}
var file_CameraCommon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CameraCommon_proto_init() }
func file_CameraCommon_proto_init() {
	if File_CameraCommon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CameraCommon_proto_rawDesc), len(file_CameraCommon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CameraCommon_proto_goTypes,
		DependencyIndexes: file_CameraCommon_proto_depIdxs,
		MessageInfos:      file_CameraCommon_proto_msgTypes,
	}.Build()
	File_CameraCommon_proto = out.File
	file_CameraCommon_proto_goTypes = nil
	file_CameraCommon_proto_depIdxs = nil
}
