// Extracted message Character
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: Character.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CharacterId               uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Level                     uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	MaxLevel                  uint32                 `protobuf:"varint,3,opt,name=max_level,json=maxLevel,proto3" json:"max_level,omitempty"`
	Exp                       uint32                 `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Star                      uint32                 `protobuf:"varint,5,opt,name=star,proto3" json:"star,omitempty"`
	EquipmentPresets          []*EquipmentPreset     `protobuf:"bytes,6,rep,name=equipment_presets,json=equipmentPresets,proto3" json:"equipment_presets,omitempty"`
	InUseEquipmentPresetIndex uint32                 `protobuf:"varint,7,opt,name=in_use_equipment_preset_index,json=inUseEquipmentPresetIndex,proto3" json:"in_use_equipment_preset_index,omitempty"`
	OutfitPresets             []*OutfitPreset        `protobuf:"bytes,8,rep,name=outfit_presets,json=outfitPresets,proto3" json:"outfit_presets,omitempty"`
	InUseOutfitPresetIndex    uint32                 `protobuf:"varint,9,opt,name=in_use_outfit_preset_index,json=inUseOutfitPresetIndex,proto3" json:"in_use_outfit_preset_index,omitempty"`
	GatherWeapon              uint32                 `protobuf:"varint,10,opt,name=gather_weapon,json=gatherWeapon,proto3" json:"gather_weapon,omitempty"`
	CharacterAppearance       *CharacterAppearance   `protobuf:"bytes,11,opt,name=character_appearance,json=characterAppearance,proto3" json:"character_appearance,omitempty"`
	CharacterSkillList        []*CharacterSkill      `protobuf:"bytes,12,rep,name=character_skill_list,json=characterSkillList,proto3" json:"character_skill_list,omitempty"`
	RewardedAchievementIdLst  []uint32               `protobuf:"varint,13,rep,packed,name=rewarded_achievement_id_lst,json=rewardedAchievementIdLst,proto3" json:"rewarded_achievement_id_lst,omitempty"`
	IsUnlockPayment           bool                   `protobuf:"varint,14,opt,name=is_unlock_payment,json=isUnlockPayment,proto3" json:"is_unlock_payment,omitempty"`
	RewardIndexLst            []uint32               `protobuf:"varint,15,rep,packed,name=reward_index_lst,json=rewardIndexLst,proto3" json:"reward_index_lst,omitempty"`
	MpGameWeapon              uint32                 `protobuf:"varint,16,opt,name=mp_game_weapon,json=mpGameWeapon,proto3" json:"mp_game_weapon,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_Character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_Character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_Character_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *Character) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetMaxLevel() uint32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

func (x *Character) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Character) GetStar() uint32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Character) GetEquipmentPresets() []*EquipmentPreset {
	if x != nil {
		return x.EquipmentPresets
	}
	return nil
}

func (x *Character) GetInUseEquipmentPresetIndex() uint32 {
	if x != nil {
		return x.InUseEquipmentPresetIndex
	}
	return 0
}

func (x *Character) GetOutfitPresets() []*OutfitPreset {
	if x != nil {
		return x.OutfitPresets
	}
	return nil
}

func (x *Character) GetInUseOutfitPresetIndex() uint32 {
	if x != nil {
		return x.InUseOutfitPresetIndex
	}
	return 0
}

func (x *Character) GetGatherWeapon() uint32 {
	if x != nil {
		return x.GatherWeapon
	}
	return 0
}

func (x *Character) GetCharacterAppearance() *CharacterAppearance {
	if x != nil {
		return x.CharacterAppearance
	}
	return nil
}

func (x *Character) GetCharacterSkillList() []*CharacterSkill {
	if x != nil {
		return x.CharacterSkillList
	}
	return nil
}

func (x *Character) GetRewardedAchievementIdLst() []uint32 {
	if x != nil {
		return x.RewardedAchievementIdLst
	}
	return nil
}

func (x *Character) GetIsUnlockPayment() bool {
	if x != nil {
		return x.IsUnlockPayment
	}
	return false
}

func (x *Character) GetRewardIndexLst() []uint32 {
	if x != nil {
		return x.RewardIndexLst
	}
	return nil
}

func (x *Character) GetMpGameWeapon() uint32 {
	if x != nil {
		return x.MpGameWeapon
	}
	return 0
}

var File_Character_proto protoreflect.FileDescriptor

const file_Character_proto_rawDesc = "" +
	"\n" +
	"\x0fCharacter.proto\x12\x05proto\x1a\x19CharacterAppearance.proto\x1a\x14CharacterSkill.proto\x1a\x15EquipmentPreset.proto\x1a\x12OutfitPreset.proto\"\xfe\x05\n" +
	"\tCharacter\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x1b\n" +
	"\tmax_level\x18\x03 \x01(\rR\bmaxLevel\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\rR\x03exp\x12\x12\n" +
	"\x04star\x18\x05 \x01(\rR\x04star\x12C\n" +
	"\x11equipment_presets\x18\x06 \x03(\v2\x16.proto.EquipmentPresetR\x10equipmentPresets\x12@\n" +
	"\x1din_use_equipment_preset_index\x18\a \x01(\rR\x19inUseEquipmentPresetIndex\x12:\n" +
	"\x0eoutfit_presets\x18\b \x03(\v2\x13.proto.OutfitPresetR\routfitPresets\x12:\n" +
	"\x1ain_use_outfit_preset_index\x18\t \x01(\rR\x16inUseOutfitPresetIndex\x12#\n" +
	"\rgather_weapon\x18\n" +
	" \x01(\rR\fgatherWeapon\x12M\n" +
	"\x14character_appearance\x18\v \x01(\v2\x1a.proto.CharacterAppearanceR\x13characterAppearance\x12G\n" +
	"\x14character_skill_list\x18\f \x03(\v2\x15.proto.CharacterSkillR\x12characterSkillList\x12=\n" +
	"\x1brewarded_achievement_id_lst\x18\r \x03(\rR\x18rewardedAchievementIdLst\x12*\n" +
	"\x11is_unlock_payment\x18\x0e \x01(\bR\x0fisUnlockPayment\x12(\n" +
	"\x10reward_index_lst\x18\x0f \x03(\rR\x0erewardIndexLst\x12$\n" +
	"\x0emp_game_weapon\x18\x10 \x01(\rR\fmpGameWeaponB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_Character_proto_rawDescOnce sync.Once
	file_Character_proto_rawDescData []byte
)

func file_Character_proto_rawDescGZIP() []byte {
	file_Character_proto_rawDescOnce.Do(func() {
		file_Character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Character_proto_rawDesc), len(file_Character_proto_rawDesc)))
	})
	return file_Character_proto_rawDescData
}

var file_Character_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Character_proto_goTypes = []any{
	(*Character)(nil),           // 0: proto.Character
	(*EquipmentPreset)(nil),     // 1: proto.EquipmentPreset
	(*OutfitPreset)(nil),        // 2: proto.OutfitPreset
	(*CharacterAppearance)(nil), // 3: proto.CharacterAppearance
	(*CharacterSkill)(nil),      // 4: proto.CharacterSkill
}
var file_Character_proto_depIdxs = []int32{
	1, // 0: proto.Character.equipment_presets:type_name -> proto.EquipmentPreset
	2, // 1: proto.Character.outfit_presets:type_name -> proto.OutfitPreset
	3, // 2: proto.Character.character_appearance:type_name -> proto.CharacterAppearance
	4, // 3: proto.Character.character_skill_list:type_name -> proto.CharacterSkill
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Character_proto_init() }
func file_Character_proto_init() {
	if File_Character_proto != nil {
		return
	}
	file_CharacterAppearance_proto_init()
	file_CharacterSkill_proto_init()
	file_EquipmentPreset_proto_init()
	file_OutfitPreset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Character_proto_rawDesc), len(file_Character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Character_proto_goTypes,
		DependencyIndexes: file_Character_proto_depIdxs,
		MessageInfos:      file_Character_proto_msgTypes,
	}.Build()
	File_Character_proto = out.File
	file_Character_proto_goTypes = nil
	file_Character_proto_depIdxs = nil
}
