// Extracted message CharacterLevelUpReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: CharacterLevelUpReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterLevelUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        uint32                 `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"`
	Nums          []int64                `protobuf:"varint,2,rep,packed,name=nums,proto3" json:"nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterLevelUpReq) Reset() {
	*x = CharacterLevelUpReq{}
	mi := &file_CharacterLevelUpReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterLevelUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterLevelUpReq) ProtoMessage() {}

func (x *CharacterLevelUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_CharacterLevelUpReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterLevelUpReq.ProtoReflect.Descriptor instead.
func (*CharacterLevelUpReq) Descriptor() ([]byte, []int) {
	return file_CharacterLevelUpReq_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterLevelUpReq) GetCharId() uint32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *CharacterLevelUpReq) GetNums() []int64 {
	if x != nil {
		return x.Nums
	}
	return nil
}

var File_CharacterLevelUpReq_proto protoreflect.FileDescriptor

const file_CharacterLevelUpReq_proto_rawDesc = "" +
	"\n" +
	"\x19CharacterLevelUpReq.proto\x12\x05proto\"B\n" +
	"\x13CharacterLevelUpReq\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\rR\x06charId\x12\x12\n" +
	"\x04nums\x18\x02 \x03(\x03R\x04numsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_CharacterLevelUpReq_proto_rawDescOnce sync.Once
	file_CharacterLevelUpReq_proto_rawDescData []byte
)

func file_CharacterLevelUpReq_proto_rawDescGZIP() []byte {
	file_CharacterLevelUpReq_proto_rawDescOnce.Do(func() {
		file_CharacterLevelUpReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CharacterLevelUpReq_proto_rawDesc), len(file_CharacterLevelUpReq_proto_rawDesc)))
	})
	return file_CharacterLevelUpReq_proto_rawDescData
}

var file_CharacterLevelUpReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CharacterLevelUpReq_proto_goTypes = []any{
	(*CharacterLevelUpReq)(nil), // 0: proto.CharacterLevelUpReq
}
var file_CharacterLevelUpReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CharacterLevelUpReq_proto_init() }
func file_CharacterLevelUpReq_proto_init() {
	if File_CharacterLevelUpReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CharacterLevelUpReq_proto_rawDesc), len(file_CharacterLevelUpReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CharacterLevelUpReq_proto_goTypes,
		DependencyIndexes: file_CharacterLevelUpReq_proto_depIdxs,
		MessageInfos:      file_CharacterLevelUpReq_proto_msgTypes,
	}.Build()
	File_CharacterLevelUpReq_proto = out.File
	file_CharacterLevelUpReq_proto_goTypes = nil
	file_CharacterLevelUpReq_proto_depIdxs = nil
}
