// Extracted message ChatMsgNotice
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ChatMsgNotice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMsgNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	Type          ChatChannelType        `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ChatChannelType" json:"type,omitempty"`
	Msg           *ChatMsgData           `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsgNotice) Reset() {
	*x = ChatMsgNotice{}
	mi := &file_ChatMsgNotice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsgNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgNotice) ProtoMessage() {}

func (x *ChatMsgNotice) ProtoReflect() protoreflect.Message {
	mi := &file_ChatMsgNotice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgNotice.ProtoReflect.Descriptor instead.
func (*ChatMsgNotice) Descriptor() ([]byte, []int) {
	return file_ChatMsgNotice_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMsgNotice) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *ChatMsgNotice) GetType() ChatChannelType {
	if x != nil {
		return x.Type
	}
	return ChatChannelType_ChatChannelType_ChatChannelDefault
}

func (x *ChatMsgNotice) GetMsg() *ChatMsgData {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_ChatMsgNotice_proto protoreflect.FileDescriptor

const file_ChatMsgNotice_proto_rawDesc = "" +
	"\n" +
	"\x13ChatMsgNotice.proto\x12\x05proto\x1a\x15ChatChannelType.proto\x1a\x11ChatMsgData.proto\x1a\x10StatusCode.proto\"\x8c\x01\n" +
	"\rChatMsgNotice\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.proto.ChatChannelTypeR\x04type\x12$\n" +
	"\x03msg\x18\x03 \x01(\v2\x12.proto.ChatMsgDataR\x03msgB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ChatMsgNotice_proto_rawDescOnce sync.Once
	file_ChatMsgNotice_proto_rawDescData []byte
)

func file_ChatMsgNotice_proto_rawDescGZIP() []byte {
	file_ChatMsgNotice_proto_rawDescOnce.Do(func() {
		file_ChatMsgNotice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ChatMsgNotice_proto_rawDesc), len(file_ChatMsgNotice_proto_rawDesc)))
	})
	return file_ChatMsgNotice_proto_rawDescData
}

var file_ChatMsgNotice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ChatMsgNotice_proto_goTypes = []any{
	(*ChatMsgNotice)(nil), // 0: proto.ChatMsgNotice
	(StatusCode)(0),       // 1: proto.StatusCode
	(ChatChannelType)(0),  // 2: proto.ChatChannelType
	(*ChatMsgData)(nil),   // 3: proto.ChatMsgData
}
var file_ChatMsgNotice_proto_depIdxs = []int32{
	1, // 0: proto.ChatMsgNotice.status:type_name -> proto.StatusCode
	2, // 1: proto.ChatMsgNotice.type:type_name -> proto.ChatChannelType
	3, // 2: proto.ChatMsgNotice.msg:type_name -> proto.ChatMsgData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ChatMsgNotice_proto_init() }
func file_ChatMsgNotice_proto_init() {
	if File_ChatMsgNotice_proto != nil {
		return
	}
	file_ChatChannelType_proto_init()
	file_ChatMsgData_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ChatMsgNotice_proto_rawDesc), len(file_ChatMsgNotice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ChatMsgNotice_proto_goTypes,
		DependencyIndexes: file_ChatMsgNotice_proto_depIdxs,
		MessageInfos:      file_ChatMsgNotice_proto_msgTypes,
	}.Build()
	File_ChatMsgNotice_proto = out.File
	file_ChatMsgNotice_proto_goTypes = nil
	file_ChatMsgNotice_proto_depIdxs = nil
}
