// Extracted message ClientLogMessage
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ClientLogMessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientLogMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientLogSeqId  uint32                 `protobuf:"varint,1,opt,name=client_log_seq_id,json=clientLogSeqId,proto3" json:"client_log_seq_id,omitempty"`
	LogTemplate     string                 `protobuf:"bytes,2,opt,name=log_template,json=logTemplate,proto3" json:"log_template,omitempty"`
	LogTemplateHash string                 `protobuf:"bytes,3,opt,name=log_template_hash,json=logTemplateHash,proto3" json:"log_template_hash,omitempty"`
	LogLevel        ClientLogLevel         `protobuf:"varint,4,opt,name=log_level,json=logLevel,proto3,enum=proto.ClientLogLevel" json:"log_level,omitempty"`
	ClientTimeMs    int64                  `protobuf:"varint,5,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	Channel         int32                  `protobuf:"varint,6,opt,name=channel,proto3" json:"channel,omitempty"`
	Params          []*CommonParam         `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientLogMessage) Reset() {
	*x = ClientLogMessage{}
	mi := &file_ClientLogMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientLogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLogMessage) ProtoMessage() {}

func (x *ClientLogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ClientLogMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLogMessage.ProtoReflect.Descriptor instead.
func (*ClientLogMessage) Descriptor() ([]byte, []int) {
	return file_ClientLogMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ClientLogMessage) GetClientLogSeqId() uint32 {
	if x != nil {
		return x.ClientLogSeqId
	}
	return 0
}

func (x *ClientLogMessage) GetLogTemplate() string {
	if x != nil {
		return x.LogTemplate
	}
	return ""
}

func (x *ClientLogMessage) GetLogTemplateHash() string {
	if x != nil {
		return x.LogTemplateHash
	}
	return ""
}

func (x *ClientLogMessage) GetLogLevel() ClientLogLevel {
	if x != nil {
		return x.LogLevel
	}
	return ClientLogLevel_ClientLogLevel_Debug
}

func (x *ClientLogMessage) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *ClientLogMessage) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ClientLogMessage) GetParams() []*CommonParam {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_ClientLogMessage_proto protoreflect.FileDescriptor

const file_ClientLogMessage_proto_rawDesc = "" +
	"\n" +
	"\x16ClientLogMessage.proto\x12\x05proto\x1a\x14ClientLogLevel.proto\x1a\x11CommonParam.proto\"\xac\x02\n" +
	"\x10ClientLogMessage\x12)\n" +
	"\x11client_log_seq_id\x18\x01 \x01(\rR\x0eclientLogSeqId\x12!\n" +
	"\flog_template\x18\x02 \x01(\tR\vlogTemplate\x12*\n" +
	"\x11log_template_hash\x18\x03 \x01(\tR\x0flogTemplateHash\x122\n" +
	"\tlog_level\x18\x04 \x01(\x0e2\x15.proto.ClientLogLevelR\blogLevel\x12$\n" +
	"\x0eclient_time_ms\x18\x05 \x01(\x03R\fclientTimeMs\x12\x18\n" +
	"\achannel\x18\x06 \x01(\x05R\achannel\x12*\n" +
	"\x06params\x18\a \x03(\v2\x12.proto.CommonParamR\x06paramsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ClientLogMessage_proto_rawDescOnce sync.Once
	file_ClientLogMessage_proto_rawDescData []byte
)

func file_ClientLogMessage_proto_rawDescGZIP() []byte {
	file_ClientLogMessage_proto_rawDescOnce.Do(func() {
		file_ClientLogMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ClientLogMessage_proto_rawDesc), len(file_ClientLogMessage_proto_rawDesc)))
	})
	return file_ClientLogMessage_proto_rawDescData
}

var file_ClientLogMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ClientLogMessage_proto_goTypes = []any{
	(*ClientLogMessage)(nil), // 0: proto.ClientLogMessage
	(ClientLogLevel)(0),      // 1: proto.ClientLogLevel
	(*CommonParam)(nil),      // 2: proto.CommonParam
}
var file_ClientLogMessage_proto_depIdxs = []int32{
	1, // 0: proto.ClientLogMessage.log_level:type_name -> proto.ClientLogLevel
	2, // 1: proto.ClientLogMessage.params:type_name -> proto.CommonParam
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ClientLogMessage_proto_init() }
func file_ClientLogMessage_proto_init() {
	if File_ClientLogMessage_proto != nil {
		return
	}
	file_ClientLogLevel_proto_init()
	file_CommonParam_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ClientLogMessage_proto_rawDesc), len(file_ClientLogMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ClientLogMessage_proto_goTypes,
		DependencyIndexes: file_ClientLogMessage_proto_depIdxs,
		MessageInfos:      file_ClientLogMessage_proto_msgTypes,
	}.Build()
	File_ClientLogMessage_proto = out.File
	file_ClientLogMessage_proto_goTypes = nil
	file_ClientLogMessage_proto_depIdxs = nil
}
