// Extracted message CollectCoinRsp
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: CollectCoinRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectCoinRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	CoinIndex     uint32                 `protobuf:"varint,2,opt,name=coin_index,json=coinIndex,proto3" json:"coin_index,omitempty"`
	Rewards       []*ItemDetail          `protobuf:"bytes,3,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectCoinRsp) Reset() {
	*x = CollectCoinRsp{}
	mi := &file_CollectCoinRsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectCoinRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectCoinRsp) ProtoMessage() {}

func (x *CollectCoinRsp) ProtoReflect() protoreflect.Message {
	mi := &file_CollectCoinRsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectCoinRsp.ProtoReflect.Descriptor instead.
func (*CollectCoinRsp) Descriptor() ([]byte, []int) {
	return file_CollectCoinRsp_proto_rawDescGZIP(), []int{0}
}

func (x *CollectCoinRsp) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *CollectCoinRsp) GetCoinIndex() uint32 {
	if x != nil {
		return x.CoinIndex
	}
	return 0
}

func (x *CollectCoinRsp) GetRewards() []*ItemDetail {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_CollectCoinRsp_proto protoreflect.FileDescriptor

const file_CollectCoinRsp_proto_rawDesc = "" +
	"\n" +
	"\x14CollectCoinRsp.proto\x12\x05proto\x1a\x10ItemDetail.proto\x1a\x10StatusCode.proto\"\x87\x01\n" +
	"\x0eCollectCoinRsp\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12\x1d\n" +
	"\n" +
	"coin_index\x18\x02 \x01(\rR\tcoinIndex\x12+\n" +
	"\arewards\x18\x03 \x03(\v2\x11.proto.ItemDetailR\arewardsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_CollectCoinRsp_proto_rawDescOnce sync.Once
	file_CollectCoinRsp_proto_rawDescData []byte
)

func file_CollectCoinRsp_proto_rawDescGZIP() []byte {
	file_CollectCoinRsp_proto_rawDescOnce.Do(func() {
		file_CollectCoinRsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CollectCoinRsp_proto_rawDesc), len(file_CollectCoinRsp_proto_rawDesc)))
	})
	return file_CollectCoinRsp_proto_rawDescData
}

var file_CollectCoinRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CollectCoinRsp_proto_goTypes = []any{
	(*CollectCoinRsp)(nil), // 0: proto.CollectCoinRsp
	(StatusCode)(0),        // 1: proto.StatusCode
	(*ItemDetail)(nil),     // 2: proto.ItemDetail
}
var file_CollectCoinRsp_proto_depIdxs = []int32{
	1, // 0: proto.CollectCoinRsp.status:type_name -> proto.StatusCode
	2, // 1: proto.CollectCoinRsp.rewards:type_name -> proto.ItemDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CollectCoinRsp_proto_init() }
func file_CollectCoinRsp_proto_init() {
	if File_CollectCoinRsp_proto != nil {
		return
	}
	file_ItemDetail_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CollectCoinRsp_proto_rawDesc), len(file_CollectCoinRsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CollectCoinRsp_proto_goTypes,
		DependencyIndexes: file_CollectCoinRsp_proto_depIdxs,
		MessageInfos:      file_CollectCoinRsp_proto_msgTypes,
	}.Build()
	File_CollectCoinRsp_proto = out.File
	file_CollectCoinRsp_proto_goTypes = nil
	file_CollectCoinRsp_proto_depIdxs = nil
}
