// Extracted message DoLikesReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: DoLikesReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoLikesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoLikesReq) Reset() {
	*x = DoLikesReq{}
	mi := &file_DoLikesReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoLikesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoLikesReq) ProtoMessage() {}

func (x *DoLikesReq) ProtoReflect() protoreflect.Message {
	mi := &file_DoLikesReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoLikesReq.ProtoReflect.Descriptor instead.
func (*DoLikesReq) Descriptor() ([]byte, []int) {
	return file_DoLikesReq_proto_rawDescGZIP(), []int{0}
}

var File_DoLikesReq_proto protoreflect.FileDescriptor

const file_DoLikesReq_proto_rawDesc = "" +
	"\n" +
	"\x10DoLikesReq.proto\x12\x05proto\"\f\n" +
	"\n" +
	"DoLikesReqB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_DoLikesReq_proto_rawDescOnce sync.Once
	file_DoLikesReq_proto_rawDescData []byte
)

func file_DoLikesReq_proto_rawDescGZIP() []byte {
	file_DoLikesReq_proto_rawDescOnce.Do(func() {
		file_DoLikesReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DoLikesReq_proto_rawDesc), len(file_DoLikesReq_proto_rawDesc)))
	})
	return file_DoLikesReq_proto_rawDescData
}

var file_DoLikesReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DoLikesReq_proto_goTypes = []any{
	(*DoLikesReq)(nil), // 0: proto.DoLikesReq
}
var file_DoLikesReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DoLikesReq_proto_init() }
func file_DoLikesReq_proto_init() {
	if File_DoLikesReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DoLikesReq_proto_rawDesc), len(file_DoLikesReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DoLikesReq_proto_goTypes,
		DependencyIndexes: file_DoLikesReq_proto_depIdxs,
		MessageInfos:      file_DoLikesReq_proto_msgTypes,
	}.Build()
	File_DoLikesReq_proto = out.File
	file_DoLikesReq_proto_goTypes = nil
	file_DoLikesReq_proto_depIdxs = nil
}
