// Extracted message DropItem
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: DropItem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DropItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Items         []*ItemDetail          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropItem) Reset() {
	*x = DropItem{}
	mi := &file_DropItem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropItem) ProtoMessage() {}

func (x *DropItem) ProtoReflect() protoreflect.Message {
	mi := &file_DropItem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropItem.ProtoReflect.Descriptor instead.
func (*DropItem) Descriptor() ([]byte, []int) {
	return file_DropItem_proto_rawDescGZIP(), []int{0}
}

func (x *DropItem) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DropItem) GetItems() []*ItemDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_DropItem_proto protoreflect.FileDescriptor

const file_DropItem_proto_rawDesc = "" +
	"\n" +
	"\x0eDropItem.proto\x12\x05proto\x1a\x10ItemDetail.proto\"I\n" +
	"\bDropItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.proto.ItemDetailR\x05itemsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_DropItem_proto_rawDescOnce sync.Once
	file_DropItem_proto_rawDescData []byte
)

func file_DropItem_proto_rawDescGZIP() []byte {
	file_DropItem_proto_rawDescOnce.Do(func() {
		file_DropItem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DropItem_proto_rawDesc), len(file_DropItem_proto_rawDesc)))
	})
	return file_DropItem_proto_rawDescData
}

var file_DropItem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_DropItem_proto_goTypes = []any{
	(*DropItem)(nil),   // 0: proto.DropItem
	(*ItemDetail)(nil), // 1: proto.ItemDetail
}
var file_DropItem_proto_depIdxs = []int32{
	1, // 0: proto.DropItem.items:type_name -> proto.ItemDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_DropItem_proto_init() }
func file_DropItem_proto_init() {
	if File_DropItem_proto != nil {
		return
	}
	file_ItemDetail_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DropItem_proto_rawDesc), len(file_DropItem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DropItem_proto_goTypes,
		DependencyIndexes: file_DropItem_proto_depIdxs,
		MessageInfos:      file_DropItem_proto_msgTypes,
	}.Build()
	File_DropItem_proto = out.File
	file_DropItem_proto_goTypes = nil
	file_DropItem_proto_depIdxs = nil
}
