// Extracted enum EAIType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EAIType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAIType int32

const (
	EAIType_EAIType_MeleeAi  EAIType = 0
	EAIType_EAIType_RangedAi EAIType = 1
)

// Enum value maps for EAIType.
var (
	EAIType_name = map[int32]string{
		0: "EAIType_MeleeAi",
		1: "EAIType_RangedAi",
	}
	EAIType_value = map[string]int32{
		"EAIType_MeleeAi":  0,
		"EAIType_RangedAi": 1,
	}
)

func (x EAIType) Enum() *EAIType {
	p := new(EAIType)
	*p = x
	return p
}

func (x EAIType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAIType) Descriptor() protoreflect.EnumDescriptor {
	return file_EAIType_proto_enumTypes[0].Descriptor()
}

func (EAIType) Type() protoreflect.EnumType {
	return &file_EAIType_proto_enumTypes[0]
}

func (x EAIType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EAIType.Descriptor instead.
func (EAIType) EnumDescriptor() ([]byte, []int) {
	return file_EAIType_proto_rawDescGZIP(), []int{0}
}

var File_EAIType_proto protoreflect.FileDescriptor

const file_EAIType_proto_rawDesc = "" +
	"\n" +
	"\rEAIType.proto\x12\x05proto*4\n" +
	"\aEAIType\x12\x13\n" +
	"\x0fEAIType_MeleeAi\x10\x00\x12\x14\n" +
	"\x10EAIType_RangedAi\x10\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_EAIType_proto_rawDescOnce sync.Once
	file_EAIType_proto_rawDescData []byte
)

func file_EAIType_proto_rawDescGZIP() []byte {
	file_EAIType_proto_rawDescOnce.Do(func() {
		file_EAIType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EAIType_proto_rawDesc), len(file_EAIType_proto_rawDesc)))
	})
	return file_EAIType_proto_rawDescData
}

var file_EAIType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EAIType_proto_goTypes = []any{
	(EAIType)(0), // 0: proto.EAIType
}
var file_EAIType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EAIType_proto_init() }
func file_EAIType_proto_init() {
	if File_EAIType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EAIType_proto_rawDesc), len(file_EAIType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EAIType_proto_goTypes,
		DependencyIndexes: file_EAIType_proto_depIdxs,
		EnumInfos:         file_EAIType_proto_enumTypes,
	}.Build()
	File_EAIType_proto = out.File
	file_EAIType_proto_goTypes = nil
	file_EAIType_proto_depIdxs = nil
}
