// Extracted enum EAttackType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EAttackType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EAttackType int32

const (
	EAttackType_EAttackType_Melee  EAttackType = 0
	EAttackType_EAttackType_Remote EAttackType = 1
)

// Enum value maps for EAttackType.
var (
	EAttackType_name = map[int32]string{
		0: "EAttackType_Melee",
		1: "EAttackType_Remote",
	}
	EAttackType_value = map[string]int32{
		"EAttackType_Melee":  0,
		"EAttackType_Remote": 1,
	}
)

func (x EAttackType) Enum() *EAttackType {
	p := new(EAttackType)
	*p = x
	return p
}

func (x EAttackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAttackType) Descriptor() protoreflect.EnumDescriptor {
	return file_EAttackType_proto_enumTypes[0].Descriptor()
}

func (EAttackType) Type() protoreflect.EnumType {
	return &file_EAttackType_proto_enumTypes[0]
}

func (x EAttackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EAttackType.Descriptor instead.
func (EAttackType) EnumDescriptor() ([]byte, []int) {
	return file_EAttackType_proto_rawDescGZIP(), []int{0}
}

var File_EAttackType_proto protoreflect.FileDescriptor

const file_EAttackType_proto_rawDesc = "" +
	"\n" +
	"\x11EAttackType.proto\x12\x05proto*<\n" +
	"\vEAttackType\x12\x15\n" +
	"\x11EAttackType_Melee\x10\x00\x12\x16\n" +
	"\x12EAttackType_Remote\x10\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_EAttackType_proto_rawDescOnce sync.Once
	file_EAttackType_proto_rawDescData []byte
)

func file_EAttackType_proto_rawDescGZIP() []byte {
	file_EAttackType_proto_rawDescOnce.Do(func() {
		file_EAttackType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EAttackType_proto_rawDesc), len(file_EAttackType_proto_rawDesc)))
	})
	return file_EAttackType_proto_rawDescData
}

var file_EAttackType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EAttackType_proto_goTypes = []any{
	(EAttackType)(0), // 0: proto.EAttackType
}
var file_EAttackType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EAttackType_proto_init() }
func file_EAttackType_proto_init() {
	if File_EAttackType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EAttackType_proto_rawDesc), len(file_EAttackType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EAttackType_proto_goTypes,
		DependencyIndexes: file_EAttackType_proto_depIdxs,
		EnumInfos:         file_EAttackType_proto_enumTypes,
	}.Build()
	File_EAttackType_proto = out.File
	file_EAttackType_proto_goTypes = nil
	file_EAttackType_proto_depIdxs = nil
}
