// Extracted enum EBagItemDyeType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EBagItemDyeType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EBagItemDyeType int32

const (
	EBagItemDyeType_EBagItemDyeType_Random EBagItemDyeType = 0
	EBagItemDyeType_EBagItemDyeType_Fixed  EBagItemDyeType = 1
)

// Enum value maps for EBagItemDyeType.
var (
	EBagItemDyeType_name = map[int32]string{
		0: "EBagItemDyeType_Random",
		1: "EBagItemDyeType_Fixed",
	}
	EBagItemDyeType_value = map[string]int32{
		"EBagItemDyeType_Random": 0,
		"EBagItemDyeType_Fixed":  1,
	}
)

func (x EBagItemDyeType) Enum() *EBagItemDyeType {
	p := new(EBagItemDyeType)
	*p = x
	return p
}

func (x EBagItemDyeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EBagItemDyeType) Descriptor() protoreflect.EnumDescriptor {
	return file_EBagItemDyeType_proto_enumTypes[0].Descriptor()
}

func (EBagItemDyeType) Type() protoreflect.EnumType {
	return &file_EBagItemDyeType_proto_enumTypes[0]
}

func (x EBagItemDyeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EBagItemDyeType.Descriptor instead.
func (EBagItemDyeType) EnumDescriptor() ([]byte, []int) {
	return file_EBagItemDyeType_proto_rawDescGZIP(), []int{0}
}

var File_EBagItemDyeType_proto protoreflect.FileDescriptor

const file_EBagItemDyeType_proto_rawDesc = "" +
	"\n" +
	"\x15EBagItemDyeType.proto\x12\x05proto*H\n" +
	"\x0fEBagItemDyeType\x12\x1a\n" +
	"\x16EBagItemDyeType_Random\x10\x00\x12\x19\n" +
	"\x15EBagItemDyeType_Fixed\x10\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_EBagItemDyeType_proto_rawDescOnce sync.Once
	file_EBagItemDyeType_proto_rawDescData []byte
)

func file_EBagItemDyeType_proto_rawDescGZIP() []byte {
	file_EBagItemDyeType_proto_rawDescOnce.Do(func() {
		file_EBagItemDyeType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EBagItemDyeType_proto_rawDesc), len(file_EBagItemDyeType_proto_rawDesc)))
	})
	return file_EBagItemDyeType_proto_rawDescData
}

var file_EBagItemDyeType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EBagItemDyeType_proto_goTypes = []any{
	(EBagItemDyeType)(0), // 0: proto.EBagItemDyeType
}
var file_EBagItemDyeType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EBagItemDyeType_proto_init() }
func file_EBagItemDyeType_proto_init() {
	if File_EBagItemDyeType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EBagItemDyeType_proto_rawDesc), len(file_EBagItemDyeType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EBagItemDyeType_proto_goTypes,
		DependencyIndexes: file_EBagItemDyeType_proto_depIdxs,
		EnumInfos:         file_EBagItemDyeType_proto_enumTypes,
	}.Build()
	File_EBagItemDyeType_proto = out.File
	file_EBagItemDyeType_proto_goTypes = nil
	file_EBagItemDyeType_proto_depIdxs = nil
}
