// Extracted enum EGemDuelAchieveCondition
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EGemDuelAchieveCondition.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EGemDuelAchieveCondition int32

const (
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_MainDungeonPass       EGemDuelAchieveCondition = 0
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_AnyMainDungeonPass    EGemDuelAchieveCondition = 1
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_AnyMainDungeonPass1   EGemDuelAchieveCondition = 2
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_AnyCharacterLevelUp   EGemDuelAchieveCondition = 3
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_ArenaWinVictory       EGemDuelAchieveCondition = 4
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_OnceDungeonDuelRemove EGemDuelAchieveCondition = 5
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_DailyLogin            EGemDuelAchieveCondition = 6
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_DailyLogin1           EGemDuelAchieveCondition = 7
	EGemDuelAchieveCondition_EGemDuelAchieveCondition_AnyPoolDraw           EGemDuelAchieveCondition = 8
)

// Enum value maps for EGemDuelAchieveCondition.
var (
	EGemDuelAchieveCondition_name = map[int32]string{
		0: "EGemDuelAchieveCondition_MainDungeonPass",
		1: "EGemDuelAchieveCondition_AnyMainDungeonPass",
		2: "EGemDuelAchieveCondition_AnyMainDungeonPass1",
		3: "EGemDuelAchieveCondition_AnyCharacterLevelUp",
		4: "EGemDuelAchieveCondition_ArenaWinVictory",
		5: "EGemDuelAchieveCondition_OnceDungeonDuelRemove",
		6: "EGemDuelAchieveCondition_DailyLogin",
		7: "EGemDuelAchieveCondition_DailyLogin1",
		8: "EGemDuelAchieveCondition_AnyPoolDraw",
	}
	EGemDuelAchieveCondition_value = map[string]int32{
		"EGemDuelAchieveCondition_MainDungeonPass":       0,
		"EGemDuelAchieveCondition_AnyMainDungeonPass":    1,
		"EGemDuelAchieveCondition_AnyMainDungeonPass1":   2,
		"EGemDuelAchieveCondition_AnyCharacterLevelUp":   3,
		"EGemDuelAchieveCondition_ArenaWinVictory":       4,
		"EGemDuelAchieveCondition_OnceDungeonDuelRemove": 5,
		"EGemDuelAchieveCondition_DailyLogin":            6,
		"EGemDuelAchieveCondition_DailyLogin1":           7,
		"EGemDuelAchieveCondition_AnyPoolDraw":           8,
	}
)

func (x EGemDuelAchieveCondition) Enum() *EGemDuelAchieveCondition {
	p := new(EGemDuelAchieveCondition)
	*p = x
	return p
}

func (x EGemDuelAchieveCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EGemDuelAchieveCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_EGemDuelAchieveCondition_proto_enumTypes[0].Descriptor()
}

func (EGemDuelAchieveCondition) Type() protoreflect.EnumType {
	return &file_EGemDuelAchieveCondition_proto_enumTypes[0]
}

func (x EGemDuelAchieveCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EGemDuelAchieveCondition.Descriptor instead.
func (EGemDuelAchieveCondition) EnumDescriptor() ([]byte, []int) {
	return file_EGemDuelAchieveCondition_proto_rawDescGZIP(), []int{0}
}

var File_EGemDuelAchieveCondition_proto protoreflect.FileDescriptor

const file_EGemDuelAchieveCondition_proto_rawDesc = "" +
	"\n" +
	"\x1eEGemDuelAchieveCondition.proto\x12\x05proto*\xbc\x03\n" +
	"\x18EGemDuelAchieveCondition\x12,\n" +
	"(EGemDuelAchieveCondition_MainDungeonPass\x10\x00\x12/\n" +
	"+EGemDuelAchieveCondition_AnyMainDungeonPass\x10\x01\x120\n" +
	",EGemDuelAchieveCondition_AnyMainDungeonPass1\x10\x02\x120\n" +
	",EGemDuelAchieveCondition_AnyCharacterLevelUp\x10\x03\x12,\n" +
	"(EGemDuelAchieveCondition_ArenaWinVictory\x10\x04\x122\n" +
	".EGemDuelAchieveCondition_OnceDungeonDuelRemove\x10\x05\x12'\n" +
	"#EGemDuelAchieveCondition_DailyLogin\x10\x06\x12(\n" +
	"$EGemDuelAchieveCondition_DailyLogin1\x10\a\x12(\n" +
	"$EGemDuelAchieveCondition_AnyPoolDraw\x10\bB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_EGemDuelAchieveCondition_proto_rawDescOnce sync.Once
	file_EGemDuelAchieveCondition_proto_rawDescData []byte
)

func file_EGemDuelAchieveCondition_proto_rawDescGZIP() []byte {
	file_EGemDuelAchieveCondition_proto_rawDescOnce.Do(func() {
		file_EGemDuelAchieveCondition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EGemDuelAchieveCondition_proto_rawDesc), len(file_EGemDuelAchieveCondition_proto_rawDesc)))
	})
	return file_EGemDuelAchieveCondition_proto_rawDescData
}

var file_EGemDuelAchieveCondition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EGemDuelAchieveCondition_proto_goTypes = []any{
	(EGemDuelAchieveCondition)(0), // 0: proto.EGemDuelAchieveCondition
}
var file_EGemDuelAchieveCondition_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EGemDuelAchieveCondition_proto_init() }
func file_EGemDuelAchieveCondition_proto_init() {
	if File_EGemDuelAchieveCondition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EGemDuelAchieveCondition_proto_rawDesc), len(file_EGemDuelAchieveCondition_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EGemDuelAchieveCondition_proto_goTypes,
		DependencyIndexes: file_EGemDuelAchieveCondition_proto_depIdxs,
		EnumInfos:         file_EGemDuelAchieveCondition_proto_enumTypes,
	}.Build()
	File_EGemDuelAchieveCondition_proto = out.File
	file_EGemDuelAchieveCondition_proto_goTypes = nil
	file_EGemDuelAchieveCondition_proto_depIdxs = nil
}
