// Extracted enum EMonsterTag
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EMonsterTag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EMonsterTag int32

const (
	EMonsterTag_EMonsterTag_None    EMonsterTag = 0
	EMonsterTag_EMonsterTag_Normal  EMonsterTag = 1
	EMonsterTag_EMonsterTag_Elite   EMonsterTag = 2
	EMonsterTag_EMonsterTag_Boss    EMonsterTag = 3
	EMonsterTag_EMonsterTag_Special EMonsterTag = 4
)

// Enum value maps for EMonsterTag.
var (
	EMonsterTag_name = map[int32]string{
		0: "EMonsterTag_None",
		1: "EMonsterTag_Normal",
		2: "EMonsterTag_Elite",
		3: "EMonsterTag_Boss",
		4: "EMonsterTag_Special",
	}
	EMonsterTag_value = map[string]int32{
		"EMonsterTag_None":    0,
		"EMonsterTag_Normal":  1,
		"EMonsterTag_Elite":   2,
		"EMonsterTag_Boss":    3,
		"EMonsterTag_Special": 4,
	}
)

func (x EMonsterTag) Enum() *EMonsterTag {
	p := new(EMonsterTag)
	*p = x
	return p
}

func (x EMonsterTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMonsterTag) Descriptor() protoreflect.EnumDescriptor {
	return file_EMonsterTag_proto_enumTypes[0].Descriptor()
}

func (EMonsterTag) Type() protoreflect.EnumType {
	return &file_EMonsterTag_proto_enumTypes[0]
}

func (x EMonsterTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMonsterTag.Descriptor instead.
func (EMonsterTag) EnumDescriptor() ([]byte, []int) {
	return file_EMonsterTag_proto_rawDescGZIP(), []int{0}
}

var File_EMonsterTag_proto protoreflect.FileDescriptor

const file_EMonsterTag_proto_rawDesc = "" +
	"\n" +
	"\x11EMonsterTag.proto\x12\x05proto*\x81\x01\n" +
	"\vEMonsterTag\x12\x14\n" +
	"\x10EMonsterTag_None\x10\x00\x12\x16\n" +
	"\x12EMonsterTag_Normal\x10\x01\x12\x15\n" +
	"\x11EMonsterTag_Elite\x10\x02\x12\x14\n" +
	"\x10EMonsterTag_Boss\x10\x03\x12\x17\n" +
	"\x13EMonsterTag_Special\x10\x04B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_EMonsterTag_proto_rawDescOnce sync.Once
	file_EMonsterTag_proto_rawDescData []byte
)

func file_EMonsterTag_proto_rawDescGZIP() []byte {
	file_EMonsterTag_proto_rawDescOnce.Do(func() {
		file_EMonsterTag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EMonsterTag_proto_rawDesc), len(file_EMonsterTag_proto_rawDesc)))
	})
	return file_EMonsterTag_proto_rawDescData
}

var file_EMonsterTag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EMonsterTag_proto_goTypes = []any{
	(EMonsterTag)(0), // 0: proto.EMonsterTag
}
var file_EMonsterTag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EMonsterTag_proto_init() }
func file_EMonsterTag_proto_init() {
	if File_EMonsterTag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EMonsterTag_proto_rawDesc), len(file_EMonsterTag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EMonsterTag_proto_goTypes,
		DependencyIndexes: file_EMonsterTag_proto_depIdxs,
		EnumInfos:         file_EMonsterTag_proto_enumTypes,
	}.Build()
	File_EMonsterTag_proto = out.File
	file_EMonsterTag_proto_goTypes = nil
	file_EMonsterTag_proto_depIdxs = nil
}
