// Extracted enum ERewardDropDecayType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ERewardDropDecayType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ERewardDropDecayType int32

const (
	ERewardDropDecayType_ERewardDropDecayType_Never       ERewardDropDecayType = 0
	ERewardDropDecayType_ERewardDropDecayType_Quantity    ERewardDropDecayType = 1
	ERewardDropDecayType_ERewardDropDecayType_Probability ERewardDropDecayType = 2
)

// Enum value maps for ERewardDropDecayType.
var (
	ERewardDropDecayType_name = map[int32]string{
		0: "ERewardDropDecayType_Never",
		1: "ERewardDropDecayType_Quantity",
		2: "ERewardDropDecayType_Probability",
	}
	ERewardDropDecayType_value = map[string]int32{
		"ERewardDropDecayType_Never":       0,
		"ERewardDropDecayType_Quantity":    1,
		"ERewardDropDecayType_Probability": 2,
	}
)

func (x ERewardDropDecayType) Enum() *ERewardDropDecayType {
	p := new(ERewardDropDecayType)
	*p = x
	return p
}

func (x ERewardDropDecayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERewardDropDecayType) Descriptor() protoreflect.EnumDescriptor {
	return file_ERewardDropDecayType_proto_enumTypes[0].Descriptor()
}

func (ERewardDropDecayType) Type() protoreflect.EnumType {
	return &file_ERewardDropDecayType_proto_enumTypes[0]
}

func (x ERewardDropDecayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERewardDropDecayType.Descriptor instead.
func (ERewardDropDecayType) EnumDescriptor() ([]byte, []int) {
	return file_ERewardDropDecayType_proto_rawDescGZIP(), []int{0}
}

var File_ERewardDropDecayType_proto protoreflect.FileDescriptor

const file_ERewardDropDecayType_proto_rawDesc = "" +
	"\n" +
	"\x1aERewardDropDecayType.proto\x12\x05proto*\x7f\n" +
	"\x14ERewardDropDecayType\x12\x1e\n" +
	"\x1aERewardDropDecayType_Never\x10\x00\x12!\n" +
	"\x1dERewardDropDecayType_Quantity\x10\x01\x12$\n" +
	" ERewardDropDecayType_Probability\x10\x02B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ERewardDropDecayType_proto_rawDescOnce sync.Once
	file_ERewardDropDecayType_proto_rawDescData []byte
)

func file_ERewardDropDecayType_proto_rawDescGZIP() []byte {
	file_ERewardDropDecayType_proto_rawDescOnce.Do(func() {
		file_ERewardDropDecayType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ERewardDropDecayType_proto_rawDesc), len(file_ERewardDropDecayType_proto_rawDesc)))
	})
	return file_ERewardDropDecayType_proto_rawDescData
}

var file_ERewardDropDecayType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ERewardDropDecayType_proto_goTypes = []any{
	(ERewardDropDecayType)(0), // 0: proto.ERewardDropDecayType
}
var file_ERewardDropDecayType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ERewardDropDecayType_proto_init() }
func file_ERewardDropDecayType_proto_init() {
	if File_ERewardDropDecayType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ERewardDropDecayType_proto_rawDesc), len(file_ERewardDropDecayType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ERewardDropDecayType_proto_goTypes,
		DependencyIndexes: file_ERewardDropDecayType_proto_depIdxs,
		EnumInfos:         file_ERewardDropDecayType_proto_enumTypes,
	}.Build()
	File_ERewardDropDecayType_proto = out.File
	file_ERewardDropDecayType_proto_goTypes = nil
	file_ERewardDropDecayType_proto_depIdxs = nil
}
