// Extracted enum ESeasonType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ESeasonType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ESeasonType int32

const (
	ESeasonType_ESeasonType_Spring ESeasonType = 0
	ESeasonType_ESeasonType_Summer ESeasonType = 1
	ESeasonType_ESeasonType_Autumn ESeasonType = 2
	ESeasonType_ESeasonType_Winter ESeasonType = 3
)

// Enum value maps for ESeasonType.
var (
	ESeasonType_name = map[int32]string{
		0: "ESeasonType_Spring",
		1: "ESeasonType_Summer",
		2: "ESeasonType_Autumn",
		3: "ESeasonType_Winter",
	}
	ESeasonType_value = map[string]int32{
		"ESeasonType_Spring": 0,
		"ESeasonType_Summer": 1,
		"ESeasonType_Autumn": 2,
		"ESeasonType_Winter": 3,
	}
)

func (x ESeasonType) Enum() *ESeasonType {
	p := new(ESeasonType)
	*p = x
	return p
}

func (x ESeasonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESeasonType) Descriptor() protoreflect.EnumDescriptor {
	return file_ESeasonType_proto_enumTypes[0].Descriptor()
}

func (ESeasonType) Type() protoreflect.EnumType {
	return &file_ESeasonType_proto_enumTypes[0]
}

func (x ESeasonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ESeasonType.Descriptor instead.
func (ESeasonType) EnumDescriptor() ([]byte, []int) {
	return file_ESeasonType_proto_rawDescGZIP(), []int{0}
}

var File_ESeasonType_proto protoreflect.FileDescriptor

const file_ESeasonType_proto_rawDesc = "" +
	"\n" +
	"\x11ESeasonType.proto\x12\x05proto*m\n" +
	"\vESeasonType\x12\x16\n" +
	"\x12ESeasonType_Spring\x10\x00\x12\x16\n" +
	"\x12ESeasonType_Summer\x10\x01\x12\x16\n" +
	"\x12ESeasonType_Autumn\x10\x02\x12\x16\n" +
	"\x12ESeasonType_Winter\x10\x03B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ESeasonType_proto_rawDescOnce sync.Once
	file_ESeasonType_proto_rawDescData []byte
)

func file_ESeasonType_proto_rawDescGZIP() []byte {
	file_ESeasonType_proto_rawDescOnce.Do(func() {
		file_ESeasonType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ESeasonType_proto_rawDesc), len(file_ESeasonType_proto_rawDesc)))
	})
	return file_ESeasonType_proto_rawDescData
}

var file_ESeasonType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ESeasonType_proto_goTypes = []any{
	(ESeasonType)(0), // 0: proto.ESeasonType
}
var file_ESeasonType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ESeasonType_proto_init() }
func file_ESeasonType_proto_init() {
	if File_ESeasonType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ESeasonType_proto_rawDesc), len(file_ESeasonType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ESeasonType_proto_goTypes,
		DependencyIndexes: file_ESeasonType_proto_depIdxs,
		EnumInfos:         file_ESeasonType_proto_enumTypes,
	}.Build()
	File_ESeasonType_proto = out.File
	file_ESeasonType_proto_goTypes = nil
	file_ESeasonType_proto_depIdxs = nil
}
