// Extracted enum EShopType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EShopType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EShopType int32

const (
	EShopType_EShopType_SingleShop   EShopType = 0
	EShopType_EShopType_MultiShop    EShopType = 1
	EShopType_EShopType_RechargeShop EShopType = 2
	EShopType_EShopType_MoonShop     EShopType = 3
	EShopType_EShopType_ActivityGift EShopType = 4
	EShopType_EShopType_BattlePass   EShopType = 5
	EShopType_EShopType_Recommending EShopType = 6
	EShopType_EShopType_CharacterBp  EShopType = 7
	EShopType_EShopType_ConvertShop  EShopType = 8
)

// Enum value maps for EShopType.
var (
	EShopType_name = map[int32]string{
		0: "EShopType_SingleShop",
		1: "EShopType_MultiShop",
		2: "EShopType_RechargeShop",
		3: "EShopType_MoonShop",
		4: "EShopType_ActivityGift",
		5: "EShopType_BattlePass",
		6: "EShopType_Recommending",
		7: "EShopType_CharacterBp",
		8: "EShopType_ConvertShop",
	}
	EShopType_value = map[string]int32{
		"EShopType_SingleShop":   0,
		"EShopType_MultiShop":    1,
		"EShopType_RechargeShop": 2,
		"EShopType_MoonShop":     3,
		"EShopType_ActivityGift": 4,
		"EShopType_BattlePass":   5,
		"EShopType_Recommending": 6,
		"EShopType_CharacterBp":  7,
		"EShopType_ConvertShop":  8,
	}
)

func (x EShopType) Enum() *EShopType {
	p := new(EShopType)
	*p = x
	return p
}

func (x EShopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EShopType) Descriptor() protoreflect.EnumDescriptor {
	return file_EShopType_proto_enumTypes[0].Descriptor()
}

func (EShopType) Type() protoreflect.EnumType {
	return &file_EShopType_proto_enumTypes[0]
}

func (x EShopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EShopType.Descriptor instead.
func (EShopType) EnumDescriptor() ([]byte, []int) {
	return file_EShopType_proto_rawDescGZIP(), []int{0}
}

var File_EShopType_proto protoreflect.FileDescriptor

const file_EShopType_proto_rawDesc = "" +
	"\n" +
	"\x0fEShopType.proto\x12\x05proto*\xfa\x01\n" +
	"\tEShopType\x12\x18\n" +
	"\x14EShopType_SingleShop\x10\x00\x12\x17\n" +
	"\x13EShopType_MultiShop\x10\x01\x12\x1a\n" +
	"\x16EShopType_RechargeShop\x10\x02\x12\x16\n" +
	"\x12EShopType_MoonShop\x10\x03\x12\x1a\n" +
	"\x16EShopType_ActivityGift\x10\x04\x12\x18\n" +
	"\x14EShopType_BattlePass\x10\x05\x12\x1a\n" +
	"\x16EShopType_Recommending\x10\x06\x12\x19\n" +
	"\x15EShopType_CharacterBp\x10\a\x12\x19\n" +
	"\x15EShopType_ConvertShop\x10\bB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_EShopType_proto_rawDescOnce sync.Once
	file_EShopType_proto_rawDescData []byte
)

func file_EShopType_proto_rawDescGZIP() []byte {
	file_EShopType_proto_rawDescOnce.Do(func() {
		file_EShopType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EShopType_proto_rawDesc), len(file_EShopType_proto_rawDesc)))
	})
	return file_EShopType_proto_rawDescData
}

var file_EShopType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EShopType_proto_goTypes = []any{
	(EShopType)(0), // 0: proto.EShopType
}
var file_EShopType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EShopType_proto_init() }
func file_EShopType_proto_init() {
	if File_EShopType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EShopType_proto_rawDesc), len(file_EShopType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EShopType_proto_goTypes,
		DependencyIndexes: file_EShopType_proto_depIdxs,
		EnumInfos:         file_EShopType_proto_enumTypes,
	}.Build()
	File_EShopType_proto = out.File
	file_EShopType_proto_goTypes = nil
	file_EShopType_proto_depIdxs = nil
}
