// Extracted enum ETalkCondition
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ETalkCondition.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ETalkCondition int32

const (
	ETalkCondition_ETalkCondition_CheckQuest ETalkCondition = 0
	ETalkCondition_ETalkCondition_CheckItem  ETalkCondition = 1
	ETalkCondition_ETalkCondition_None       ETalkCondition = 2
)

// Enum value maps for ETalkCondition.
var (
	ETalkCondition_name = map[int32]string{
		0: "ETalkCondition_CheckQuest",
		1: "ETalkCondition_CheckItem",
		2: "ETalkCondition_None",
	}
	ETalkCondition_value = map[string]int32{
		"ETalkCondition_CheckQuest": 0,
		"ETalkCondition_CheckItem":  1,
		"ETalkCondition_None":       2,
	}
)

func (x ETalkCondition) Enum() *ETalkCondition {
	p := new(ETalkCondition)
	*p = x
	return p
}

func (x ETalkCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ETalkCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_ETalkCondition_proto_enumTypes[0].Descriptor()
}

func (ETalkCondition) Type() protoreflect.EnumType {
	return &file_ETalkCondition_proto_enumTypes[0]
}

func (x ETalkCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ETalkCondition.Descriptor instead.
func (ETalkCondition) EnumDescriptor() ([]byte, []int) {
	return file_ETalkCondition_proto_rawDescGZIP(), []int{0}
}

var File_ETalkCondition_proto protoreflect.FileDescriptor

const file_ETalkCondition_proto_rawDesc = "" +
	"\n" +
	"\x14ETalkCondition.proto\x12\x05proto*f\n" +
	"\x0eETalkCondition\x12\x1d\n" +
	"\x19ETalkCondition_CheckQuest\x10\x00\x12\x1c\n" +
	"\x18ETalkCondition_CheckItem\x10\x01\x12\x17\n" +
	"\x13ETalkCondition_None\x10\x02B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ETalkCondition_proto_rawDescOnce sync.Once
	file_ETalkCondition_proto_rawDescData []byte
)

func file_ETalkCondition_proto_rawDescGZIP() []byte {
	file_ETalkCondition_proto_rawDescOnce.Do(func() {
		file_ETalkCondition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ETalkCondition_proto_rawDesc), len(file_ETalkCondition_proto_rawDesc)))
	})
	return file_ETalkCondition_proto_rawDescData
}

var file_ETalkCondition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ETalkCondition_proto_goTypes = []any{
	(ETalkCondition)(0), // 0: proto.ETalkCondition
}
var file_ETalkCondition_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ETalkCondition_proto_init() }
func file_ETalkCondition_proto_init() {
	if File_ETalkCondition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ETalkCondition_proto_rawDesc), len(file_ETalkCondition_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ETalkCondition_proto_goTypes,
		DependencyIndexes: file_ETalkCondition_proto_depIdxs,
		EnumInfos:         file_ETalkCondition_proto_enumTypes,
	}.Build()
	File_ETalkCondition_proto = out.File
	file_ETalkCondition_proto_goTypes = nil
	file_ETalkCondition_proto_depIdxs = nil
}
