// Extracted enum ETurntableType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ETurntableType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ETurntableType int32

const (
	ETurntableType_ETurntableType_None          ETurntableType = 0
	ETurntableType_ETurntableType_InstantWinAll ETurntableType = 1
)

// Enum value maps for ETurntableType.
var (
	ETurntableType_name = map[int32]string{
		0: "ETurntableType_None",
		1: "ETurntableType_InstantWinAll",
	}
	ETurntableType_value = map[string]int32{
		"ETurntableType_None":          0,
		"ETurntableType_InstantWinAll": 1,
	}
)

func (x ETurntableType) Enum() *ETurntableType {
	p := new(ETurntableType)
	*p = x
	return p
}

func (x ETurntableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ETurntableType) Descriptor() protoreflect.EnumDescriptor {
	return file_ETurntableType_proto_enumTypes[0].Descriptor()
}

func (ETurntableType) Type() protoreflect.EnumType {
	return &file_ETurntableType_proto_enumTypes[0]
}

func (x ETurntableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ETurntableType.Descriptor instead.
func (ETurntableType) EnumDescriptor() ([]byte, []int) {
	return file_ETurntableType_proto_rawDescGZIP(), []int{0}
}

var File_ETurntableType_proto protoreflect.FileDescriptor

const file_ETurntableType_proto_rawDesc = "" +
	"\n" +
	"\x14ETurntableType.proto\x12\x05proto*K\n" +
	"\x0eETurntableType\x12\x17\n" +
	"\x13ETurntableType_None\x10\x00\x12 \n" +
	"\x1cETurntableType_InstantWinAll\x10\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ETurntableType_proto_rawDescOnce sync.Once
	file_ETurntableType_proto_rawDescData []byte
)

func file_ETurntableType_proto_rawDescGZIP() []byte {
	file_ETurntableType_proto_rawDescOnce.Do(func() {
		file_ETurntableType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ETurntableType_proto_rawDesc), len(file_ETurntableType_proto_rawDesc)))
	})
	return file_ETurntableType_proto_rawDescData
}

var file_ETurntableType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ETurntableType_proto_goTypes = []any{
	(ETurntableType)(0), // 0: proto.ETurntableType
}
var file_ETurntableType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ETurntableType_proto_init() }
func file_ETurntableType_proto_init() {
	if File_ETurntableType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ETurntableType_proto_rawDesc), len(file_ETurntableType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ETurntableType_proto_goTypes,
		DependencyIndexes: file_ETurntableType_proto_depIdxs,
		EnumInfos:         file_ETurntableType_proto_enumTypes,
	}.Build()
	File_ETurntableType_proto = out.File
	file_ETurntableType_proto_goTypes = nil
	file_ETurntableType_proto_depIdxs = nil
}
