// Extracted enum EWeaponType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EWeaponType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EWeaponType int32

const (
	EWeaponType_EWeaponType_TwoHandAxe       EWeaponType = 0
	EWeaponType_EWeaponType_TwoHandSword     EWeaponType = 1
	EWeaponType_EWeaponType_Ball             EWeaponType = 2
	EWeaponType_EWeaponType_TwoHanded        EWeaponType = 3
	EWeaponType_EWeaponType_CollectionGloves EWeaponType = 4
	EWeaponType_EWeaponType_LoggingAxe       EWeaponType = 5
	EWeaponType_EWeaponType_MiningHammer     EWeaponType = 6
	EWeaponType_EWeaponType_InsectNet        EWeaponType = 7
	EWeaponType_EWeaponType_WaterBottle      EWeaponType = 8
	EWeaponType_EWeaponType_Bow              EWeaponType = 9
	EWeaponType_EWeaponType_Spear            EWeaponType = 10
	EWeaponType_EWeaponType_Gloves           EWeaponType = 11
	EWeaponType_EWeaponType_Longbow          EWeaponType = 12
	EWeaponType_EWeaponType_Sword            EWeaponType = 13
	EWeaponType_EWeaponType_Staff            EWeaponType = 14
	EWeaponType_EWeaponType_All              EWeaponType = 15
	EWeaponType_EWeaponType_Rifle            EWeaponType = 16
	EWeaponType_EWeaponType_Card             EWeaponType = 17
	EWeaponType_EWeaponType_FishingRod       EWeaponType = 18
	EWeaponType_EWeaponType_Unarmed          EWeaponType = 19
	EWeaponType_EWeaponType_MinigameWeapon   EWeaponType = 20
	EWeaponType_EWeaponType_Vehicle          EWeaponType = 21
)

// Enum value maps for EWeaponType.
var (
	EWeaponType_name = map[int32]string{
		0:  "EWeaponType_TwoHandAxe",
		1:  "EWeaponType_TwoHandSword",
		2:  "EWeaponType_Ball",
		3:  "EWeaponType_TwoHanded",
		4:  "EWeaponType_CollectionGloves",
		5:  "EWeaponType_LoggingAxe",
		6:  "EWeaponType_MiningHammer",
		7:  "EWeaponType_InsectNet",
		8:  "EWeaponType_WaterBottle",
		9:  "EWeaponType_Bow",
		10: "EWeaponType_Spear",
		11: "EWeaponType_Gloves",
		12: "EWeaponType_Longbow",
		13: "EWeaponType_Sword",
		14: "EWeaponType_Staff",
		15: "EWeaponType_All",
		16: "EWeaponType_Rifle",
		17: "EWeaponType_Card",
		18: "EWeaponType_FishingRod",
		19: "EWeaponType_Unarmed",
		20: "EWeaponType_MinigameWeapon",
		21: "EWeaponType_Vehicle",
	}
	EWeaponType_value = map[string]int32{
		"EWeaponType_TwoHandAxe":       0,
		"EWeaponType_TwoHandSword":     1,
		"EWeaponType_Ball":             2,
		"EWeaponType_TwoHanded":        3,
		"EWeaponType_CollectionGloves": 4,
		"EWeaponType_LoggingAxe":       5,
		"EWeaponType_MiningHammer":     6,
		"EWeaponType_InsectNet":        7,
		"EWeaponType_WaterBottle":      8,
		"EWeaponType_Bow":              9,
		"EWeaponType_Spear":            10,
		"EWeaponType_Gloves":           11,
		"EWeaponType_Longbow":          12,
		"EWeaponType_Sword":            13,
		"EWeaponType_Staff":            14,
		"EWeaponType_All":              15,
		"EWeaponType_Rifle":            16,
		"EWeaponType_Card":             17,
		"EWeaponType_FishingRod":       18,
		"EWeaponType_Unarmed":          19,
		"EWeaponType_MinigameWeapon":   20,
		"EWeaponType_Vehicle":          21,
	}
)

func (x EWeaponType) Enum() *EWeaponType {
	p := new(EWeaponType)
	*p = x
	return p
}

func (x EWeaponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EWeaponType) Descriptor() protoreflect.EnumDescriptor {
	return file_EWeaponType_proto_enumTypes[0].Descriptor()
}

func (EWeaponType) Type() protoreflect.EnumType {
	return &file_EWeaponType_proto_enumTypes[0]
}

func (x EWeaponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EWeaponType.Descriptor instead.
func (EWeaponType) EnumDescriptor() ([]byte, []int) {
	return file_EWeaponType_proto_rawDescGZIP(), []int{0}
}

var File_EWeaponType_proto protoreflect.FileDescriptor

const file_EWeaponType_proto_rawDesc = "" +
	"\n" +
	"\x11EWeaponType.proto\x12\x05proto*\xc7\x04\n" +
	"\vEWeaponType\x12\x1a\n" +
	"\x16EWeaponType_TwoHandAxe\x10\x00\x12\x1c\n" +
	"\x18EWeaponType_TwoHandSword\x10\x01\x12\x14\n" +
	"\x10EWeaponType_Ball\x10\x02\x12\x19\n" +
	"\x15EWeaponType_TwoHanded\x10\x03\x12 \n" +
	"\x1cEWeaponType_CollectionGloves\x10\x04\x12\x1a\n" +
	"\x16EWeaponType_LoggingAxe\x10\x05\x12\x1c\n" +
	"\x18EWeaponType_MiningHammer\x10\x06\x12\x19\n" +
	"\x15EWeaponType_InsectNet\x10\a\x12\x1b\n" +
	"\x17EWeaponType_WaterBottle\x10\b\x12\x13\n" +
	"\x0fEWeaponType_Bow\x10\t\x12\x15\n" +
	"\x11EWeaponType_Spear\x10\n" +
	"\x12\x16\n" +
	"\x12EWeaponType_Gloves\x10\v\x12\x17\n" +
	"\x13EWeaponType_Longbow\x10\f\x12\x15\n" +
	"\x11EWeaponType_Sword\x10\r\x12\x15\n" +
	"\x11EWeaponType_Staff\x10\x0e\x12\x13\n" +
	"\x0fEWeaponType_All\x10\x0f\x12\x15\n" +
	"\x11EWeaponType_Rifle\x10\x10\x12\x14\n" +
	"\x10EWeaponType_Card\x10\x11\x12\x1a\n" +
	"\x16EWeaponType_FishingRod\x10\x12\x12\x17\n" +
	"\x13EWeaponType_Unarmed\x10\x13\x12\x1e\n" +
	"\x1aEWeaponType_MinigameWeapon\x10\x14\x12\x17\n" +
	"\x13EWeaponType_Vehicle\x10\x15B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_EWeaponType_proto_rawDescOnce sync.Once
	file_EWeaponType_proto_rawDescData []byte
)

func file_EWeaponType_proto_rawDescGZIP() []byte {
	file_EWeaponType_proto_rawDescOnce.Do(func() {
		file_EWeaponType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EWeaponType_proto_rawDesc), len(file_EWeaponType_proto_rawDesc)))
	})
	return file_EWeaponType_proto_rawDescData
}

var file_EWeaponType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EWeaponType_proto_goTypes = []any{
	(EWeaponType)(0), // 0: proto.EWeaponType
}
var file_EWeaponType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EWeaponType_proto_init() }
func file_EWeaponType_proto_init() {
	if File_EWeaponType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EWeaponType_proto_rawDesc), len(file_EWeaponType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EWeaponType_proto_goTypes,
		DependencyIndexes: file_EWeaponType_proto_depIdxs,
		EnumInfos:         file_EWeaponType_proto_enumTypes,
	}.Build()
	File_EWeaponType_proto = out.File
	file_EWeaponType_proto_goTypes = nil
	file_EWeaponType_proto_depIdxs = nil
}
