// Extracted message FlagBattleData
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: FlagBattleData.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagBattleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      uint32                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	State         BattleState            `protobuf:"varint,2,opt,name=state,proto3,enum=proto.BattleState" json:"state,omitempty"`
	Type          EMissionType           `protobuf:"varint,3,opt,name=type,proto3,enum=proto.EMissionType" json:"type,omitempty"`
	FinishTimes   uint32                 `protobuf:"varint,4,opt,name=finish_times,json=finishTimes,proto3" json:"finish_times,omitempty"`
	VoiceId       uint32                 `protobuf:"varint,5,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagBattleData) Reset() {
	*x = FlagBattleData{}
	mi := &file_FlagBattleData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagBattleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagBattleData) ProtoMessage() {}

func (x *FlagBattleData) ProtoReflect() protoreflect.Message {
	mi := &file_FlagBattleData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagBattleData.ProtoReflect.Descriptor instead.
func (*FlagBattleData) Descriptor() ([]byte, []int) {
	return file_FlagBattleData_proto_rawDescGZIP(), []int{0}
}

func (x *FlagBattleData) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *FlagBattleData) GetState() BattleState {
	if x != nil {
		return x.State
	}
	return BattleState_BattleState_Start
}

func (x *FlagBattleData) GetType() EMissionType {
	if x != nil {
		return x.Type
	}
	return EMissionType_EMissionType_NormalBattle
}

func (x *FlagBattleData) GetFinishTimes() uint32 {
	if x != nil {
		return x.FinishTimes
	}
	return 0
}

func (x *FlagBattleData) GetVoiceId() uint32 {
	if x != nil {
		return x.VoiceId
	}
	return 0
}

var File_FlagBattleData_proto protoreflect.FileDescriptor

const file_FlagBattleData_proto_rawDesc = "" +
	"\n" +
	"\x14FlagBattleData.proto\x12\x05proto\x1a\x11BattleState.proto\x1a\x12EMissionType.proto\"\xbe\x01\n" +
	"\x0eFlagBattleData\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\rR\bbattleId\x12(\n" +
	"\x05state\x18\x02 \x01(\x0e2\x12.proto.BattleStateR\x05state\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.proto.EMissionTypeR\x04type\x12!\n" +
	"\ffinish_times\x18\x04 \x01(\rR\vfinishTimes\x12\x19\n" +
	"\bvoice_id\x18\x05 \x01(\rR\avoiceIdB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_FlagBattleData_proto_rawDescOnce sync.Once
	file_FlagBattleData_proto_rawDescData []byte
)

func file_FlagBattleData_proto_rawDescGZIP() []byte {
	file_FlagBattleData_proto_rawDescOnce.Do(func() {
		file_FlagBattleData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_FlagBattleData_proto_rawDesc), len(file_FlagBattleData_proto_rawDesc)))
	})
	return file_FlagBattleData_proto_rawDescData
}

var file_FlagBattleData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FlagBattleData_proto_goTypes = []any{
	(*FlagBattleData)(nil), // 0: proto.FlagBattleData
	(BattleState)(0),       // 1: proto.BattleState
	(EMissionType)(0),      // 2: proto.EMissionType
}
var file_FlagBattleData_proto_depIdxs = []int32{
	1, // 0: proto.FlagBattleData.state:type_name -> proto.BattleState
	2, // 1: proto.FlagBattleData.type:type_name -> proto.EMissionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_FlagBattleData_proto_init() }
func file_FlagBattleData_proto_init() {
	if File_FlagBattleData_proto != nil {
		return
	}
	file_BattleState_proto_init()
	file_EMissionType_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_FlagBattleData_proto_rawDesc), len(file_FlagBattleData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FlagBattleData_proto_goTypes,
		DependencyIndexes: file_FlagBattleData_proto_depIdxs,
		MessageInfos:      file_FlagBattleData_proto_msgTypes,
	}.Build()
	File_FlagBattleData_proto = out.File
	file_FlagBattleData_proto_goTypes = nil
	file_FlagBattleData_proto_depIdxs = nil
}
