// Extracted message ForbiddenInfo
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ForbiddenInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForbiddenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForbiddenType ForbiddenType          `protobuf:"varint,1,opt,name=forbidden_type,json=forbiddenType,proto3,enum=proto.ForbiddenType" json:"forbidden_type,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForbiddenInfo) Reset() {
	*x = ForbiddenInfo{}
	mi := &file_ForbiddenInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForbiddenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForbiddenInfo) ProtoMessage() {}

func (x *ForbiddenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ForbiddenInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForbiddenInfo.ProtoReflect.Descriptor instead.
func (*ForbiddenInfo) Descriptor() ([]byte, []int) {
	return file_ForbiddenInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ForbiddenInfo) GetForbiddenType() ForbiddenType {
	if x != nil {
		return x.ForbiddenType
	}
	return ForbiddenType_ForbiddenType_Muted
}

func (x *ForbiddenInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ForbiddenInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_ForbiddenInfo_proto protoreflect.FileDescriptor

const file_ForbiddenInfo_proto_rawDesc = "" +
	"\n" +
	"\x13ForbiddenInfo.proto\x12\x05proto\x1a\x13ForbiddenType.proto\"\x7f\n" +
	"\rForbiddenInfo\x12;\n" +
	"\x0eforbidden_type\x18\x01 \x01(\x0e2\x14.proto.ForbiddenTypeR\rforbiddenType\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ForbiddenInfo_proto_rawDescOnce sync.Once
	file_ForbiddenInfo_proto_rawDescData []byte
)

func file_ForbiddenInfo_proto_rawDescGZIP() []byte {
	file_ForbiddenInfo_proto_rawDescOnce.Do(func() {
		file_ForbiddenInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ForbiddenInfo_proto_rawDesc), len(file_ForbiddenInfo_proto_rawDesc)))
	})
	return file_ForbiddenInfo_proto_rawDescData
}

var file_ForbiddenInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ForbiddenInfo_proto_goTypes = []any{
	(*ForbiddenInfo)(nil), // 0: proto.ForbiddenInfo
	(ForbiddenType)(0),    // 1: proto.ForbiddenType
}
var file_ForbiddenInfo_proto_depIdxs = []int32{
	1, // 0: proto.ForbiddenInfo.forbidden_type:type_name -> proto.ForbiddenType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ForbiddenInfo_proto_init() }
func file_ForbiddenInfo_proto_init() {
	if File_ForbiddenInfo_proto != nil {
		return
	}
	file_ForbiddenType_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ForbiddenInfo_proto_rawDesc), len(file_ForbiddenInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ForbiddenInfo_proto_goTypes,
		DependencyIndexes: file_ForbiddenInfo_proto_depIdxs,
		MessageInfos:      file_ForbiddenInfo_proto_msgTypes,
	}.Build()
	File_ForbiddenInfo_proto = out.File
	file_ForbiddenInfo_proto_goTypes = nil
	file_ForbiddenInfo_proto_depIdxs = nil
}
