// Extracted message GemDuelPaySendGoodsNotice
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: GemDuelPaySendGoodsNotice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GemDuelPaySendGoodsNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	ShopId        uint32                 `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Grids         *GemDuelShopGrid       `protobuf:"bytes,3,opt,name=grids,proto3" json:"grids,omitempty"`
	OrderId       string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*GemDuelItem         `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GemDuelPaySendGoodsNotice) Reset() {
	*x = GemDuelPaySendGoodsNotice{}
	mi := &file_GemDuelPaySendGoodsNotice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GemDuelPaySendGoodsNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GemDuelPaySendGoodsNotice) ProtoMessage() {}

func (x *GemDuelPaySendGoodsNotice) ProtoReflect() protoreflect.Message {
	mi := &file_GemDuelPaySendGoodsNotice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GemDuelPaySendGoodsNotice.ProtoReflect.Descriptor instead.
func (*GemDuelPaySendGoodsNotice) Descriptor() ([]byte, []int) {
	return file_GemDuelPaySendGoodsNotice_proto_rawDescGZIP(), []int{0}
}

func (x *GemDuelPaySendGoodsNotice) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *GemDuelPaySendGoodsNotice) GetShopId() uint32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *GemDuelPaySendGoodsNotice) GetGrids() *GemDuelShopGrid {
	if x != nil {
		return x.Grids
	}
	return nil
}

func (x *GemDuelPaySendGoodsNotice) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GemDuelPaySendGoodsNotice) GetItems() []*GemDuelItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_GemDuelPaySendGoodsNotice_proto protoreflect.FileDescriptor

const file_GemDuelPaySendGoodsNotice_proto_rawDesc = "" +
	"\n" +
	"\x1fGemDuelPaySendGoodsNotice.proto\x12\x05proto\x1a\x11GemDuelItem.proto\x1a\x15GemDuelShopGrid.proto\x1a\x10StatusCode.proto\"\xd2\x01\n" +
	"\x19GemDuelPaySendGoodsNotice\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\rR\x06shopId\x12,\n" +
	"\x05grids\x18\x03 \x01(\v2\x16.proto.GemDuelShopGridR\x05grids\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12(\n" +
	"\x05items\x18\x06 \x03(\v2\x12.proto.GemDuelItemR\x05itemsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_GemDuelPaySendGoodsNotice_proto_rawDescOnce sync.Once
	file_GemDuelPaySendGoodsNotice_proto_rawDescData []byte
)

func file_GemDuelPaySendGoodsNotice_proto_rawDescGZIP() []byte {
	file_GemDuelPaySendGoodsNotice_proto_rawDescOnce.Do(func() {
		file_GemDuelPaySendGoodsNotice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GemDuelPaySendGoodsNotice_proto_rawDesc), len(file_GemDuelPaySendGoodsNotice_proto_rawDesc)))
	})
	return file_GemDuelPaySendGoodsNotice_proto_rawDescData
}

var file_GemDuelPaySendGoodsNotice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GemDuelPaySendGoodsNotice_proto_goTypes = []any{
	(*GemDuelPaySendGoodsNotice)(nil), // 0: proto.GemDuelPaySendGoodsNotice
	(StatusCode)(0),                   // 1: proto.StatusCode
	(*GemDuelShopGrid)(nil),           // 2: proto.GemDuelShopGrid
	(*GemDuelItem)(nil),               // 3: proto.GemDuelItem
}
var file_GemDuelPaySendGoodsNotice_proto_depIdxs = []int32{
	1, // 0: proto.GemDuelPaySendGoodsNotice.status:type_name -> proto.StatusCode
	2, // 1: proto.GemDuelPaySendGoodsNotice.grids:type_name -> proto.GemDuelShopGrid
	3, // 2: proto.GemDuelPaySendGoodsNotice.items:type_name -> proto.GemDuelItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_GemDuelPaySendGoodsNotice_proto_init() }
func file_GemDuelPaySendGoodsNotice_proto_init() {
	if File_GemDuelPaySendGoodsNotice_proto != nil {
		return
	}
	file_GemDuelItem_proto_init()
	file_GemDuelShopGrid_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GemDuelPaySendGoodsNotice_proto_rawDesc), len(file_GemDuelPaySendGoodsNotice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GemDuelPaySendGoodsNotice_proto_goTypes,
		DependencyIndexes: file_GemDuelPaySendGoodsNotice_proto_depIdxs,
		MessageInfos:      file_GemDuelPaySendGoodsNotice_proto_msgTypes,
	}.Build()
	File_GemDuelPaySendGoodsNotice_proto = out.File
	file_GemDuelPaySendGoodsNotice_proto_goTypes = nil
	file_GemDuelPaySendGoodsNotice_proto_depIdxs = nil
}
