// Extracted enum GemDuelActionType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: GemDuelActionType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GemDuelActionType int32

const (
	GemDuelActionType_GemDuelActionType_None              GemDuelActionType = 0
	GemDuelActionType_GemDuelActionType_Move              GemDuelActionType = 1
	GemDuelActionType_GemDuelActionType_Clear             GemDuelActionType = 2
	GemDuelActionType_GemDuelActionType_CastSkill         GemDuelActionType = 3
	GemDuelActionType_GemDuelActionType_Round             GemDuelActionType = 4
	GemDuelActionType_GemDuelActionType_Spawn             GemDuelActionType = 5
	GemDuelActionType_GemDuelActionType_Destroy           GemDuelActionType = 6
	GemDuelActionType_GemDuelActionType_Attack            GemDuelActionType = 7
	GemDuelActionType_GemDuelActionType_GetEnergy         GemDuelActionType = 8
	GemDuelActionType_GemDuelActionType_Win               GemDuelActionType = 9
	GemDuelActionType_GemDuelActionType_ResetGrids        GemDuelActionType = 10
	GemDuelActionType_GemDuelActionType_Recommend         GemDuelActionType = 11
	GemDuelActionType_GemDuelActionType_HealthChange      GemDuelActionType = 12
	GemDuelActionType_GemDuelActionType_ChangeGemType     GemDuelActionType = 13
	GemDuelActionType_GemDuelActionType_ChangeHealthMax   GemDuelActionType = 14
	GemDuelActionType_GemDuelActionType_PassiveSkill      GemDuelActionType = 15
	GemDuelActionType_GemDuelActionType_ChangeGemDefRatio GemDuelActionType = 16
	GemDuelActionType_GemDuelActionType_ShieldChange      GemDuelActionType = 17
	GemDuelActionType_GemDuelActionType_AddBuff           GemDuelActionType = 18
	GemDuelActionType_GemDuelActionType_DelBuff           GemDuelActionType = 19
	GemDuelActionType_GemDuelActionType_AddCharacter      GemDuelActionType = 20
	GemDuelActionType_GemDuelActionType_EnergyChange      GemDuelActionType = 21
	GemDuelActionType_GemDuelActionType_BuffChangeNum     GemDuelActionType = 22
)

// Enum value maps for GemDuelActionType.
var (
	GemDuelActionType_name = map[int32]string{
		0:  "GemDuelActionType_None",
		1:  "GemDuelActionType_Move",
		2:  "GemDuelActionType_Clear",
		3:  "GemDuelActionType_CastSkill",
		4:  "GemDuelActionType_Round",
		5:  "GemDuelActionType_Spawn",
		6:  "GemDuelActionType_Destroy",
		7:  "GemDuelActionType_Attack",
		8:  "GemDuelActionType_GetEnergy",
		9:  "GemDuelActionType_Win",
		10: "GemDuelActionType_ResetGrids",
		11: "GemDuelActionType_Recommend",
		12: "GemDuelActionType_HealthChange",
		13: "GemDuelActionType_ChangeGemType",
		14: "GemDuelActionType_ChangeHealthMax",
		15: "GemDuelActionType_PassiveSkill",
		16: "GemDuelActionType_ChangeGemDefRatio",
		17: "GemDuelActionType_ShieldChange",
		18: "GemDuelActionType_AddBuff",
		19: "GemDuelActionType_DelBuff",
		20: "GemDuelActionType_AddCharacter",
		21: "GemDuelActionType_EnergyChange",
		22: "GemDuelActionType_BuffChangeNum",
	}
	GemDuelActionType_value = map[string]int32{
		"GemDuelActionType_None":              0,
		"GemDuelActionType_Move":              1,
		"GemDuelActionType_Clear":             2,
		"GemDuelActionType_CastSkill":         3,
		"GemDuelActionType_Round":             4,
		"GemDuelActionType_Spawn":             5,
		"GemDuelActionType_Destroy":           6,
		"GemDuelActionType_Attack":            7,
		"GemDuelActionType_GetEnergy":         8,
		"GemDuelActionType_Win":               9,
		"GemDuelActionType_ResetGrids":        10,
		"GemDuelActionType_Recommend":         11,
		"GemDuelActionType_HealthChange":      12,
		"GemDuelActionType_ChangeGemType":     13,
		"GemDuelActionType_ChangeHealthMax":   14,
		"GemDuelActionType_PassiveSkill":      15,
		"GemDuelActionType_ChangeGemDefRatio": 16,
		"GemDuelActionType_ShieldChange":      17,
		"GemDuelActionType_AddBuff":           18,
		"GemDuelActionType_DelBuff":           19,
		"GemDuelActionType_AddCharacter":      20,
		"GemDuelActionType_EnergyChange":      21,
		"GemDuelActionType_BuffChangeNum":     22,
	}
)

func (x GemDuelActionType) Enum() *GemDuelActionType {
	p := new(GemDuelActionType)
	*p = x
	return p
}

func (x GemDuelActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GemDuelActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_GemDuelActionType_proto_enumTypes[0].Descriptor()
}

func (GemDuelActionType) Type() protoreflect.EnumType {
	return &file_GemDuelActionType_proto_enumTypes[0]
}

func (x GemDuelActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GemDuelActionType.Descriptor instead.
func (GemDuelActionType) EnumDescriptor() ([]byte, []int) {
	return file_GemDuelActionType_proto_rawDescGZIP(), []int{0}
}

var File_GemDuelActionType_proto protoreflect.FileDescriptor

const file_GemDuelActionType_proto_rawDesc = "" +
	"\n" +
	"\x17GemDuelActionType.proto\x12\x05proto*\x8b\x06\n" +
	"\x11GemDuelActionType\x12\x1a\n" +
	"\x16GemDuelActionType_None\x10\x00\x12\x1a\n" +
	"\x16GemDuelActionType_Move\x10\x01\x12\x1b\n" +
	"\x17GemDuelActionType_Clear\x10\x02\x12\x1f\n" +
	"\x1bGemDuelActionType_CastSkill\x10\x03\x12\x1b\n" +
	"\x17GemDuelActionType_Round\x10\x04\x12\x1b\n" +
	"\x17GemDuelActionType_Spawn\x10\x05\x12\x1d\n" +
	"\x19GemDuelActionType_Destroy\x10\x06\x12\x1c\n" +
	"\x18GemDuelActionType_Attack\x10\a\x12\x1f\n" +
	"\x1bGemDuelActionType_GetEnergy\x10\b\x12\x19\n" +
	"\x15GemDuelActionType_Win\x10\t\x12 \n" +
	"\x1cGemDuelActionType_ResetGrids\x10\n" +
	"\x12\x1f\n" +
	"\x1bGemDuelActionType_Recommend\x10\v\x12\"\n" +
	"\x1eGemDuelActionType_HealthChange\x10\f\x12#\n" +
	"\x1fGemDuelActionType_ChangeGemType\x10\r\x12%\n" +
	"!GemDuelActionType_ChangeHealthMax\x10\x0e\x12\"\n" +
	"\x1eGemDuelActionType_PassiveSkill\x10\x0f\x12'\n" +
	"#GemDuelActionType_ChangeGemDefRatio\x10\x10\x12\"\n" +
	"\x1eGemDuelActionType_ShieldChange\x10\x11\x12\x1d\n" +
	"\x19GemDuelActionType_AddBuff\x10\x12\x12\x1d\n" +
	"\x19GemDuelActionType_DelBuff\x10\x13\x12\"\n" +
	"\x1eGemDuelActionType_AddCharacter\x10\x14\x12\"\n" +
	"\x1eGemDuelActionType_EnergyChange\x10\x15\x12#\n" +
	"\x1fGemDuelActionType_BuffChangeNum\x10\x16B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_GemDuelActionType_proto_rawDescOnce sync.Once
	file_GemDuelActionType_proto_rawDescData []byte
)

func file_GemDuelActionType_proto_rawDescGZIP() []byte {
	file_GemDuelActionType_proto_rawDescOnce.Do(func() {
		file_GemDuelActionType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GemDuelActionType_proto_rawDesc), len(file_GemDuelActionType_proto_rawDesc)))
	})
	return file_GemDuelActionType_proto_rawDescData
}

var file_GemDuelActionType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_GemDuelActionType_proto_goTypes = []any{
	(GemDuelActionType)(0), // 0: proto.GemDuelActionType
}
var file_GemDuelActionType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GemDuelActionType_proto_init() }
func file_GemDuelActionType_proto_init() {
	if File_GemDuelActionType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GemDuelActionType_proto_rawDesc), len(file_GemDuelActionType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GemDuelActionType_proto_goTypes,
		DependencyIndexes: file_GemDuelActionType_proto_depIdxs,
		EnumInfos:         file_GemDuelActionType_proto_enumTypes,
	}.Build()
	File_GemDuelActionType_proto = out.File
	file_GemDuelActionType_proto_goTypes = nil
	file_GemDuelActionType_proto_depIdxs = nil
}
