// Extracted message GemDuelBattlePassBuyExpReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: GemDuelBattlePassBuyExpReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GemDuelBattlePassBuyExpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattlePassId  uint32                 `protobuf:"varint,2,opt,name=battle_pass_id,json=battlePassId,proto3" json:"battle_pass_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GemDuelBattlePassBuyExpReq) Reset() {
	*x = GemDuelBattlePassBuyExpReq{}
	mi := &file_GemDuelBattlePassBuyExpReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GemDuelBattlePassBuyExpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GemDuelBattlePassBuyExpReq) ProtoMessage() {}

func (x *GemDuelBattlePassBuyExpReq) ProtoReflect() protoreflect.Message {
	mi := &file_GemDuelBattlePassBuyExpReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GemDuelBattlePassBuyExpReq.ProtoReflect.Descriptor instead.
func (*GemDuelBattlePassBuyExpReq) Descriptor() ([]byte, []int) {
	return file_GemDuelBattlePassBuyExpReq_proto_rawDescGZIP(), []int{0}
}

func (x *GemDuelBattlePassBuyExpReq) GetBattlePassId() uint32 {
	if x != nil {
		return x.BattlePassId
	}
	return 0
}

var File_GemDuelBattlePassBuyExpReq_proto protoreflect.FileDescriptor

const file_GemDuelBattlePassBuyExpReq_proto_rawDesc = "" +
	"\n" +
	" GemDuelBattlePassBuyExpReq.proto\x12\x05proto\"B\n" +
	"\x1aGemDuelBattlePassBuyExpReq\x12$\n" +
	"\x0ebattle_pass_id\x18\x02 \x01(\rR\fbattlePassIdB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_GemDuelBattlePassBuyExpReq_proto_rawDescOnce sync.Once
	file_GemDuelBattlePassBuyExpReq_proto_rawDescData []byte
)

func file_GemDuelBattlePassBuyExpReq_proto_rawDescGZIP() []byte {
	file_GemDuelBattlePassBuyExpReq_proto_rawDescOnce.Do(func() {
		file_GemDuelBattlePassBuyExpReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GemDuelBattlePassBuyExpReq_proto_rawDesc), len(file_GemDuelBattlePassBuyExpReq_proto_rawDesc)))
	})
	return file_GemDuelBattlePassBuyExpReq_proto_rawDescData
}

var file_GemDuelBattlePassBuyExpReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GemDuelBattlePassBuyExpReq_proto_goTypes = []any{
	(*GemDuelBattlePassBuyExpReq)(nil), // 0: proto.GemDuelBattlePassBuyExpReq
}
var file_GemDuelBattlePassBuyExpReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GemDuelBattlePassBuyExpReq_proto_init() }
func file_GemDuelBattlePassBuyExpReq_proto_init() {
	if File_GemDuelBattlePassBuyExpReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GemDuelBattlePassBuyExpReq_proto_rawDesc), len(file_GemDuelBattlePassBuyExpReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GemDuelBattlePassBuyExpReq_proto_goTypes,
		DependencyIndexes: file_GemDuelBattlePassBuyExpReq_proto_depIdxs,
		MessageInfos:      file_GemDuelBattlePassBuyExpReq_proto_msgTypes,
	}.Build()
	File_GemDuelBattlePassBuyExpReq_proto = out.File
	file_GemDuelBattlePassBuyExpReq_proto_goTypes = nil
	file_GemDuelBattlePassBuyExpReq_proto_depIdxs = nil
}
