// Extracted message GenericGameAReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: GenericGameAReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericGameAReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GenericMsgId  uint32                 `protobuf:"varint,1,opt,name=generic_msg_id,json=genericMsgId,proto3" json:"generic_msg_id,omitempty"`
	Params        []*CommonParam         `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	ParamMap      map[string]string      `protobuf:"bytes,3,rep,name=param_map,json=paramMap,proto3" json:"param_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericGameAReq) Reset() {
	*x = GenericGameAReq{}
	mi := &file_GenericGameAReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericGameAReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericGameAReq) ProtoMessage() {}

func (x *GenericGameAReq) ProtoReflect() protoreflect.Message {
	mi := &file_GenericGameAReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericGameAReq.ProtoReflect.Descriptor instead.
func (*GenericGameAReq) Descriptor() ([]byte, []int) {
	return file_GenericGameAReq_proto_rawDescGZIP(), []int{0}
}

func (x *GenericGameAReq) GetGenericMsgId() uint32 {
	if x != nil {
		return x.GenericMsgId
	}
	return 0
}

func (x *GenericGameAReq) GetParams() []*CommonParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenericGameAReq) GetParamMap() map[string]string {
	if x != nil {
		return x.ParamMap
	}
	return nil
}

var File_GenericGameAReq_proto protoreflect.FileDescriptor

const file_GenericGameAReq_proto_rawDesc = "" +
	"\n" +
	"\x15GenericGameAReq.proto\x12\x05proto\x1a\x11CommonParam.proto\"\xe3\x01\n" +
	"\x0fGenericGameAReq\x12$\n" +
	"\x0egeneric_msg_id\x18\x01 \x01(\rR\fgenericMsgId\x12*\n" +
	"\x06params\x18\x02 \x03(\v2\x12.proto.CommonParamR\x06params\x12A\n" +
	"\tparam_map\x18\x03 \x03(\v2$.proto.GenericGameAReq.ParamMapEntryR\bparamMap\x1a;\n" +
	"\rParamMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_GenericGameAReq_proto_rawDescOnce sync.Once
	file_GenericGameAReq_proto_rawDescData []byte
)

func file_GenericGameAReq_proto_rawDescGZIP() []byte {
	file_GenericGameAReq_proto_rawDescOnce.Do(func() {
		file_GenericGameAReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GenericGameAReq_proto_rawDesc), len(file_GenericGameAReq_proto_rawDesc)))
	})
	return file_GenericGameAReq_proto_rawDescData
}

var file_GenericGameAReq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GenericGameAReq_proto_goTypes = []any{
	(*GenericGameAReq)(nil), // 0: proto.GenericGameAReq
	nil,                     // 1: proto.GenericGameAReq.ParamMapEntry
	(*CommonParam)(nil),     // 2: proto.CommonParam
}
var file_GenericGameAReq_proto_depIdxs = []int32{
	2, // 0: proto.GenericGameAReq.params:type_name -> proto.CommonParam
	1, // 1: proto.GenericGameAReq.param_map:type_name -> proto.GenericGameAReq.ParamMapEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GenericGameAReq_proto_init() }
func file_GenericGameAReq_proto_init() {
	if File_GenericGameAReq_proto != nil {
		return
	}
	file_CommonParam_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GenericGameAReq_proto_rawDesc), len(file_GenericGameAReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GenericGameAReq_proto_goTypes,
		DependencyIndexes: file_GenericGameAReq_proto_depIdxs,
		MessageInfos:      file_GenericGameAReq_proto_msgTypes,
	}.Build()
	File_GenericGameAReq_proto = out.File
	file_GenericGameAReq_proto_goTypes = nil
	file_GenericGameAReq_proto_depIdxs = nil
}
