// Extracted message IntervalJoinReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: IntervalJoinReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntervalJoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      uint32                 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	IntervalParam string                 `protobuf:"bytes,2,opt,name=interval_param,json=intervalParam,proto3" json:"interval_param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalJoinReq) Reset() {
	*x = IntervalJoinReq{}
	mi := &file_IntervalJoinReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalJoinReq) ProtoMessage() {}

func (x *IntervalJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_IntervalJoinReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalJoinReq.ProtoReflect.Descriptor instead.
func (*IntervalJoinReq) Descriptor() ([]byte, []int) {
	return file_IntervalJoinReq_proto_rawDescGZIP(), []int{0}
}

func (x *IntervalJoinReq) GetFriendId() uint32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *IntervalJoinReq) GetIntervalParam() string {
	if x != nil {
		return x.IntervalParam
	}
	return ""
}

var File_IntervalJoinReq_proto protoreflect.FileDescriptor

const file_IntervalJoinReq_proto_rawDesc = "" +
	"\n" +
	"\x15IntervalJoinReq.proto\x12\x05proto\"U\n" +
	"\x0fIntervalJoinReq\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\rR\bfriendId\x12%\n" +
	"\x0einterval_param\x18\x02 \x01(\tR\rintervalParamB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_IntervalJoinReq_proto_rawDescOnce sync.Once
	file_IntervalJoinReq_proto_rawDescData []byte
)

func file_IntervalJoinReq_proto_rawDescGZIP() []byte {
	file_IntervalJoinReq_proto_rawDescOnce.Do(func() {
		file_IntervalJoinReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_IntervalJoinReq_proto_rawDesc), len(file_IntervalJoinReq_proto_rawDesc)))
	})
	return file_IntervalJoinReq_proto_rawDescData
}

var file_IntervalJoinReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_IntervalJoinReq_proto_goTypes = []any{
	(*IntervalJoinReq)(nil), // 0: proto.IntervalJoinReq
}
var file_IntervalJoinReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_IntervalJoinReq_proto_init() }
func file_IntervalJoinReq_proto_init() {
	if File_IntervalJoinReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_IntervalJoinReq_proto_rawDesc), len(file_IntervalJoinReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IntervalJoinReq_proto_goTypes,
		DependencyIndexes: file_IntervalJoinReq_proto_depIdxs,
		MessageInfos:      file_IntervalJoinReq_proto_msgTypes,
	}.Build()
	File_IntervalJoinReq_proto = out.File
	file_IntervalJoinReq_proto_goTypes = nil
	file_IntervalJoinReq_proto_depIdxs = nil
}
