// Extracted message IntervalJoinRsp
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: IntervalJoinRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntervalJoinRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	ExploreId     uint32                 `protobuf:"varint,3,opt,name=explore_id,json=exploreId,proto3" json:"explore_id,omitempty"`
	FinishTime    int64                  `protobuf:"varint,4,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalJoinRsp) Reset() {
	*x = IntervalJoinRsp{}
	mi := &file_IntervalJoinRsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalJoinRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalJoinRsp) ProtoMessage() {}

func (x *IntervalJoinRsp) ProtoReflect() protoreflect.Message {
	mi := &file_IntervalJoinRsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalJoinRsp.ProtoReflect.Descriptor instead.
func (*IntervalJoinRsp) Descriptor() ([]byte, []int) {
	return file_IntervalJoinRsp_proto_rawDescGZIP(), []int{0}
}

func (x *IntervalJoinRsp) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *IntervalJoinRsp) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *IntervalJoinRsp) GetExploreId() uint32 {
	if x != nil {
		return x.ExploreId
	}
	return 0
}

func (x *IntervalJoinRsp) GetFinishTime() int64 {
	if x != nil {
		return x.FinishTime
	}
	return 0
}

var File_IntervalJoinRsp_proto protoreflect.FileDescriptor

const file_IntervalJoinRsp_proto_rawDesc = "" +
	"\n" +
	"\x15IntervalJoinRsp.proto\x12\x05proto\x1a\x10StatusCode.proto\"\x99\x01\n" +
	"\x0fIntervalJoinRsp\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\x12\x1d\n" +
	"\n" +
	"explore_id\x18\x03 \x01(\rR\texploreId\x12\x1f\n" +
	"\vfinish_time\x18\x04 \x01(\x03R\n" +
	"finishTimeB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_IntervalJoinRsp_proto_rawDescOnce sync.Once
	file_IntervalJoinRsp_proto_rawDescData []byte
)

func file_IntervalJoinRsp_proto_rawDescGZIP() []byte {
	file_IntervalJoinRsp_proto_rawDescOnce.Do(func() {
		file_IntervalJoinRsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_IntervalJoinRsp_proto_rawDesc), len(file_IntervalJoinRsp_proto_rawDesc)))
	})
	return file_IntervalJoinRsp_proto_rawDescData
}

var file_IntervalJoinRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_IntervalJoinRsp_proto_goTypes = []any{
	(*IntervalJoinRsp)(nil), // 0: proto.IntervalJoinRsp
	(StatusCode)(0),         // 1: proto.StatusCode
}
var file_IntervalJoinRsp_proto_depIdxs = []int32{
	1, // 0: proto.IntervalJoinRsp.status:type_name -> proto.StatusCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_IntervalJoinRsp_proto_init() }
func file_IntervalJoinRsp_proto_init() {
	if File_IntervalJoinRsp_proto != nil {
		return
	}
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_IntervalJoinRsp_proto_rawDesc), len(file_IntervalJoinRsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IntervalJoinRsp_proto_goTypes,
		DependencyIndexes: file_IntervalJoinRsp_proto_depIdxs,
		MessageInfos:      file_IntervalJoinRsp_proto_msgTypes,
	}.Build()
	File_IntervalJoinRsp_proto = out.File
	file_IntervalJoinRsp_proto_goTypes = nil
	file_IntervalJoinRsp_proto_depIdxs = nil
}
