// Extracted enum JumpType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: JumpType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JumpType int32

const (
	JumpType_JumpType_None     JumpType = 0
	JumpType_JumpType_HttpJump JumpType = 1
	JumpType_JumpType_GameJump JumpType = 2
)

// Enum value maps for JumpType.
var (
	JumpType_name = map[int32]string{
		0: "JumpType_None",
		1: "JumpType_HttpJump",
		2: "JumpType_GameJump",
	}
	JumpType_value = map[string]int32{
		"JumpType_None":     0,
		"JumpType_HttpJump": 1,
		"JumpType_GameJump": 2,
	}
)

func (x JumpType) Enum() *JumpType {
	p := new(JumpType)
	*p = x
	return p
}

func (x JumpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JumpType) Descriptor() protoreflect.EnumDescriptor {
	return file_JumpType_proto_enumTypes[0].Descriptor()
}

func (JumpType) Type() protoreflect.EnumType {
	return &file_JumpType_proto_enumTypes[0]
}

func (x JumpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JumpType.Descriptor instead.
func (JumpType) EnumDescriptor() ([]byte, []int) {
	return file_JumpType_proto_rawDescGZIP(), []int{0}
}

var File_JumpType_proto protoreflect.FileDescriptor

const file_JumpType_proto_rawDesc = "" +
	"\n" +
	"\x0eJumpType.proto\x12\x05proto*K\n" +
	"\bJumpType\x12\x11\n" +
	"\rJumpType_None\x10\x00\x12\x15\n" +
	"\x11JumpType_HttpJump\x10\x01\x12\x15\n" +
	"\x11JumpType_GameJump\x10\x02B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_JumpType_proto_rawDescOnce sync.Once
	file_JumpType_proto_rawDescData []byte
)

func file_JumpType_proto_rawDescGZIP() []byte {
	file_JumpType_proto_rawDescOnce.Do(func() {
		file_JumpType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_JumpType_proto_rawDesc), len(file_JumpType_proto_rawDesc)))
	})
	return file_JumpType_proto_rawDescData
}

var file_JumpType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_JumpType_proto_goTypes = []any{
	(JumpType)(0), // 0: proto.JumpType
}
var file_JumpType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_JumpType_proto_init() }
func file_JumpType_proto_init() {
	if File_JumpType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_JumpType_proto_rawDesc), len(file_JumpType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_JumpType_proto_goTypes,
		DependencyIndexes: file_JumpType_proto_depIdxs,
		EnumInfos:         file_JumpType_proto_enumTypes,
	}.Build()
	File_JumpType_proto = out.File
	file_JumpType_proto_goTypes = nil
	file_JumpType_proto_depIdxs = nil
}
