// Extracted message LifeLeveUpRsp
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: LifeLeveUpRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifeLeveUpRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	LifeBaseInfo  *LifeBaseInfo          `protobuf:"bytes,2,opt,name=life_base_info,json=lifeBaseInfo,proto3" json:"life_base_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifeLeveUpRsp) Reset() {
	*x = LifeLeveUpRsp{}
	mi := &file_LifeLeveUpRsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifeLeveUpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifeLeveUpRsp) ProtoMessage() {}

func (x *LifeLeveUpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_LifeLeveUpRsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifeLeveUpRsp.ProtoReflect.Descriptor instead.
func (*LifeLeveUpRsp) Descriptor() ([]byte, []int) {
	return file_LifeLeveUpRsp_proto_rawDescGZIP(), []int{0}
}

func (x *LifeLeveUpRsp) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *LifeLeveUpRsp) GetLifeBaseInfo() *LifeBaseInfo {
	if x != nil {
		return x.LifeBaseInfo
	}
	return nil
}

var File_LifeLeveUpRsp_proto protoreflect.FileDescriptor

const file_LifeLeveUpRsp_proto_rawDesc = "" +
	"\n" +
	"\x13LifeLeveUpRsp.proto\x12\x05proto\x1a\x12LifeBaseInfo.proto\x1a\x10StatusCode.proto\"u\n" +
	"\rLifeLeveUpRsp\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x129\n" +
	"\x0elife_base_info\x18\x02 \x01(\v2\x13.proto.LifeBaseInfoR\flifeBaseInfoB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_LifeLeveUpRsp_proto_rawDescOnce sync.Once
	file_LifeLeveUpRsp_proto_rawDescData []byte
)

func file_LifeLeveUpRsp_proto_rawDescGZIP() []byte {
	file_LifeLeveUpRsp_proto_rawDescOnce.Do(func() {
		file_LifeLeveUpRsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_LifeLeveUpRsp_proto_rawDesc), len(file_LifeLeveUpRsp_proto_rawDesc)))
	})
	return file_LifeLeveUpRsp_proto_rawDescData
}

var file_LifeLeveUpRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_LifeLeveUpRsp_proto_goTypes = []any{
	(*LifeLeveUpRsp)(nil), // 0: proto.LifeLeveUpRsp
	(StatusCode)(0),       // 1: proto.StatusCode
	(*LifeBaseInfo)(nil),  // 2: proto.LifeBaseInfo
}
var file_LifeLeveUpRsp_proto_depIdxs = []int32{
	1, // 0: proto.LifeLeveUpRsp.status:type_name -> proto.StatusCode
	2, // 1: proto.LifeLeveUpRsp.life_base_info:type_name -> proto.LifeBaseInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_LifeLeveUpRsp_proto_init() }
func file_LifeLeveUpRsp_proto_init() {
	if File_LifeLeveUpRsp_proto != nil {
		return
	}
	file_LifeBaseInfo_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_LifeLeveUpRsp_proto_rawDesc), len(file_LifeLeveUpRsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LifeLeveUpRsp_proto_goTypes,
		DependencyIndexes: file_LifeLeveUpRsp_proto_depIdxs,
		MessageInfos:      file_LifeLeveUpRsp_proto_msgTypes,
	}.Build()
	File_LifeLeveUpRsp_proto = out.File
	file_LifeLeveUpRsp_proto_goTypes = nil
	file_LifeLeveUpRsp_proto_depIdxs = nil
}
