// Extracted message LifeCommonResult
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: LifeCommonResult.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifeCommonResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResultItems      []*ItemDetail          `protobuf:"bytes,1,rep,name=result_items,json=resultItems,proto3" json:"result_items,omitempty"`
	IsSuccess        bool                   `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	LifeType         LifeType               `protobuf:"varint,3,opt,name=life_type,json=lifeType,proto3,enum=proto.LifeType" json:"life_type,omitempty"`
	SkillReturnItems []*BaseItem            `protobuf:"bytes,6,rep,name=skill_return_items,json=skillReturnItems,proto3" json:"skill_return_items,omitempty"`
	IsLuckyReturn    bool                   `protobuf:"varint,7,opt,name=is_lucky_return,json=isLuckyReturn,proto3" json:"is_lucky_return,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LifeCommonResult) Reset() {
	*x = LifeCommonResult{}
	mi := &file_LifeCommonResult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifeCommonResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifeCommonResult) ProtoMessage() {}

func (x *LifeCommonResult) ProtoReflect() protoreflect.Message {
	mi := &file_LifeCommonResult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifeCommonResult.ProtoReflect.Descriptor instead.
func (*LifeCommonResult) Descriptor() ([]byte, []int) {
	return file_LifeCommonResult_proto_rawDescGZIP(), []int{0}
}

func (x *LifeCommonResult) GetResultItems() []*ItemDetail {
	if x != nil {
		return x.ResultItems
	}
	return nil
}

func (x *LifeCommonResult) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *LifeCommonResult) GetLifeType() LifeType {
	if x != nil {
		return x.LifeType
	}
	return LifeType_LifeType_None
}

func (x *LifeCommonResult) GetSkillReturnItems() []*BaseItem {
	if x != nil {
		return x.SkillReturnItems
	}
	return nil
}

func (x *LifeCommonResult) GetIsLuckyReturn() bool {
	if x != nil {
		return x.IsLuckyReturn
	}
	return false
}

var File_LifeCommonResult_proto protoreflect.FileDescriptor

const file_LifeCommonResult_proto_rawDesc = "" +
	"\n" +
	"\x16LifeCommonResult.proto\x12\x05proto\x1a\x0eBaseItem.proto\x1a\x10ItemDetail.proto\x1a\x0eLifeType.proto\"\xfc\x01\n" +
	"\x10LifeCommonResult\x124\n" +
	"\fresult_items\x18\x01 \x03(\v2\x11.proto.ItemDetailR\vresultItems\x12\x1d\n" +
	"\n" +
	"is_success\x18\x02 \x01(\bR\tisSuccess\x12,\n" +
	"\tlife_type\x18\x03 \x01(\x0e2\x0f.proto.LifeTypeR\blifeType\x12=\n" +
	"\x12skill_return_items\x18\x06 \x03(\v2\x0f.proto.BaseItemR\x10skillReturnItems\x12&\n" +
	"\x0fis_lucky_return\x18\a \x01(\bR\risLuckyReturnB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_LifeCommonResult_proto_rawDescOnce sync.Once
	file_LifeCommonResult_proto_rawDescData []byte
)

func file_LifeCommonResult_proto_rawDescGZIP() []byte {
	file_LifeCommonResult_proto_rawDescOnce.Do(func() {
		file_LifeCommonResult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_LifeCommonResult_proto_rawDesc), len(file_LifeCommonResult_proto_rawDesc)))
	})
	return file_LifeCommonResult_proto_rawDescData
}

var file_LifeCommonResult_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_LifeCommonResult_proto_goTypes = []any{
	(*LifeCommonResult)(nil), // 0: proto.LifeCommonResult
	(*ItemDetail)(nil),       // 1: proto.ItemDetail
	(LifeType)(0),            // 2: proto.LifeType
	(*BaseItem)(nil),         // 3: proto.BaseItem
}
var file_LifeCommonResult_proto_depIdxs = []int32{
	1, // 0: proto.LifeCommonResult.result_items:type_name -> proto.ItemDetail
	2, // 1: proto.LifeCommonResult.life_type:type_name -> proto.LifeType
	3, // 2: proto.LifeCommonResult.skill_return_items:type_name -> proto.BaseItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_LifeCommonResult_proto_init() }
func file_LifeCommonResult_proto_init() {
	if File_LifeCommonResult_proto != nil {
		return
	}
	file_BaseItem_proto_init()
	file_ItemDetail_proto_init()
	file_LifeType_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_LifeCommonResult_proto_rawDesc), len(file_LifeCommonResult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LifeCommonResult_proto_goTypes,
		DependencyIndexes: file_LifeCommonResult_proto_depIdxs,
		MessageInfos:      file_LifeCommonResult_proto_msgTypes,
	}.Build()
	File_LifeCommonResult_proto = out.File
	file_LifeCommonResult_proto_goTypes = nil
	file_LifeCommonResult_proto_depIdxs = nil
}
