// Extracted message MPPlayerInfo
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: MPPlayerInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MPPlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPPlayerInfo) Reset() {
	*x = MPPlayerInfo{}
	mi := &file_MPPlayerInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPPlayerInfo) ProtoMessage() {}

func (x *MPPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_MPPlayerInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPPlayerInfo.ProtoReflect.Descriptor instead.
func (*MPPlayerInfo) Descriptor() ([]byte, []int) {
	return file_MPPlayerInfo_proto_rawDescGZIP(), []int{0}
}

func (x *MPPlayerInfo) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

var File_MPPlayerInfo_proto protoreflect.FileDescriptor

const file_MPPlayerInfo_proto_rawDesc = "" +
	"\n" +
	"\x12MPPlayerInfo.proto\x12\x05proto\x1a\x0fCharacter.proto\">\n" +
	"\fMPPlayerInfo\x12.\n" +
	"\tcharacter\x18\x01 \x01(\v2\x10.proto.CharacterR\tcharacterB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_MPPlayerInfo_proto_rawDescOnce sync.Once
	file_MPPlayerInfo_proto_rawDescData []byte
)

func file_MPPlayerInfo_proto_rawDescGZIP() []byte {
	file_MPPlayerInfo_proto_rawDescOnce.Do(func() {
		file_MPPlayerInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MPPlayerInfo_proto_rawDesc), len(file_MPPlayerInfo_proto_rawDesc)))
	})
	return file_MPPlayerInfo_proto_rawDescData
}

var file_MPPlayerInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MPPlayerInfo_proto_goTypes = []any{
	(*MPPlayerInfo)(nil), // 0: proto.MPPlayerInfo
	(*Character)(nil),    // 1: proto.Character
}
var file_MPPlayerInfo_proto_depIdxs = []int32{
	1, // 0: proto.MPPlayerInfo.character:type_name -> proto.Character
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_MPPlayerInfo_proto_init() }
func file_MPPlayerInfo_proto_init() {
	if File_MPPlayerInfo_proto != nil {
		return
	}
	file_Character_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MPPlayerInfo_proto_rawDesc), len(file_MPPlayerInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MPPlayerInfo_proto_goTypes,
		DependencyIndexes: file_MPPlayerInfo_proto_depIdxs,
		MessageInfos:      file_MPPlayerInfo_proto_msgTypes,
	}.Build()
	File_MPPlayerInfo_proto = out.File
	file_MPPlayerInfo_proto_goTypes = nil
	file_MPPlayerInfo_proto_depIdxs = nil
}
