// Extracted message MPTeamMembers
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: MPTeamMembers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MPTeamMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        uint32                 `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Members       map[uint32]*MPPlayer   `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPTeamMembers) Reset() {
	*x = MPTeamMembers{}
	mi := &file_MPTeamMembers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPTeamMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPTeamMembers) ProtoMessage() {}

func (x *MPTeamMembers) ProtoReflect() protoreflect.Message {
	mi := &file_MPTeamMembers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPTeamMembers.ProtoReflect.Descriptor instead.
func (*MPTeamMembers) Descriptor() ([]byte, []int) {
	return file_MPTeamMembers_proto_rawDescGZIP(), []int{0}
}

func (x *MPTeamMembers) GetLeader() uint32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *MPTeamMembers) GetMembers() map[uint32]*MPPlayer {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_MPTeamMembers_proto protoreflect.FileDescriptor

const file_MPTeamMembers_proto_rawDesc = "" +
	"\n" +
	"\x13MPTeamMembers.proto\x12\x05proto\x1a\x0eMPPlayer.proto\"\xb1\x01\n" +
	"\rMPTeamMembers\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\rR\x06leader\x12;\n" +
	"\amembers\x18\x02 \x03(\v2!.proto.MPTeamMembers.MembersEntryR\amembers\x1aK\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.proto.MPPlayerR\x05value:\x028\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_MPTeamMembers_proto_rawDescOnce sync.Once
	file_MPTeamMembers_proto_rawDescData []byte
)

func file_MPTeamMembers_proto_rawDescGZIP() []byte {
	file_MPTeamMembers_proto_rawDescOnce.Do(func() {
		file_MPTeamMembers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MPTeamMembers_proto_rawDesc), len(file_MPTeamMembers_proto_rawDesc)))
	})
	return file_MPTeamMembers_proto_rawDescData
}

var file_MPTeamMembers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_MPTeamMembers_proto_goTypes = []any{
	(*MPTeamMembers)(nil), // 0: proto.MPTeamMembers
	nil,                   // 1: proto.MPTeamMembers.MembersEntry
	(*MPPlayer)(nil),      // 2: proto.MPPlayer
}
var file_MPTeamMembers_proto_depIdxs = []int32{
	1, // 0: proto.MPTeamMembers.members:type_name -> proto.MPTeamMembers.MembersEntry
	2, // 1: proto.MPTeamMembers.MembersEntry.value:type_name -> proto.MPPlayer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_MPTeamMembers_proto_init() }
func file_MPTeamMembers_proto_init() {
	if File_MPTeamMembers_proto != nil {
		return
	}
	file_MPPlayer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MPTeamMembers_proto_rawDesc), len(file_MPTeamMembers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MPTeamMembers_proto_goTypes,
		DependencyIndexes: file_MPTeamMembers_proto_depIdxs,
		MessageInfos:      file_MPTeamMembers_proto_msgTypes,
	}.Build()
	File_MPTeamMembers_proto = out.File
	file_MPTeamMembers_proto_goTypes = nil
	file_MPTeamMembers_proto_depIdxs = nil
}
