// Extracted message OperateCmdData
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: OperateCmdData.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperateCmdData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CmdType         OperateCmdType         `protobuf:"varint,2,opt,name=cmd_type,json=cmdType,proto3,enum=proto.OperateCmdType" json:"cmd_type,omitempty"`
	GmCode          string                 `protobuf:"bytes,3,opt,name=gm_code,json=gmCode,proto3" json:"gm_code,omitempty"`
	Questionnaire   *QuestionnaireCmdData  `protobuf:"bytes,4,opt,name=questionnaire,proto3" json:"questionnaire,omitempty"`
	TaskUpdateBatch []*TaskCmdData         `protobuf:"bytes,5,rep,name=task_update_batch,json=taskUpdateBatch,proto3" json:"task_update_batch,omitempty"`
	Data            []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OperateCmdData) Reset() {
	*x = OperateCmdData{}
	mi := &file_OperateCmdData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateCmdData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateCmdData) ProtoMessage() {}

func (x *OperateCmdData) ProtoReflect() protoreflect.Message {
	mi := &file_OperateCmdData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateCmdData.ProtoReflect.Descriptor instead.
func (*OperateCmdData) Descriptor() ([]byte, []int) {
	return file_OperateCmdData_proto_rawDescGZIP(), []int{0}
}

func (x *OperateCmdData) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OperateCmdData) GetCmdType() OperateCmdType {
	if x != nil {
		return x.CmdType
	}
	return OperateCmdType_OperateCmdType_None
}

func (x *OperateCmdData) GetGmCode() string {
	if x != nil {
		return x.GmCode
	}
	return ""
}

func (x *OperateCmdData) GetQuestionnaire() *QuestionnaireCmdData {
	if x != nil {
		return x.Questionnaire
	}
	return nil
}

func (x *OperateCmdData) GetTaskUpdateBatch() []*TaskCmdData {
	if x != nil {
		return x.TaskUpdateBatch
	}
	return nil
}

func (x *OperateCmdData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_OperateCmdData_proto protoreflect.FileDescriptor

const file_OperateCmdData_proto_rawDesc = "" +
	"\n" +
	"\x14OperateCmdData.proto\x12\x05proto\x1a\x14OperateCmdType.proto\x1a\x1aQuestionnaireCmdData.proto\x1a\x11TaskCmdData.proto\"\x8d\x02\n" +
	"\x0eOperateCmdData\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\bcmd_type\x18\x02 \x01(\x0e2\x15.proto.OperateCmdTypeR\acmdType\x12\x17\n" +
	"\agm_code\x18\x03 \x01(\tR\x06gmCode\x12A\n" +
	"\rquestionnaire\x18\x04 \x01(\v2\x1b.proto.QuestionnaireCmdDataR\rquestionnaire\x12>\n" +
	"\x11task_update_batch\x18\x05 \x03(\v2\x12.proto.TaskCmdDataR\x0ftaskUpdateBatch\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04dataB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_OperateCmdData_proto_rawDescOnce sync.Once
	file_OperateCmdData_proto_rawDescData []byte
)

func file_OperateCmdData_proto_rawDescGZIP() []byte {
	file_OperateCmdData_proto_rawDescOnce.Do(func() {
		file_OperateCmdData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OperateCmdData_proto_rawDesc), len(file_OperateCmdData_proto_rawDesc)))
	})
	return file_OperateCmdData_proto_rawDescData
}

var file_OperateCmdData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OperateCmdData_proto_goTypes = []any{
	(*OperateCmdData)(nil),       // 0: proto.OperateCmdData
	(OperateCmdType)(0),          // 1: proto.OperateCmdType
	(*QuestionnaireCmdData)(nil), // 2: proto.QuestionnaireCmdData
	(*TaskCmdData)(nil),          // 3: proto.TaskCmdData
}
var file_OperateCmdData_proto_depIdxs = []int32{
	1, // 0: proto.OperateCmdData.cmd_type:type_name -> proto.OperateCmdType
	2, // 1: proto.OperateCmdData.questionnaire:type_name -> proto.QuestionnaireCmdData
	3, // 2: proto.OperateCmdData.task_update_batch:type_name -> proto.TaskCmdData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_OperateCmdData_proto_init() }
func file_OperateCmdData_proto_init() {
	if File_OperateCmdData_proto != nil {
		return
	}
	file_OperateCmdType_proto_init()
	file_QuestionnaireCmdData_proto_init()
	file_TaskCmdData_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OperateCmdData_proto_rawDesc), len(file_OperateCmdData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OperateCmdData_proto_goTypes,
		DependencyIndexes: file_OperateCmdData_proto_depIdxs,
		MessageInfos:      file_OperateCmdData_proto_msgTypes,
	}.Build()
	File_OperateCmdData_proto = out.File
	file_OperateCmdData_proto_goTypes = nil
	file_OperateCmdData_proto_depIdxs = nil
}
