// Extracted message OutfitDyeScheme
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: OutfitDyeScheme.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutfitDyeScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemeIndex   uint32                 `protobuf:"varint,1,opt,name=scheme_index,json=schemeIndex,proto3" json:"scheme_index,omitempty"`
	Colors        []*PosColor            `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty"`
	IsUnLock      bool                   `protobuf:"varint,3,opt,name=is_un_lock,json=isUnLock,proto3" json:"is_un_lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutfitDyeScheme) Reset() {
	*x = OutfitDyeScheme{}
	mi := &file_OutfitDyeScheme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutfitDyeScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutfitDyeScheme) ProtoMessage() {}

func (x *OutfitDyeScheme) ProtoReflect() protoreflect.Message {
	mi := &file_OutfitDyeScheme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutfitDyeScheme.ProtoReflect.Descriptor instead.
func (*OutfitDyeScheme) Descriptor() ([]byte, []int) {
	return file_OutfitDyeScheme_proto_rawDescGZIP(), []int{0}
}

func (x *OutfitDyeScheme) GetSchemeIndex() uint32 {
	if x != nil {
		return x.SchemeIndex
	}
	return 0
}

func (x *OutfitDyeScheme) GetColors() []*PosColor {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *OutfitDyeScheme) GetIsUnLock() bool {
	if x != nil {
		return x.IsUnLock
	}
	return false
}

var File_OutfitDyeScheme_proto protoreflect.FileDescriptor

const file_OutfitDyeScheme_proto_rawDesc = "" +
	"\n" +
	"\x15OutfitDyeScheme.proto\x12\x05proto\x1a\x0ePosColor.proto\"{\n" +
	"\x0fOutfitDyeScheme\x12!\n" +
	"\fscheme_index\x18\x01 \x01(\rR\vschemeIndex\x12'\n" +
	"\x06colors\x18\x02 \x03(\v2\x0f.proto.PosColorR\x06colors\x12\x1c\n" +
	"\n" +
	"is_un_lock\x18\x03 \x01(\bR\bisUnLockB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_OutfitDyeScheme_proto_rawDescOnce sync.Once
	file_OutfitDyeScheme_proto_rawDescData []byte
)

func file_OutfitDyeScheme_proto_rawDescGZIP() []byte {
	file_OutfitDyeScheme_proto_rawDescOnce.Do(func() {
		file_OutfitDyeScheme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OutfitDyeScheme_proto_rawDesc), len(file_OutfitDyeScheme_proto_rawDesc)))
	})
	return file_OutfitDyeScheme_proto_rawDescData
}

var file_OutfitDyeScheme_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OutfitDyeScheme_proto_goTypes = []any{
	(*OutfitDyeScheme)(nil), // 0: proto.OutfitDyeScheme
	(*PosColor)(nil),        // 1: proto.PosColor
}
var file_OutfitDyeScheme_proto_depIdxs = []int32{
	1, // 0: proto.OutfitDyeScheme.colors:type_name -> proto.PosColor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_OutfitDyeScheme_proto_init() }
func file_OutfitDyeScheme_proto_init() {
	if File_OutfitDyeScheme_proto != nil {
		return
	}
	file_PosColor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OutfitDyeScheme_proto_rawDesc), len(file_OutfitDyeScheme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OutfitDyeScheme_proto_goTypes,
		DependencyIndexes: file_OutfitDyeScheme_proto_depIdxs,
		MessageInfos:      file_OutfitDyeScheme_proto_msgTypes,
	}.Build()
	File_OutfitDyeScheme_proto = out.File
	file_OutfitDyeScheme_proto_goTypes = nil
	file_OutfitDyeScheme_proto_depIdxs = nil
}
