// Extracted message PlayerActivitySandbag
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: PlayerActivitySandbag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerActivitySandbag struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	ActivityId     uint32                    `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	BoxList        []*PlayerActivityDailyBox `protobuf:"bytes,2,rep,name=box_list,json=boxList,proto3" json:"box_list,omitempty"`
	ServerReward   []uint32                  `protobuf:"varint,3,rep,packed,name=server_reward,json=serverReward,proto3" json:"server_reward,omitempty"`
	ServerProgress int64                     `protobuf:"varint,4,opt,name=server_progress,json=serverProgress,proto3" json:"server_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerActivitySandbag) Reset() {
	*x = PlayerActivitySandbag{}
	mi := &file_PlayerActivitySandbag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActivitySandbag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActivitySandbag) ProtoMessage() {}

func (x *PlayerActivitySandbag) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerActivitySandbag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActivitySandbag.ProtoReflect.Descriptor instead.
func (*PlayerActivitySandbag) Descriptor() ([]byte, []int) {
	return file_PlayerActivitySandbag_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerActivitySandbag) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PlayerActivitySandbag) GetBoxList() []*PlayerActivityDailyBox {
	if x != nil {
		return x.BoxList
	}
	return nil
}

func (x *PlayerActivitySandbag) GetServerReward() []uint32 {
	if x != nil {
		return x.ServerReward
	}
	return nil
}

func (x *PlayerActivitySandbag) GetServerProgress() int64 {
	if x != nil {
		return x.ServerProgress
	}
	return 0
}

var File_PlayerActivitySandbag_proto protoreflect.FileDescriptor

const file_PlayerActivitySandbag_proto_rawDesc = "" +
	"\n" +
	"\x1bPlayerActivitySandbag.proto\x12\x05proto\x1a\x1cPlayerActivityDailyBox.proto\"\xc0\x01\n" +
	"\x15PlayerActivitySandbag\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\rR\n" +
	"activityId\x128\n" +
	"\bbox_list\x18\x02 \x03(\v2\x1d.proto.PlayerActivityDailyBoxR\aboxList\x12#\n" +
	"\rserver_reward\x18\x03 \x03(\rR\fserverReward\x12'\n" +
	"\x0fserver_progress\x18\x04 \x01(\x03R\x0eserverProgressB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_PlayerActivitySandbag_proto_rawDescOnce sync.Once
	file_PlayerActivitySandbag_proto_rawDescData []byte
)

func file_PlayerActivitySandbag_proto_rawDescGZIP() []byte {
	file_PlayerActivitySandbag_proto_rawDescOnce.Do(func() {
		file_PlayerActivitySandbag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PlayerActivitySandbag_proto_rawDesc), len(file_PlayerActivitySandbag_proto_rawDesc)))
	})
	return file_PlayerActivitySandbag_proto_rawDescData
}

var file_PlayerActivitySandbag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerActivitySandbag_proto_goTypes = []any{
	(*PlayerActivitySandbag)(nil),  // 0: proto.PlayerActivitySandbag
	(*PlayerActivityDailyBox)(nil), // 1: proto.PlayerActivityDailyBox
}
var file_PlayerActivitySandbag_proto_depIdxs = []int32{
	1, // 0: proto.PlayerActivitySandbag.box_list:type_name -> proto.PlayerActivityDailyBox
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PlayerActivitySandbag_proto_init() }
func file_PlayerActivitySandbag_proto_init() {
	if File_PlayerActivitySandbag_proto != nil {
		return
	}
	file_PlayerActivityDailyBox_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PlayerActivitySandbag_proto_rawDesc), len(file_PlayerActivitySandbag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerActivitySandbag_proto_goTypes,
		DependencyIndexes: file_PlayerActivitySandbag_proto_depIdxs,
		MessageInfos:      file_PlayerActivitySandbag_proto_msgTypes,
	}.Build()
	File_PlayerActivitySandbag_proto = out.File
	file_PlayerActivitySandbag_proto_goTypes = nil
	file_PlayerActivitySandbag_proto_depIdxs = nil
}
