// Extracted message PlayerExploreInfo
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: PlayerExploreInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerExploreInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExploreId     uint32                 `protobuf:"varint,1,opt,name=explore_id,json=exploreId,proto3" json:"explore_id,omitempty"`
	Times         uint32                 `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	IsQuickFinish bool                   `protobuf:"varint,4,opt,name=is_quick_finish,json=isQuickFinish,proto3" json:"is_quick_finish,omitempty"`
	CollectItemId []uint32               `protobuf:"varint,6,rep,packed,name=collect_item_id,json=collectItemId,proto3" json:"collect_item_id,omitempty"`
	CollectReward bool                   `protobuf:"varint,7,opt,name=collect_reward,json=collectReward,proto3" json:"collect_reward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerExploreInfo) Reset() {
	*x = PlayerExploreInfo{}
	mi := &file_PlayerExploreInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerExploreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerExploreInfo) ProtoMessage() {}

func (x *PlayerExploreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerExploreInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerExploreInfo.ProtoReflect.Descriptor instead.
func (*PlayerExploreInfo) Descriptor() ([]byte, []int) {
	return file_PlayerExploreInfo_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerExploreInfo) GetExploreId() uint32 {
	if x != nil {
		return x.ExploreId
	}
	return 0
}

func (x *PlayerExploreInfo) GetTimes() uint32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *PlayerExploreInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PlayerExploreInfo) GetIsQuickFinish() bool {
	if x != nil {
		return x.IsQuickFinish
	}
	return false
}

func (x *PlayerExploreInfo) GetCollectItemId() []uint32 {
	if x != nil {
		return x.CollectItemId
	}
	return nil
}

func (x *PlayerExploreInfo) GetCollectReward() bool {
	if x != nil {
		return x.CollectReward
	}
	return false
}

var File_PlayerExploreInfo_proto protoreflect.FileDescriptor

const file_PlayerExploreInfo_proto_rawDesc = "" +
	"\n" +
	"\x17PlayerExploreInfo.proto\x12\x05proto\"\xde\x01\n" +
	"\x11PlayerExploreInfo\x12\x1d\n" +
	"\n" +
	"explore_id\x18\x01 \x01(\rR\texploreId\x12\x14\n" +
	"\x05times\x18\x02 \x01(\rR\x05times\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12&\n" +
	"\x0fis_quick_finish\x18\x04 \x01(\bR\risQuickFinish\x12&\n" +
	"\x0fcollect_item_id\x18\x06 \x03(\rR\rcollectItemId\x12%\n" +
	"\x0ecollect_reward\x18\a \x01(\bR\rcollectRewardB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_PlayerExploreInfo_proto_rawDescOnce sync.Once
	file_PlayerExploreInfo_proto_rawDescData []byte
)

func file_PlayerExploreInfo_proto_rawDescGZIP() []byte {
	file_PlayerExploreInfo_proto_rawDescOnce.Do(func() {
		file_PlayerExploreInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PlayerExploreInfo_proto_rawDesc), len(file_PlayerExploreInfo_proto_rawDesc)))
	})
	return file_PlayerExploreInfo_proto_rawDescData
}

var file_PlayerExploreInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerExploreInfo_proto_goTypes = []any{
	(*PlayerExploreInfo)(nil), // 0: proto.PlayerExploreInfo
}
var file_PlayerExploreInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PlayerExploreInfo_proto_init() }
func file_PlayerExploreInfo_proto_init() {
	if File_PlayerExploreInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PlayerExploreInfo_proto_rawDesc), len(file_PlayerExploreInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerExploreInfo_proto_goTypes,
		DependencyIndexes: file_PlayerExploreInfo_proto_depIdxs,
		MessageInfos:      file_PlayerExploreInfo_proto_msgTypes,
	}.Build()
	File_PlayerExploreInfo_proto = out.File
	file_PlayerExploreInfo_proto_goTypes = nil
	file_PlayerExploreInfo_proto_depIdxs = nil
}
