// Extracted message RedemptionCodeData
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: RedemptionCodeData.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedemptionCodeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Type          RedemptionCodeType     `protobuf:"varint,2,opt,name=type,proto3,enum=proto.RedemptionCodeType" json:"type,omitempty"`
	UseFrequency  uint32                 `protobuf:"varint,3,opt,name=use_frequency,json=useFrequency,proto3" json:"use_frequency,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Channels      []uint32               `protobuf:"varint,6,rep,packed,name=channels,proto3" json:"channels,omitempty"`
	Items         []*BaseItem            `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedemptionCodeData) Reset() {
	*x = RedemptionCodeData{}
	mi := &file_RedemptionCodeData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedemptionCodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedemptionCodeData) ProtoMessage() {}

func (x *RedemptionCodeData) ProtoReflect() protoreflect.Message {
	mi := &file_RedemptionCodeData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedemptionCodeData.ProtoReflect.Descriptor instead.
func (*RedemptionCodeData) Descriptor() ([]byte, []int) {
	return file_RedemptionCodeData_proto_rawDescGZIP(), []int{0}
}

func (x *RedemptionCodeData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RedemptionCodeData) GetType() RedemptionCodeType {
	if x != nil {
		return x.Type
	}
	return RedemptionCodeType_RedemptionCodeType_Text
}

func (x *RedemptionCodeData) GetUseFrequency() uint32 {
	if x != nil {
		return x.UseFrequency
	}
	return 0
}

func (x *RedemptionCodeData) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RedemptionCodeData) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *RedemptionCodeData) GetChannels() []uint32 {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *RedemptionCodeData) GetItems() []*BaseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_RedemptionCodeData_proto protoreflect.FileDescriptor

const file_RedemptionCodeData_proto_rawDesc = "" +
	"\n" +
	"\x18RedemptionCodeData.proto\x12\x05proto\x1a\x0eBaseItem.proto\x1a\x18RedemptionCodeType.proto\"\xf9\x01\n" +
	"\x12RedemptionCodeData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.proto.RedemptionCodeTypeR\x04type\x12#\n" +
	"\ruse_frequency\x18\x03 \x01(\rR\fuseFrequency\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1a\n" +
	"\bchannels\x18\x06 \x03(\rR\bchannels\x12%\n" +
	"\x05items\x18\a \x03(\v2\x0f.proto.BaseItemR\x05itemsB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_RedemptionCodeData_proto_rawDescOnce sync.Once
	file_RedemptionCodeData_proto_rawDescData []byte
)

func file_RedemptionCodeData_proto_rawDescGZIP() []byte {
	file_RedemptionCodeData_proto_rawDescOnce.Do(func() {
		file_RedemptionCodeData_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RedemptionCodeData_proto_rawDesc), len(file_RedemptionCodeData_proto_rawDesc)))
	})
	return file_RedemptionCodeData_proto_rawDescData
}

var file_RedemptionCodeData_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RedemptionCodeData_proto_goTypes = []any{
	(*RedemptionCodeData)(nil), // 0: proto.RedemptionCodeData
	(RedemptionCodeType)(0),    // 1: proto.RedemptionCodeType
	(*BaseItem)(nil),           // 2: proto.BaseItem
}
var file_RedemptionCodeData_proto_depIdxs = []int32{
	1, // 0: proto.RedemptionCodeData.type:type_name -> proto.RedemptionCodeType
	2, // 1: proto.RedemptionCodeData.items:type_name -> proto.BaseItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_RedemptionCodeData_proto_init() }
func file_RedemptionCodeData_proto_init() {
	if File_RedemptionCodeData_proto != nil {
		return
	}
	file_BaseItem_proto_init()
	file_RedemptionCodeType_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RedemptionCodeData_proto_rawDesc), len(file_RedemptionCodeData_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RedemptionCodeData_proto_goTypes,
		DependencyIndexes: file_RedemptionCodeData_proto_depIdxs,
		MessageInfos:      file_RedemptionCodeData_proto_msgTypes,
	}.Build()
	File_RedemptionCodeData_proto = out.File
	file_RedemptionCodeData_proto_goTypes = nil
	file_RedemptionCodeData_proto_depIdxs = nil
}
