// Extracted message RestaurantGameQuestRewardReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: RestaurantGameQuestRewardReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantGameQuestRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestId       uint32                 `protobuf:"varint,1,opt,name=quest_id,json=questId,proto3" json:"quest_id,omitempty"`
	ActivityId    uint32                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantGameQuestRewardReq) Reset() {
	*x = RestaurantGameQuestRewardReq{}
	mi := &file_RestaurantGameQuestRewardReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantGameQuestRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantGameQuestRewardReq) ProtoMessage() {}

func (x *RestaurantGameQuestRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_RestaurantGameQuestRewardReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantGameQuestRewardReq.ProtoReflect.Descriptor instead.
func (*RestaurantGameQuestRewardReq) Descriptor() ([]byte, []int) {
	return file_RestaurantGameQuestRewardReq_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantGameQuestRewardReq) GetQuestId() uint32 {
	if x != nil {
		return x.QuestId
	}
	return 0
}

func (x *RestaurantGameQuestRewardReq) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

var File_RestaurantGameQuestRewardReq_proto protoreflect.FileDescriptor

const file_RestaurantGameQuestRewardReq_proto_rawDesc = "" +
	"\n" +
	"\"RestaurantGameQuestRewardReq.proto\x12\x05proto\"Z\n" +
	"\x1cRestaurantGameQuestRewardReq\x12\x19\n" +
	"\bquest_id\x18\x01 \x01(\rR\aquestId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\rR\n" +
	"activityIdB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_RestaurantGameQuestRewardReq_proto_rawDescOnce sync.Once
	file_RestaurantGameQuestRewardReq_proto_rawDescData []byte
)

func file_RestaurantGameQuestRewardReq_proto_rawDescGZIP() []byte {
	file_RestaurantGameQuestRewardReq_proto_rawDescOnce.Do(func() {
		file_RestaurantGameQuestRewardReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RestaurantGameQuestRewardReq_proto_rawDesc), len(file_RestaurantGameQuestRewardReq_proto_rawDesc)))
	})
	return file_RestaurantGameQuestRewardReq_proto_rawDescData
}

var file_RestaurantGameQuestRewardReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RestaurantGameQuestRewardReq_proto_goTypes = []any{
	(*RestaurantGameQuestRewardReq)(nil), // 0: proto.RestaurantGameQuestRewardReq
}
var file_RestaurantGameQuestRewardReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RestaurantGameQuestRewardReq_proto_init() }
func file_RestaurantGameQuestRewardReq_proto_init() {
	if File_RestaurantGameQuestRewardReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RestaurantGameQuestRewardReq_proto_rawDesc), len(file_RestaurantGameQuestRewardReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RestaurantGameQuestRewardReq_proto_goTypes,
		DependencyIndexes: file_RestaurantGameQuestRewardReq_proto_depIdxs,
		MessageInfos:      file_RestaurantGameQuestRewardReq_proto_msgTypes,
	}.Build()
	File_RestaurantGameQuestRewardReq_proto = out.File
	file_RestaurantGameQuestRewardReq_proto_goTypes = nil
	file_RestaurantGameQuestRewardReq_proto_depIdxs = nil
}
