// Extracted message RestaurantGameOperateReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: RestaurantGameOperateReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantGameOperateReq struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ActivityId    uint32                    `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Type          RestaurantGameOperateType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.RestaurantGameOperateType" json:"type,omitempty"`
	BuyPoolId     uint32                    `protobuf:"varint,3,opt,name=buy_pool_id,json=buyPoolId,proto3" json:"buy_pool_id,omitempty"`
	Grid          []uint32                  `protobuf:"varint,4,rep,packed,name=grid,proto3" json:"grid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantGameOperateReq) Reset() {
	*x = RestaurantGameOperateReq{}
	mi := &file_RestaurantGameOperateReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantGameOperateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantGameOperateReq) ProtoMessage() {}

func (x *RestaurantGameOperateReq) ProtoReflect() protoreflect.Message {
	mi := &file_RestaurantGameOperateReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantGameOperateReq.ProtoReflect.Descriptor instead.
func (*RestaurantGameOperateReq) Descriptor() ([]byte, []int) {
	return file_RestaurantGameOperateReq_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantGameOperateReq) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *RestaurantGameOperateReq) GetType() RestaurantGameOperateType {
	if x != nil {
		return x.Type
	}
	return RestaurantGameOperateType_RestaurantGameOperateType_None
}

func (x *RestaurantGameOperateReq) GetBuyPoolId() uint32 {
	if x != nil {
		return x.BuyPoolId
	}
	return 0
}

func (x *RestaurantGameOperateReq) GetGrid() []uint32 {
	if x != nil {
		return x.Grid
	}
	return nil
}

var File_RestaurantGameOperateReq_proto protoreflect.FileDescriptor

const file_RestaurantGameOperateReq_proto_rawDesc = "" +
	"\n" +
	"\x1eRestaurantGameOperateReq.proto\x12\x05proto\x1a\x1fRestaurantGameOperateType.proto\"\xa5\x01\n" +
	"\x18RestaurantGameOperateReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\rR\n" +
	"activityId\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .proto.RestaurantGameOperateTypeR\x04type\x12\x1e\n" +
	"\vbuy_pool_id\x18\x03 \x01(\rR\tbuyPoolId\x12\x12\n" +
	"\x04grid\x18\x04 \x03(\rR\x04gridB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_RestaurantGameOperateReq_proto_rawDescOnce sync.Once
	file_RestaurantGameOperateReq_proto_rawDescData []byte
)

func file_RestaurantGameOperateReq_proto_rawDescGZIP() []byte {
	file_RestaurantGameOperateReq_proto_rawDescOnce.Do(func() {
		file_RestaurantGameOperateReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RestaurantGameOperateReq_proto_rawDesc), len(file_RestaurantGameOperateReq_proto_rawDesc)))
	})
	return file_RestaurantGameOperateReq_proto_rawDescData
}

var file_RestaurantGameOperateReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RestaurantGameOperateReq_proto_goTypes = []any{
	(*RestaurantGameOperateReq)(nil), // 0: proto.RestaurantGameOperateReq
	(RestaurantGameOperateType)(0),   // 1: proto.RestaurantGameOperateType
}
var file_RestaurantGameOperateReq_proto_depIdxs = []int32{
	1, // 0: proto.RestaurantGameOperateReq.type:type_name -> proto.RestaurantGameOperateType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_RestaurantGameOperateReq_proto_init() }
func file_RestaurantGameOperateReq_proto_init() {
	if File_RestaurantGameOperateReq_proto != nil {
		return
	}
	file_RestaurantGameOperateType_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RestaurantGameOperateReq_proto_rawDesc), len(file_RestaurantGameOperateReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RestaurantGameOperateReq_proto_goTypes,
		DependencyIndexes: file_RestaurantGameOperateReq_proto_depIdxs,
		MessageInfos:      file_RestaurantGameOperateReq_proto_msgTypes,
	}.Build()
	File_RestaurantGameOperateReq_proto = out.File
	file_RestaurantGameOperateReq_proto_goTypes = nil
	file_RestaurantGameOperateReq_proto_depIdxs = nil
}
