// Extracted enum RestaurantGameOperateType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: RestaurantGameOperateType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantGameOperateType int32

const (
	RestaurantGameOperateType_RestaurantGameOperateType_None    RestaurantGameOperateType = 0
	RestaurantGameOperateType_RestaurantGameOperateType_Buy     RestaurantGameOperateType = 1
	RestaurantGameOperateType_RestaurantGameOperateType_Mix     RestaurantGameOperateType = 2
	RestaurantGameOperateType_RestaurantGameOperateType_Recycle RestaurantGameOperateType = 3
)

// Enum value maps for RestaurantGameOperateType.
var (
	RestaurantGameOperateType_name = map[int32]string{
		0: "RestaurantGameOperateType_None",
		1: "RestaurantGameOperateType_Buy",
		2: "RestaurantGameOperateType_Mix",
		3: "RestaurantGameOperateType_Recycle",
	}
	RestaurantGameOperateType_value = map[string]int32{
		"RestaurantGameOperateType_None":    0,
		"RestaurantGameOperateType_Buy":     1,
		"RestaurantGameOperateType_Mix":     2,
		"RestaurantGameOperateType_Recycle": 3,
	}
)

func (x RestaurantGameOperateType) Enum() *RestaurantGameOperateType {
	p := new(RestaurantGameOperateType)
	*p = x
	return p
}

func (x RestaurantGameOperateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestaurantGameOperateType) Descriptor() protoreflect.EnumDescriptor {
	return file_RestaurantGameOperateType_proto_enumTypes[0].Descriptor()
}

func (RestaurantGameOperateType) Type() protoreflect.EnumType {
	return &file_RestaurantGameOperateType_proto_enumTypes[0]
}

func (x RestaurantGameOperateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestaurantGameOperateType.Descriptor instead.
func (RestaurantGameOperateType) EnumDescriptor() ([]byte, []int) {
	return file_RestaurantGameOperateType_proto_rawDescGZIP(), []int{0}
}

var File_RestaurantGameOperateType_proto protoreflect.FileDescriptor

const file_RestaurantGameOperateType_proto_rawDesc = "" +
	"\n" +
	"\x1fRestaurantGameOperateType.proto\x12\x05proto*\xac\x01\n" +
	"\x19RestaurantGameOperateType\x12\"\n" +
	"\x1eRestaurantGameOperateType_None\x10\x00\x12!\n" +
	"\x1dRestaurantGameOperateType_Buy\x10\x01\x12!\n" +
	"\x1dRestaurantGameOperateType_Mix\x10\x02\x12%\n" +
	"!RestaurantGameOperateType_Recycle\x10\x03B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_RestaurantGameOperateType_proto_rawDescOnce sync.Once
	file_RestaurantGameOperateType_proto_rawDescData []byte
)

func file_RestaurantGameOperateType_proto_rawDescGZIP() []byte {
	file_RestaurantGameOperateType_proto_rawDescOnce.Do(func() {
		file_RestaurantGameOperateType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RestaurantGameOperateType_proto_rawDesc), len(file_RestaurantGameOperateType_proto_rawDesc)))
	})
	return file_RestaurantGameOperateType_proto_rawDescData
}

var file_RestaurantGameOperateType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_RestaurantGameOperateType_proto_goTypes = []any{
	(RestaurantGameOperateType)(0), // 0: proto.RestaurantGameOperateType
}
var file_RestaurantGameOperateType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RestaurantGameOperateType_proto_init() }
func file_RestaurantGameOperateType_proto_init() {
	if File_RestaurantGameOperateType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RestaurantGameOperateType_proto_rawDesc), len(file_RestaurantGameOperateType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RestaurantGameOperateType_proto_goTypes,
		DependencyIndexes: file_RestaurantGameOperateType_proto_depIdxs,
		EnumInfos:         file_RestaurantGameOperateType_proto_enumTypes,
	}.Build()
	File_RestaurantGameOperateType_proto = out.File
	file_RestaurantGameOperateType_proto_goTypes = nil
	file_RestaurantGameOperateType_proto_depIdxs = nil
}
