// Extracted message RestaurantGameCustomerInfo
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: RestaurantGameCustomerInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantGameCustomerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerIndex uint32                 `protobuf:"varint,1,opt,name=customer_index,json=customerIndex,proto3" json:"customer_index,omitempty"`
	Food          uint32                 `protobuf:"varint,2,opt,name=food,proto3" json:"food,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantGameCustomerInfo) Reset() {
	*x = RestaurantGameCustomerInfo{}
	mi := &file_RestaurantGameCustomerInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantGameCustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantGameCustomerInfo) ProtoMessage() {}

func (x *RestaurantGameCustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_RestaurantGameCustomerInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantGameCustomerInfo.ProtoReflect.Descriptor instead.
func (*RestaurantGameCustomerInfo) Descriptor() ([]byte, []int) {
	return file_RestaurantGameCustomerInfo_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantGameCustomerInfo) GetCustomerIndex() uint32 {
	if x != nil {
		return x.CustomerIndex
	}
	return 0
}

func (x *RestaurantGameCustomerInfo) GetFood() uint32 {
	if x != nil {
		return x.Food
	}
	return 0
}

func (x *RestaurantGameCustomerInfo) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_RestaurantGameCustomerInfo_proto protoreflect.FileDescriptor

const file_RestaurantGameCustomerInfo_proto_rawDesc = "" +
	"\n" +
	" RestaurantGameCustomerInfo.proto\x12\x05proto\"o\n" +
	"\x1aRestaurantGameCustomerInfo\x12%\n" +
	"\x0ecustomer_index\x18\x01 \x01(\rR\rcustomerIndex\x12\x12\n" +
	"\x04food\x18\x02 \x01(\rR\x04food\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06statusB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_RestaurantGameCustomerInfo_proto_rawDescOnce sync.Once
	file_RestaurantGameCustomerInfo_proto_rawDescData []byte
)

func file_RestaurantGameCustomerInfo_proto_rawDescGZIP() []byte {
	file_RestaurantGameCustomerInfo_proto_rawDescOnce.Do(func() {
		file_RestaurantGameCustomerInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RestaurantGameCustomerInfo_proto_rawDesc), len(file_RestaurantGameCustomerInfo_proto_rawDesc)))
	})
	return file_RestaurantGameCustomerInfo_proto_rawDescData
}

var file_RestaurantGameCustomerInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_RestaurantGameCustomerInfo_proto_goTypes = []any{
	(*RestaurantGameCustomerInfo)(nil), // 0: proto.RestaurantGameCustomerInfo
}
var file_RestaurantGameCustomerInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RestaurantGameCustomerInfo_proto_init() }
func file_RestaurantGameCustomerInfo_proto_init() {
	if File_RestaurantGameCustomerInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RestaurantGameCustomerInfo_proto_rawDesc), len(file_RestaurantGameCustomerInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RestaurantGameCustomerInfo_proto_goTypes,
		DependencyIndexes: file_RestaurantGameCustomerInfo_proto_depIdxs,
		MessageInfos:      file_RestaurantGameCustomerInfo_proto_msgTypes,
	}.Build()
	File_RestaurantGameCustomerInfo_proto = out.File
	file_RestaurantGameCustomerInfo_proto_goTypes = nil
	file_RestaurantGameCustomerInfo_proto_depIdxs = nil
}
