// Extracted enum RollNoticeType
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: RollNoticeType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollNoticeType int32

const (
	RollNoticeType_RollNoticeType_None      RollNoticeType = 0
	RollNoticeType_RollNoticeType_Fireworks RollNoticeType = 1
)

// Enum value maps for RollNoticeType.
var (
	RollNoticeType_name = map[int32]string{
		0: "RollNoticeType_None",
		1: "RollNoticeType_Fireworks",
	}
	RollNoticeType_value = map[string]int32{
		"RollNoticeType_None":      0,
		"RollNoticeType_Fireworks": 1,
	}
)

func (x RollNoticeType) Enum() *RollNoticeType {
	p := new(RollNoticeType)
	*p = x
	return p
}

func (x RollNoticeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RollNoticeType) Descriptor() protoreflect.EnumDescriptor {
	return file_RollNoticeType_proto_enumTypes[0].Descriptor()
}

func (RollNoticeType) Type() protoreflect.EnumType {
	return &file_RollNoticeType_proto_enumTypes[0]
}

func (x RollNoticeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RollNoticeType.Descriptor instead.
func (RollNoticeType) EnumDescriptor() ([]byte, []int) {
	return file_RollNoticeType_proto_rawDescGZIP(), []int{0}
}

var File_RollNoticeType_proto protoreflect.FileDescriptor

const file_RollNoticeType_proto_rawDesc = "" +
	"\n" +
	"\x14RollNoticeType.proto\x12\x05proto*G\n" +
	"\x0eRollNoticeType\x12\x17\n" +
	"\x13RollNoticeType_None\x10\x00\x12\x1c\n" +
	"\x18RollNoticeType_Fireworks\x10\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_RollNoticeType_proto_rawDescOnce sync.Once
	file_RollNoticeType_proto_rawDescData []byte
)

func file_RollNoticeType_proto_rawDescGZIP() []byte {
	file_RollNoticeType_proto_rawDescOnce.Do(func() {
		file_RollNoticeType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_RollNoticeType_proto_rawDesc), len(file_RollNoticeType_proto_rawDesc)))
	})
	return file_RollNoticeType_proto_rawDescData
}

var file_RollNoticeType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_RollNoticeType_proto_goTypes = []any{
	(RollNoticeType)(0), // 0: proto.RollNoticeType
}
var file_RollNoticeType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RollNoticeType_proto_init() }
func file_RollNoticeType_proto_init() {
	if File_RollNoticeType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_RollNoticeType_proto_rawDesc), len(file_RollNoticeType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_RollNoticeType_proto_goTypes,
		DependencyIndexes: file_RollNoticeType_proto_depIdxs,
		EnumInfos:         file_RollNoticeType_proto_enumTypes,
	}.Build()
	File_RollNoticeType_proto = out.File
	file_RollNoticeType_proto_goTypes = nil
	file_RollNoticeType_proto_depIdxs = nil
}
