// Extracted message SceneMPBeaconNotice
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: SceneMPBeaconNotice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneMPBeaconNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	Beacons       map[uint32]*MPBeacon   `protobuf:"bytes,2,rep,name=beacons,proto3" json:"beacons,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneMPBeaconNotice) Reset() {
	*x = SceneMPBeaconNotice{}
	mi := &file_SceneMPBeaconNotice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneMPBeaconNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneMPBeaconNotice) ProtoMessage() {}

func (x *SceneMPBeaconNotice) ProtoReflect() protoreflect.Message {
	mi := &file_SceneMPBeaconNotice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneMPBeaconNotice.ProtoReflect.Descriptor instead.
func (*SceneMPBeaconNotice) Descriptor() ([]byte, []int) {
	return file_SceneMPBeaconNotice_proto_rawDescGZIP(), []int{0}
}

func (x *SceneMPBeaconNotice) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *SceneMPBeaconNotice) GetBeacons() map[uint32]*MPBeacon {
	if x != nil {
		return x.Beacons
	}
	return nil
}

var File_SceneMPBeaconNotice_proto protoreflect.FileDescriptor

const file_SceneMPBeaconNotice_proto_rawDesc = "" +
	"\n" +
	"\x19SceneMPBeaconNotice.proto\x12\x05proto\x1a\x0eMPBeacon.proto\x1a\x10StatusCode.proto\"\xd0\x01\n" +
	"\x13SceneMPBeaconNotice\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12A\n" +
	"\abeacons\x18\x02 \x03(\v2'.proto.SceneMPBeaconNotice.BeaconsEntryR\abeacons\x1aK\n" +
	"\fBeaconsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.proto.MPBeaconR\x05value:\x028\x01B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_SceneMPBeaconNotice_proto_rawDescOnce sync.Once
	file_SceneMPBeaconNotice_proto_rawDescData []byte
)

func file_SceneMPBeaconNotice_proto_rawDescGZIP() []byte {
	file_SceneMPBeaconNotice_proto_rawDescOnce.Do(func() {
		file_SceneMPBeaconNotice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SceneMPBeaconNotice_proto_rawDesc), len(file_SceneMPBeaconNotice_proto_rawDesc)))
	})
	return file_SceneMPBeaconNotice_proto_rawDescData
}

var file_SceneMPBeaconNotice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SceneMPBeaconNotice_proto_goTypes = []any{
	(*SceneMPBeaconNotice)(nil), // 0: proto.SceneMPBeaconNotice
	nil,                         // 1: proto.SceneMPBeaconNotice.BeaconsEntry
	(StatusCode)(0),             // 2: proto.StatusCode
	(*MPBeacon)(nil),            // 3: proto.MPBeacon
}
var file_SceneMPBeaconNotice_proto_depIdxs = []int32{
	2, // 0: proto.SceneMPBeaconNotice.status:type_name -> proto.StatusCode
	1, // 1: proto.SceneMPBeaconNotice.beacons:type_name -> proto.SceneMPBeaconNotice.BeaconsEntry
	3, // 2: proto.SceneMPBeaconNotice.BeaconsEntry.value:type_name -> proto.MPBeacon
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_SceneMPBeaconNotice_proto_init() }
func file_SceneMPBeaconNotice_proto_init() {
	if File_SceneMPBeaconNotice_proto != nil {
		return
	}
	file_MPBeacon_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SceneMPBeaconNotice_proto_rawDesc), len(file_SceneMPBeaconNotice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneMPBeaconNotice_proto_goTypes,
		DependencyIndexes: file_SceneMPBeaconNotice_proto_depIdxs,
		MessageInfos:      file_SceneMPBeaconNotice_proto_msgTypes,
	}.Build()
	File_SceneMPBeaconNotice_proto = out.File
	file_SceneMPBeaconNotice_proto_goTypes = nil
	file_SceneMPBeaconNotice_proto_depIdxs = nil
}
