// Extracted message SceneGardenFurnitureUpdateNotice
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: SceneGardenFurnitureUpdateNotice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneGardenFurnitureUpdateNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=proto.StatusCode" json:"status,omitempty"`
	FurnitureInfo *FurnitureDetailsInfo  `protobuf:"bytes,2,opt,name=furniture_info,json=furnitureInfo,proto3" json:"furniture_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneGardenFurnitureUpdateNotice) Reset() {
	*x = SceneGardenFurnitureUpdateNotice{}
	mi := &file_SceneGardenFurnitureUpdateNotice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneGardenFurnitureUpdateNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneGardenFurnitureUpdateNotice) ProtoMessage() {}

func (x *SceneGardenFurnitureUpdateNotice) ProtoReflect() protoreflect.Message {
	mi := &file_SceneGardenFurnitureUpdateNotice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneGardenFurnitureUpdateNotice.ProtoReflect.Descriptor instead.
func (*SceneGardenFurnitureUpdateNotice) Descriptor() ([]byte, []int) {
	return file_SceneGardenFurnitureUpdateNotice_proto_rawDescGZIP(), []int{0}
}

func (x *SceneGardenFurnitureUpdateNotice) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_StatusCode_None
}

func (x *SceneGardenFurnitureUpdateNotice) GetFurnitureInfo() *FurnitureDetailsInfo {
	if x != nil {
		return x.FurnitureInfo
	}
	return nil
}

var File_SceneGardenFurnitureUpdateNotice_proto protoreflect.FileDescriptor

const file_SceneGardenFurnitureUpdateNotice_proto_rawDesc = "" +
	"\n" +
	"&SceneGardenFurnitureUpdateNotice.proto\x12\x05proto\x1a\x1aFurnitureDetailsInfo.proto\x1a\x10StatusCode.proto\"\x91\x01\n" +
	" SceneGardenFurnitureUpdateNotice\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.proto.StatusCodeR\x06status\x12B\n" +
	"\x0efurniture_info\x18\x02 \x01(\v2\x1b.proto.FurnitureDetailsInfoR\rfurnitureInfoB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_SceneGardenFurnitureUpdateNotice_proto_rawDescOnce sync.Once
	file_SceneGardenFurnitureUpdateNotice_proto_rawDescData []byte
)

func file_SceneGardenFurnitureUpdateNotice_proto_rawDescGZIP() []byte {
	file_SceneGardenFurnitureUpdateNotice_proto_rawDescOnce.Do(func() {
		file_SceneGardenFurnitureUpdateNotice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SceneGardenFurnitureUpdateNotice_proto_rawDesc), len(file_SceneGardenFurnitureUpdateNotice_proto_rawDesc)))
	})
	return file_SceneGardenFurnitureUpdateNotice_proto_rawDescData
}

var file_SceneGardenFurnitureUpdateNotice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneGardenFurnitureUpdateNotice_proto_goTypes = []any{
	(*SceneGardenFurnitureUpdateNotice)(nil), // 0: proto.SceneGardenFurnitureUpdateNotice
	(StatusCode)(0),                          // 1: proto.StatusCode
	(*FurnitureDetailsInfo)(nil),             // 2: proto.FurnitureDetailsInfo
}
var file_SceneGardenFurnitureUpdateNotice_proto_depIdxs = []int32{
	1, // 0: proto.SceneGardenFurnitureUpdateNotice.status:type_name -> proto.StatusCode
	2, // 1: proto.SceneGardenFurnitureUpdateNotice.furniture_info:type_name -> proto.FurnitureDetailsInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_SceneGardenFurnitureUpdateNotice_proto_init() }
func file_SceneGardenFurnitureUpdateNotice_proto_init() {
	if File_SceneGardenFurnitureUpdateNotice_proto != nil {
		return
	}
	file_FurnitureDetailsInfo_proto_init()
	file_StatusCode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SceneGardenFurnitureUpdateNotice_proto_rawDesc), len(file_SceneGardenFurnitureUpdateNotice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneGardenFurnitureUpdateNotice_proto_goTypes,
		DependencyIndexes: file_SceneGardenFurnitureUpdateNotice_proto_depIdxs,
		MessageInfos:      file_SceneGardenFurnitureUpdateNotice_proto_msgTypes,
	}.Build()
	File_SceneGardenFurnitureUpdateNotice_proto = out.File
	file_SceneGardenFurnitureUpdateNotice_proto_goTypes = nil
	file_SceneGardenFurnitureUpdateNotice_proto_depIdxs = nil
}
