// Extracted message TakeOutFurnitureReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: TakeOutFurnitureReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TakeOutFurnitureReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FurnitureId    int64                  `protobuf:"varint,1,opt,name=furniture_id,json=furnitureId,proto3" json:"furniture_id,omitempty"`
	IsPutInPackage bool                   `protobuf:"varint,2,opt,name=is_put_in_package,json=isPutInPackage,proto3" json:"is_put_in_package,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TakeOutFurnitureReq) Reset() {
	*x = TakeOutFurnitureReq{}
	mi := &file_TakeOutFurnitureReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeOutFurnitureReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOutFurnitureReq) ProtoMessage() {}

func (x *TakeOutFurnitureReq) ProtoReflect() protoreflect.Message {
	mi := &file_TakeOutFurnitureReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOutFurnitureReq.ProtoReflect.Descriptor instead.
func (*TakeOutFurnitureReq) Descriptor() ([]byte, []int) {
	return file_TakeOutFurnitureReq_proto_rawDescGZIP(), []int{0}
}

func (x *TakeOutFurnitureReq) GetFurnitureId() int64 {
	if x != nil {
		return x.FurnitureId
	}
	return 0
}

func (x *TakeOutFurnitureReq) GetIsPutInPackage() bool {
	if x != nil {
		return x.IsPutInPackage
	}
	return false
}

var File_TakeOutFurnitureReq_proto protoreflect.FileDescriptor

const file_TakeOutFurnitureReq_proto_rawDesc = "" +
	"\n" +
	"\x19TakeOutFurnitureReq.proto\x12\x05proto\"c\n" +
	"\x13TakeOutFurnitureReq\x12!\n" +
	"\ffurniture_id\x18\x01 \x01(\x03R\vfurnitureId\x12)\n" +
	"\x11is_put_in_package\x18\x02 \x01(\bR\x0eisPutInPackageB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_TakeOutFurnitureReq_proto_rawDescOnce sync.Once
	file_TakeOutFurnitureReq_proto_rawDescData []byte
)

func file_TakeOutFurnitureReq_proto_rawDescGZIP() []byte {
	file_TakeOutFurnitureReq_proto_rawDescOnce.Do(func() {
		file_TakeOutFurnitureReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TakeOutFurnitureReq_proto_rawDesc), len(file_TakeOutFurnitureReq_proto_rawDesc)))
	})
	return file_TakeOutFurnitureReq_proto_rawDescData
}

var file_TakeOutFurnitureReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TakeOutFurnitureReq_proto_goTypes = []any{
	(*TakeOutFurnitureReq)(nil), // 0: proto.TakeOutFurnitureReq
}
var file_TakeOutFurnitureReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TakeOutFurnitureReq_proto_init() }
func file_TakeOutFurnitureReq_proto_init() {
	if File_TakeOutFurnitureReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TakeOutFurnitureReq_proto_rawDesc), len(file_TakeOutFurnitureReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TakeOutFurnitureReq_proto_goTypes,
		DependencyIndexes: file_TakeOutFurnitureReq_proto_depIdxs,
		MessageInfos:      file_TakeOutFurnitureReq_proto_msgTypes,
	}.Build()
	File_TakeOutFurnitureReq_proto = out.File
	file_TakeOutFurnitureReq_proto_goTypes = nil
	file_TakeOutFurnitureReq_proto_depIdxs = nil
}
