// Extracted message TeamRedis
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: TeamRedis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamRedis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaveTime      int64                  `protobuf:"varint,1,opt,name=save_time,json=saveTime,proto3" json:"save_time,omitempty"`
	Char1Pos      *Vector3               `protobuf:"bytes,2,opt,name=char1pos,proto3" json:"char1pos,omitempty"`
	Char1Rot      *Vector3               `protobuf:"bytes,3,opt,name=char1rot,proto3" json:"char1rot,omitempty"`
	Char2Pos      *Vector3               `protobuf:"bytes,4,opt,name=char2pos,proto3" json:"char2pos,omitempty"`
	Char2Rot      *Vector3               `protobuf:"bytes,5,opt,name=char2rot,proto3" json:"char2rot,omitempty"`
	Char3Pos      *Vector3               `protobuf:"bytes,6,opt,name=char3pos,proto3" json:"char3pos,omitempty"`
	Char3Rot      *Vector3               `protobuf:"bytes,7,opt,name=char3rot,proto3" json:"char3rot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamRedis) Reset() {
	*x = TeamRedis{}
	mi := &file_TeamRedis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamRedis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamRedis) ProtoMessage() {}

func (x *TeamRedis) ProtoReflect() protoreflect.Message {
	mi := &file_TeamRedis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamRedis.ProtoReflect.Descriptor instead.
func (*TeamRedis) Descriptor() ([]byte, []int) {
	return file_TeamRedis_proto_rawDescGZIP(), []int{0}
}

func (x *TeamRedis) GetSaveTime() int64 {
	if x != nil {
		return x.SaveTime
	}
	return 0
}

func (x *TeamRedis) GetChar1Pos() *Vector3 {
	if x != nil {
		return x.Char1Pos
	}
	return nil
}

func (x *TeamRedis) GetChar1Rot() *Vector3 {
	if x != nil {
		return x.Char1Rot
	}
	return nil
}

func (x *TeamRedis) GetChar2Pos() *Vector3 {
	if x != nil {
		return x.Char2Pos
	}
	return nil
}

func (x *TeamRedis) GetChar2Rot() *Vector3 {
	if x != nil {
		return x.Char2Rot
	}
	return nil
}

func (x *TeamRedis) GetChar3Pos() *Vector3 {
	if x != nil {
		return x.Char3Pos
	}
	return nil
}

func (x *TeamRedis) GetChar3Rot() *Vector3 {
	if x != nil {
		return x.Char3Rot
	}
	return nil
}

var File_TeamRedis_proto protoreflect.FileDescriptor

const file_TeamRedis_proto_rawDesc = "" +
	"\n" +
	"\x0fTeamRedis.proto\x12\x05proto\x1a\rVector3.proto\"\xb0\x02\n" +
	"\tTeamRedis\x12\x1b\n" +
	"\tsave_time\x18\x01 \x01(\x03R\bsaveTime\x12*\n" +
	"\bchar1pos\x18\x02 \x01(\v2\x0e.proto.Vector3R\bchar1pos\x12*\n" +
	"\bchar1rot\x18\x03 \x01(\v2\x0e.proto.Vector3R\bchar1rot\x12*\n" +
	"\bchar2pos\x18\x04 \x01(\v2\x0e.proto.Vector3R\bchar2pos\x12*\n" +
	"\bchar2rot\x18\x05 \x01(\v2\x0e.proto.Vector3R\bchar2rot\x12*\n" +
	"\bchar3pos\x18\x06 \x01(\v2\x0e.proto.Vector3R\bchar3pos\x12*\n" +
	"\bchar3rot\x18\a \x01(\v2\x0e.proto.Vector3R\bchar3rotB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_TeamRedis_proto_rawDescOnce sync.Once
	file_TeamRedis_proto_rawDescData []byte
)

func file_TeamRedis_proto_rawDescGZIP() []byte {
	file_TeamRedis_proto_rawDescOnce.Do(func() {
		file_TeamRedis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TeamRedis_proto_rawDesc), len(file_TeamRedis_proto_rawDesc)))
	})
	return file_TeamRedis_proto_rawDescData
}

var file_TeamRedis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TeamRedis_proto_goTypes = []any{
	(*TeamRedis)(nil), // 0: proto.TeamRedis
	(*Vector3)(nil),   // 1: proto.Vector3
}
var file_TeamRedis_proto_depIdxs = []int32{
	1, // 0: proto.TeamRedis.char1pos:type_name -> proto.Vector3
	1, // 1: proto.TeamRedis.char1rot:type_name -> proto.Vector3
	1, // 2: proto.TeamRedis.char2pos:type_name -> proto.Vector3
	1, // 3: proto.TeamRedis.char2rot:type_name -> proto.Vector3
	1, // 4: proto.TeamRedis.char3pos:type_name -> proto.Vector3
	1, // 5: proto.TeamRedis.char3rot:type_name -> proto.Vector3
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_TeamRedis_proto_init() }
func file_TeamRedis_proto_init() {
	if File_TeamRedis_proto != nil {
		return
	}
	file_Vector3_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TeamRedis_proto_rawDesc), len(file_TeamRedis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TeamRedis_proto_goTypes,
		DependencyIndexes: file_TeamRedis_proto_depIdxs,
		MessageInfos:      file_TeamRedis_proto_msgTypes,
	}.Build()
	File_TeamRedis_proto = out.File
	file_TeamRedis_proto_goTypes = nil
	file_TeamRedis_proto_depIdxs = nil
}
