// Extracted message ThrowDiceResult
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ThrowDiceResult.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThrowDiceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiceId        uint32                 `protobuf:"varint,1,opt,name=dice_id,json=diceId,proto3" json:"dice_id,omitempty"`
	Pips          uint32                 `protobuf:"varint,2,opt,name=pips,proto3" json:"pips,omitempty"`
	PlayerName    string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	WonResult     DiceWonResult          `protobuf:"varint,4,opt,name=won_result,json=wonResult,proto3,enum=proto.DiceWonResult" json:"won_result,omitempty"`
	PlayerId      uint32                 `protobuf:"varint,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrowDiceResult) Reset() {
	*x = ThrowDiceResult{}
	mi := &file_ThrowDiceResult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowDiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowDiceResult) ProtoMessage() {}

func (x *ThrowDiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_ThrowDiceResult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowDiceResult.ProtoReflect.Descriptor instead.
func (*ThrowDiceResult) Descriptor() ([]byte, []int) {
	return file_ThrowDiceResult_proto_rawDescGZIP(), []int{0}
}

func (x *ThrowDiceResult) GetDiceId() uint32 {
	if x != nil {
		return x.DiceId
	}
	return 0
}

func (x *ThrowDiceResult) GetPips() uint32 {
	if x != nil {
		return x.Pips
	}
	return 0
}

func (x *ThrowDiceResult) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *ThrowDiceResult) GetWonResult() DiceWonResult {
	if x != nil {
		return x.WonResult
	}
	return DiceWonResult_DiceWonResult_Loss
}

func (x *ThrowDiceResult) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_ThrowDiceResult_proto protoreflect.FileDescriptor

const file_ThrowDiceResult_proto_rawDesc = "" +
	"\n" +
	"\x15ThrowDiceResult.proto\x12\x05proto\x1a\x13DiceWonResult.proto\"\xb1\x01\n" +
	"\x0fThrowDiceResult\x12\x17\n" +
	"\adice_id\x18\x01 \x01(\rR\x06diceId\x12\x12\n" +
	"\x04pips\x18\x02 \x01(\rR\x04pips\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x123\n" +
	"\n" +
	"won_result\x18\x04 \x01(\x0e2\x14.proto.DiceWonResultR\twonResult\x12\x1b\n" +
	"\tplayer_id\x18\x05 \x01(\rR\bplayerIdB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_ThrowDiceResult_proto_rawDescOnce sync.Once
	file_ThrowDiceResult_proto_rawDescData []byte
)

func file_ThrowDiceResult_proto_rawDescGZIP() []byte {
	file_ThrowDiceResult_proto_rawDescOnce.Do(func() {
		file_ThrowDiceResult_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ThrowDiceResult_proto_rawDesc), len(file_ThrowDiceResult_proto_rawDesc)))
	})
	return file_ThrowDiceResult_proto_rawDescData
}

var file_ThrowDiceResult_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ThrowDiceResult_proto_goTypes = []any{
	(*ThrowDiceResult)(nil), // 0: proto.ThrowDiceResult
	(DiceWonResult)(0),      // 1: proto.DiceWonResult
}
var file_ThrowDiceResult_proto_depIdxs = []int32{
	1, // 0: proto.ThrowDiceResult.won_result:type_name -> proto.DiceWonResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ThrowDiceResult_proto_init() }
func file_ThrowDiceResult_proto_init() {
	if File_ThrowDiceResult_proto != nil {
		return
	}
	file_DiceWonResult_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ThrowDiceResult_proto_rawDesc), len(file_ThrowDiceResult_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ThrowDiceResult_proto_goTypes,
		DependencyIndexes: file_ThrowDiceResult_proto_depIdxs,
		MessageInfos:      file_ThrowDiceResult_proto_msgTypes,
	}.Build()
	File_ThrowDiceResult_proto = out.File
	file_ThrowDiceResult_proto_goTypes = nil
	file_ThrowDiceResult_proto_depIdxs = nil
}
