// Extracted message WeaponInscriptionInlaidReq
// Tool: OverfieldTool

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: WeaponInscriptionInlaidReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeaponInscriptionInlaidReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WeaponInstanceId uint32                 `protobuf:"varint,1,opt,name=weapon_instance_id,json=weaponInstanceId,proto3" json:"weapon_instance_id,omitempty"`
	InscriptionId    uint32                 `protobuf:"varint,2,opt,name=inscription_id,json=inscriptionId,proto3" json:"inscription_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WeaponInscriptionInlaidReq) Reset() {
	*x = WeaponInscriptionInlaidReq{}
	mi := &file_WeaponInscriptionInlaidReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponInscriptionInlaidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponInscriptionInlaidReq) ProtoMessage() {}

func (x *WeaponInscriptionInlaidReq) ProtoReflect() protoreflect.Message {
	mi := &file_WeaponInscriptionInlaidReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponInscriptionInlaidReq.ProtoReflect.Descriptor instead.
func (*WeaponInscriptionInlaidReq) Descriptor() ([]byte, []int) {
	return file_WeaponInscriptionInlaidReq_proto_rawDescGZIP(), []int{0}
}

func (x *WeaponInscriptionInlaidReq) GetWeaponInstanceId() uint32 {
	if x != nil {
		return x.WeaponInstanceId
	}
	return 0
}

func (x *WeaponInscriptionInlaidReq) GetInscriptionId() uint32 {
	if x != nil {
		return x.InscriptionId
	}
	return 0
}

var File_WeaponInscriptionInlaidReq_proto protoreflect.FileDescriptor

const file_WeaponInscriptionInlaidReq_proto_rawDesc = "" +
	"\n" +
	" WeaponInscriptionInlaidReq.proto\x12\x05proto\"q\n" +
	"\x1aWeaponInscriptionInlaidReq\x12,\n" +
	"\x12weapon_instance_id\x18\x01 \x01(\rR\x10weaponInstanceId\x12%\n" +
	"\x0einscription_id\x18\x02 \x01(\rR\rinscriptionIdB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_WeaponInscriptionInlaidReq_proto_rawDescOnce sync.Once
	file_WeaponInscriptionInlaidReq_proto_rawDescData []byte
)

func file_WeaponInscriptionInlaidReq_proto_rawDescGZIP() []byte {
	file_WeaponInscriptionInlaidReq_proto_rawDescOnce.Do(func() {
		file_WeaponInscriptionInlaidReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_WeaponInscriptionInlaidReq_proto_rawDesc), len(file_WeaponInscriptionInlaidReq_proto_rawDesc)))
	})
	return file_WeaponInscriptionInlaidReq_proto_rawDescData
}

var file_WeaponInscriptionInlaidReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_WeaponInscriptionInlaidReq_proto_goTypes = []any{
	(*WeaponInscriptionInlaidReq)(nil), // 0: proto.WeaponInscriptionInlaidReq
}
var file_WeaponInscriptionInlaidReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WeaponInscriptionInlaidReq_proto_init() }
func file_WeaponInscriptionInlaidReq_proto_init() {
	if File_WeaponInscriptionInlaidReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_WeaponInscriptionInlaidReq_proto_rawDesc), len(file_WeaponInscriptionInlaidReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WeaponInscriptionInlaidReq_proto_goTypes,
		DependencyIndexes: file_WeaponInscriptionInlaidReq_proto_depIdxs,
		MessageInfos:      file_WeaponInscriptionInlaidReq_proto_msgTypes,
	}.Build()
	File_WeaponInscriptionInlaidReq_proto = out.File
	file_WeaponInscriptionInlaidReq_proto_goTypes = nil
	file_WeaponInscriptionInlaidReq_proto_depIdxs = nil
}
